### ISSUE TITLE
Lights on lander pods or fuel segments

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#100]
Is it possible to integrate lights on the landing cans and/or the lander-core fuel tanks? This to facilitate vision while landing/docking.

**Comment by shadowmage45** [comment]
Not in their current incarnation no.  

I already have a complete rework of the lander-core parts scheduled for 0.9.0 update, and will not be even looking at them again until then (aside from fixing them to work in 1.1 when it breaks everything).
