### ISSUE TITLE
Brainstorm, part 1

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#101]
i'm always building the same thing for tugs probes etc:

Drone core
Hefty reaction wheel
Four solar panels
Radiators
Rcs

Is there some way a single part with all these features and modularity in terms of diameter could be added? Basically it's the two orion parts combined with the exception of kerbal room and storage tanks.

**Comment by shadowmage45** [comment]
That sounds like the planned service modules, almost exactly.
The one exception being I don't like reaction wheels, you will have to mod those into the config / alter their torque (will have one, but low torque)-- I'm fine if it takes a minute to rotate around, and I use RCS on payloads intended for docking manuevers, which often grants more than enough attitude control (sm+payload rcs).

Will likely be configurable diameter, with integrated fuel capacity of some measure.  Feature is a quite a ways off though, at best.

**Comment by Jimbodiah** [comment]
Yeah, I am using the service module from the Orion now with a drone core added, but engine selection is limited to the integrated monoprop one. So looking forward to your new stuff ;)

**Comment by shadowmage45** [comment]
As stated, these features (for the most part) will be what the Modular Service Module is all about.  Please add any feedback regarding its development to its' issue ticket (if/when it is created).
