### ISSUE TITLE
Brainstorm, part 2

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#102]
Modular sattelite with options for probe gear (resource scanners) and scansat functionality. 

M700 survey probe and three scanset probed
Antenna
Solar panels
Battery
Propulsion
Tanks
...

**Comment by shadowmage45** [comment]
https://github.com/shadowmage45/SSTULabs/wiki/Parts-%E2%80%90-Satellite-Core

Planned for -way- down the road.  Likely 6mo-year.  (note the page is created, and has been for a time, but is empty... too far out to even do much concept development on it)

But yes, -eventually- I will be making low-part-count probe/satellite stuff  (and there is another part series geared towards manned/unmanned rovers)
