### ISSUE TITLE
SSTUEngineCluster - Add 'Engine Vertical Offset' slider in VAB

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#103]
To allow for clipping engines inside of a mount or the part above when no mount is present.
## Requirements:

Add variables (temp and persistent) to handle the offset
Add handling to engine model-position update code
Add on-editor-changed code branch for height offset
Add handling of offset position to fairing and node update methods

**Comment by Jimbodiah** [comment]
just press 2?

**Comment by shadowmage45** [comment]
This would do it mostly to offset the engine into its own integrated mount, and or offset it into other parts -while not clipping the fairing or mount model.

**Comment by shadowmage45** [comment]
Mostly this function will be useful with the upcoming 'shroud' series of mounts (and is in fact the main feature that will make those mounts usable with different engines).
