### ISSUE TITLE
Remove Deprecated - SC-C - Sci-Fi part series

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#108]
Official warning/Heads up that the current SC-C part series will be retired and removed from the main download starting with release 0.3.25.

This is being done because the SC-C series is being usurped by the 1.875m command pod/SM series of parts.

Will revisit the orbital freighter concept at a future date -- will be reclassed as SC-OA; Orbital-A series or similar.

**Comment by Jimbodiah** [comment]
I use Rover's FTT mod which has a awesome space freighter with fuelswitch tanks/containers. So maybe a wise choice and focus on the other parts you are working on. Would rather see your smaller parts than the current C series (never used them).
