### ISSUE TITLE
New Parts: Ship Core Docking Ports

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#112]
A selection of docking ports, mostly intended to be used for pre-welded parts.  -Might- make them available as discrete parts as well.
## Features:
- Custom models per stack size for stock sizes
  - 0.625m (size 0)
    - Minimal port, lacks guide plates, maximises usable space, as a kerbal might -barely- fit through it at 0.625m...
  - 1.25m (size 1)
    - Existing 'standard' docking port geometry
    - 1.25m model w/parachutes.
  - 2.5m (size 2)
- Passive and Active models for each?
  - Use mesh-switch to change between them?
## Done:
- 1.25m passive standard geometry and texture first pass
  - Need to adapt it to add some parachute packs to it; likely external geometry.
  - Will be a second part
  - Needs texture finished and re-exported
## Todo:
- Models
- UV
- Bake
- Textures
- Configs

**Comment by Jimbodiah** [comment]
I only use your ports at the moment for all my other ships, so I can dock them all together. So please keep them as a separate part, the chute version as well please.

Would it be an option to make a multi-dock version of the 2.5, so you can dock all three on it?
