### ISSUE TITLE
Remove Deprecated - SC-B-ENG 2/3/4/5

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#115]
Scheduled removal of the SC-B- engine clusters;  they should be replaced effectively by the general engine clusters

**Comment by Jimbodiah** [comment]
which engines are those (SC-B-ENG 2/3/4/5), I can't find them, or do you mean all engine clusters in general?

**Comment by shadowmage45** [comment]
they were the old pre-built SLS engine clusters with RS-25 engine bells only.

All of the new single engines, and engine clusters in the engine cluster tab, will be staying around for the foreseeable future.
