### ISSUE TITLE
New Engine Mount - Radial Engine Mounts

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#117]
A set of 2-3 engine mounts intended to be surface attached and used as radial engines.

Ideally I would like to find a way to enable some of these to have a 'deployed' and 'retracted' state, but that will require more thought (would need to dynamically re-link all the animation stuff up, or manually animate through the plugin; either way requires quite a bit more code).

Ideas --
Space-Shuttle OMS pod (will be needed by upcoming E-series stuff)
Umm.. yah.. no other real ideas yet.

**Comment by Jimbodiah** [comment]
how about the C series engine module. Animation looks cool.

**Comment by Jimbodiah** [comment]
Skycrane engines would be a nice addition.

Lately I use Verniers a lot, maybe one or two versions of those: a plane jane straight firing one and the FASA Atlas swiveling type (but bigger).
