### ISSUE TITLE
New beta will break saves?

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#118]
Nevermind, please delete :(((  Was meant as a ? but forgot the ? mark and you already mentioned the C series would get pulled ;)

**Comment by shadowmage45** [comment]
yep, and that is why this is a pre-release and not the new recommended release; I'm giving people a few weeks to convert stuff / backup the configs if they want to keep them.

**Comment by Jimbodiah** [comment]
:+1:
