### ISSUE TITLE
New command pod

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#119]
First off I want to make clear this is another awesome addition!!!! :100: 

Some things I noticed, I will bunch them all in one issue in fear of starting a flood with all the single ones.
- Could the new pod sit in the water a bit higher? Only the parachute section stick out right now.
  http://dasher.nl/kerbal/sstu_03.jpg
- Is it an option to have floaters deploy? It's cosmetic, but looked so cool on the FASA parts.
- Can the chutes be added to staging somehow? (awesome now with the drogue chutes by the way!, kudos!). There is also no option for making custom actions for it.
- Can't see if it's safe to open chutes now.
- Drogue chutes, always come out and are immediately let go. [edit] strike that for now, depends on altitude it seems.
- I can use your chutes at 55K to slow down from 2300m/s to 100m/s. Who needs heatshields or retro rockets? ;)
- Not able to repack chutes on EVA.
- Will there be a fairing coming from the A-CM to match to the stage below? I take it this is the line "textures not ready yet".
- Looks Awesome!!!!
- Your Saturn V build will not fly; the second stage TWR is too low ;)  But I got to test the abort function and that Looks Awesome!!!!
- Cabin lights and docking lights are both named "activate lights".
- The CM got really hot when I hyperedited it into orbit and put on SAS/RCS/Lights (over 800°K). Cooled down quickly afterwards. This was 55km up.

**Comment by shadowmage45** [comment]
1 - it sits higher than that on my game - do you have any mods messing with buoyancy / water / water rendering (looks like at least some rendering mods)?  Try testing without them.

2 - no

3 - see the note on WIP on the module

4 - ^^

5 - ^^

6 - ^^

7 - nope, you will not be able to repack them

8 - Again, see the note on WIP on the part.  Yes, there will be a fairing, but I need to fix the fairing code to not interact with the drag cube code for the parachutes

9 - Thanks :) still quite a bit to do on both the CM and BPC, but they are coming along

10 - Not my design.  But as long as it is > 0.8 it is probably more than plenty, even 0.5 is doable.

11 - See note on WIP on the module

12 - Yep, see the note on WIP on the module, it still needs some balance and adjustment.

**Comment by Jimbodiah** [comment]
Damn, I need to read the notes ;)  Haha, just pointing out the things I see.

**Comment by shadowmage45** [comment]
No worries, they are mostly all valid points.. just not done yet :)

**Comment by shadowmage45** [comment]
RE 2.) -- it -might- be something I can work into the parachute module at some point; but not any kind of priority;

RE 7.) -- Some chutes you will be able to repack, but not the command module ones; at least initially.  Perhaps I'll have an option to 'bring spares' or something, as it jettisons a ton of stuff before you hit the ground, and you would need something to replace it all.

**Comment by Jimbodiah** [comment]
I tend to use the orion on duna to shuttle kerbals up and down, and deploy the chute on the last part to save fuel or get the bottom pointing down again after the thing flips due to my piloting. Hence the repacking.

**Comment by Jimbodiah** [comment]
![floats_01](https://cloud.githubusercontent.com/assets/16107012/11765303/570f73ec-a151-11e5-80bb-ecb452beade0.jpg)
![floats_02](https://cloud.githubusercontent.com/assets/16107012/11765304/5aacc9a0-a151-11e5-96da-af1b0dc571af.jpg)

**Comment by Jimbodiah** [comment]
PS, if you run out of electricity, you can't open the chutes anymore.

**Comment by shadowmage45** [comment]
Rolled all the actual issues reported here regarding parachutes into #121.  Will be opening another ticket for the HeatShield related issues/enhancements ( #122 ).
