### ISSUE TITLE
SSTUModularParachute - General cleanup / finishing of module

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#121]
## TODO:
- Add functions regarding calculating safe-to-deploy and updating GUI text
  - These are going to be simple; based on mach-heating multiplier and dynamic pressure.
  - -Might- implement chute-heating/cooling to allow for some 'risky' deployment; will likely not be present in initial implementation.
- Add -optional- staging functionality (disabled by default, as pods already have decouplers linked to staging)
- Add second (possibly third) parachute model and texture(s)
- Add in-VAB adjustment of various parameters (auto-deploy altitude/pressure)
- Add manual deploy right-click option / ability to use while command is disabled (e.g. EC run out);
- Add independent scaling of the line and cap models
- Re-export parachute model with fixed geometry and updated default texture name
## Notes:
- Should probably move over to use purely atmo pressure for deploy sequence; altitude is inconsistent and only meaningful on Kerbin
- Need to figure out how stock is doing the shock/heat/drag calculations for the parachute cap and use something very similar to setup for the 'safe to deploy' stuff.
## Done:
- Add action group functionality
- Add independent texture setting to config
  - Will add parachute in-vab texture and model-swap capability in 1.1 after I can do some proper GUIs for the selection.
- Add second/third/fourth/fifth parachute texture (standard, blue, red, orange_alt, x-mas (gag))

**Comment by Jimbodiah** [comment]
A note on the A series integrated chutes:  The do not always deploy fully in time, specially when landing in high terain (mountains). Most of the time the capsule just smashes into the ground or the chute starts to open when the capsule hits. I've seen it a few times around the 1300-1800m terain elevation mark.
