### ISSUE TITLE
New Parts: Ship Core Series E

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#123]
True-to-scale shuttle replica with minimal part count -- should not need 60 parts to make a shuttle, more like 4 (body, main engine cluster, oms pod/engine cluster x 2).  (Might even integrate all of the engines/pods).

-Should- be a relatively small series of parts, probably consisting of a single part -- the shuttle body.

No, this will not be a modular part -- there will be a single design/layout.  Yes, it will have integrated cargo bay + functionality.  No, it will not come with large integrated fuel tanks (shuttle orbiter only had ~600 m/s of DV once it jettisoned the external tank).

Concept at this point, not sure if I want to get into the aero/spaceplane stuff much -- won't really know until I can make and test the initial geometry (basically if a single-piece aero-enabled part will even work at all; more-so that it will have multiple independent control surfaces, and I'm unsure if stock can handle that setup...)

If I cannot pull of the single-part design, I will -not- be doing it at all.  Single part or nothing.
## Features:
- Single part body design
- Integrated aero control surfaces
- Integrated cargo bay
- Integrated wheels
- Integrated RCS
- Possible integrated engines (main + OMS).
- Integrated passive/thermal-soak heat shielding.
- A couple of 'modules' for the cargo bay -- science experiments, and/or ??
- NO - I will not be doing the Canadarm -- other mods already exist for that, and there is always IR.

**Comment by Jimbodiah** [comment]
Whoooot whoooot!!! I WILL fly a shuttle someday :)))  :100:

**Comment by blowfishpro** [comment]
Combing the wings and the body is a very serious issue with FAR - if it were done this way it would not be compatible with FAR at all.  Just letting you know.

Future versions of FAR will allow compound wing shapes, so the additional number of parts wouldn't be that large (two wings, vertical stabilizer, and tail flap).

**Comment by shadowmage45** [comment]
Yah, I'm unsure if stock can support the setup either.  I'm unsure that stock will allow more than a single aero-surface setup in a part;  so this concept may be doomed and never go anywhere;  won't know for another few months (as I won't be able to begin investigating until current planned stuff is done).

**Comment by Jimbodiah** [comment]
Thanks! Downloading it now together with Gimp and Blender (what the hell, right)

**Comment by Jimbodiah** [comment]
To be honest I am antisipating the station parts more. There are no realy good mods with a good set of parts for space stations.

**Comment by blowfishpro** [comment]
Actually, now that I think about it I don't think a single part shuttle would work in stock either - there's no way that control surfaces on opposing wings would trigger correctly (and the vertical stabilizer wouldn't work).  So yeah, the wings have to be separate either way.

**Comment by shadowmage45** [comment]
Yah.. thats what I was afraid of... ohwell, no shuttle I guess.

**Comment by shadowmage45** [comment]
Hmm...
I'm going to re-examine this concept from the standpoint of allowing the -control surfaces- to be separate parts.  So main body + 3 stock ailerons/whatever you want to put on there (left elevon, right elevon, rudder; or 5 if you want split aileron(2)/elevator(2) on the rear).

Yah... I kind of want to make / fly a shuttle too, and the stock-derived stuff just doesn't cut it for me.

Normally I would completely waive-off doing any 'single-purpose' designed part such as this -- but the shuttle, by design, is a multipurpose-vessel; basically a crew capsule + integrated cargo bay.

Anyhow, still a ways off, but might work up a prototype to test the validity here in the next few weeks.

**Comment by blowfishpro** [comment]
If the control surfaces are separate parts, why not just make the wings separate with integrated control surfaces?  This has no effect on overall part count but allows FAR compatibility.

The entire rudder has to be separate under any aerodynamic model - even the stock ModuleLiftingSurface is directional, so no way to provide yaw stability without a separate part.

**Comment by shadowmage45** [comment]
Apparently this concept is just doomed due to stock limitations.  Oh-well.  Not like I really needed more stuff to model anyway.

In short -- if I have to make it multi-part then it is no different than the existing stock stuff.  Floppy joints and falling-off wings and all.
