### ISSUE TITLE
Docking lights on Orion + ports

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#124]
Would it be possible to add docking lights to the docking ports, like on the new Apollo capsule?

**Comment by shadowmage45** [comment]
https://github.com/shadowmage45/SSTULabs/issues/72

**Comment by Jimbodiah** [comment]
doh!

**Comment by shadowmage45** [comment]
No worries :)

Yep, had that one on the planned list for awhile now.  As I'm currently 'stuck' on the heatshield coding, I cut out the new geometry for it today (new mesh layout with 'proper' shading, new window cuts/joins):
![sc-b-cm-preview1](https://cloud.githubusercontent.com/assets/1503399/11856039/3281a16e-a40b-11e5-9887-8510476799ca.png)

**Comment by Jimbodiah** [comment]
Wow, a complete rebuild?

Is the top coming off when the parachute deploys, like on the apollo capsule?
