### ISSUE TITLE
SC-A-CM - Issues / Enhancements

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#126]
(Edited)
- Docking Lights light up planets - Stock bug, no proper workaround/solution; result of ScaledSpace conversions when in timewarp (could disable lights if in non-physics timewarp?)
- ~~Docking Port only connects to 1.25m standard ports -- need to add 0.625m compat~~ DONE
- ~~Ladder/hatch collider issues - perhaps move ladder collider away from main body collider a bit more?~~ DONE
- ~~Ladder collider does not reach to ground/top of pod (even though there are visible ladders)~~ DONE
- Needs fairing for lower node - requires adding a 'don't re-render drag-cubes' flag to the fairing module

**Comment by shadowmage45** [comment]
Docking light - is this all the time, or just during time-warp?  (Timewarp does strange things, have seen that effect with many other mod added lights, and even the stock lights)

Lag/fps drop -- logs?

As everything was fine last night during testing.  I did -many- re-entries without any lag or issue.

Docking port could be related to whatever problem was causing your lag issue (often if one thing goes wrong in KSP it brings down everything else with it, even completely unconnected systems).  Could also be that the transform name did not get updated when I swapped the model.  Or, could yet be a different problem.  Need those logs from above :)

And, I just have to make sure you are using the latest pre-release from last night (0.3.24-pre3 -- https://github.com/shadowmage45/SSTULabs/releases/tag/0.3.24-pre3 )

**Comment by Jimbodiah** [comment]
Downloaded it about 2 hours ago... Will check on the lights, think I saw it in time-warp like you said.

Logs were just overwritten, I restarted KSP :(  I'll try it again in a minute. 

KSP glitches, yeah, tell me a bout it. I sometimes can't use mechjeb, bouncing all over the place so I just restart the game, problem solved.

**Comment by Jimbodiah** [comment]
Lights: Only in time-warp.

Docking port: didn't check yet.

And the rest was KSP freaking out :(

**Comment by shadowmage45** [comment]
Docking port working properly too?  (not sure I tested after I swapped the model; so just want to make sure).

Lights -- stock bug; will look into it a bit -- might be able to figure out what TimeWarp does regarding the apparent compression of space (it looks like it starts rendering the planets as small spheres much closer to the vessel), and apply an inverse function to normalize it.

**Comment by Jimbodiah** [comment]
Just checked port, it will not attach to a clamp-o-tron jr and I think that is the only one that will fit.

**Comment by shadowmage45** [comment]
It is set to size 1 (standard size) -- check it using the standard Clamp-O-Tron and/or SC-B-DP.  (Still need to add the multi-size support that was added in 1.05, after I figure out how it needs to be set in the config).

**Comment by Jimbodiah** [comment]
Docking with B-DP works fine, don't have regular ports on anything, but take your word for it ;)

RCS and reaction wheel work like a charm on the CM/SM combination, as long as the capsule's rcs is turned off. Feels nice to fly, turns quickly, responsive. Nice!!!!!

**Comment by shadowmage45** [comment]
Aye, I 'balanced' the COM on the CM and SM such that the RCS will tend towards near-perfect balance at a half-full SM (with the CM ports turned off), and will again be at near-perfect balance when the SM is emtpy and the CM ports are turned on.  So, in theory, it should be usable with minimal rotation during translation through the entirety of its propellant load.

Closing this for now, as it seems to be a non-issue :)

**Comment by Jimbodiah** [comment]
The pod is nearly impossible to enter again with Kerbals, grabbing makes the kerbal flip all around. I can only get it to work in space with EVA/jetsuits to position right in front of the door. On the ground with any kind of gravity I can't get back in.

**Comment by shadowmage45** [comment]
How do the ladders/hatches feel on the new reworked SC-B-CM?

If they work acceptably, I'll do a very similar setup for the SC-A-CM.  Should be able to get this all done for this weekends' update (01-02-16)

**Comment by Jimbodiah** [comment]
I'll test it tonight.

**Comment by shadowmage45** [comment]
Have updated the airlock and hatch colliders on the SC-A CM to match those of the SC-B-CM as far as size and position is concerned.  Seems much less glitchy and less prone to flying kerbals, and now can easily be entered from the ground.

Have added one more item to the list for this issue, and intend to have it all wrapped up for Sat. release.

**Comment by Jimbodiah** [comment]
The docking port lights light up the planet even when not in time warp (have screenshot if you need).

No problems getting in/out of the pod, but only tested it twice.
