### ISSUE TITLE
Remove Deprecated - remove SC-B-PM & DPM

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#129]
- Remove the dedicated parachute part; I've certainly never used it.
- These changes will allow the removal of the old parachute models and textures, leaving only the new textures dedicated for the parachute models.
- SC-B-DPM -will- still be being removed in the near future (after the new docking ports are finished), as the parachtues (and docking port) are going to be integrated into the pod.
- Parts are scheduled for full removal
- -May- want to investigate re-UV mapping the parachute model to take advantage of the now unused texture space
  - OR - re-use this texture space for the texture for a different geometry parachute (rectangular canopy?)

**Comment by Jimbodiah** [comment]
I use these for every capsule/part that needs chutes (also your lander pods for unassisted landings on Duna/Eve), please keep it in the line-up.

**Comment by shadowmage45** [comment]
They will be removed with the scheduled release.  The model and setup is a hack, and needs to go away.

However, I have also scheduled some replacements to be developed in that time; docking ports with proper parachute handling; where the parachutes don't come out of nowhere / the middle of the door.

Considering the date on the release though, you likely have a couple of weeks to get your craft converted to using the new parts after they are released.

The reason for posting this issue is not to debate whether they will be removed or not (they will be), but to give you an advanced heads-up that they will be removed and give you time to fix your craft before they break.

**Comment by Jimbodiah** [comment]
That is half my sandbox ;)  Can you give a heads-up when the time is ripe?
