### ISSUE TITLE
SSTUModularParachute - General Enhancements

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#131]
(Edited)  
- Add some kind of information that chutes are deployed and waiting for altitude/safety (DONE)
- Change over mains deploy to be radar/raycast based rather than altitude based. (DONE)
- Add staging controls to parachute module.  (DONE)
- Add multi-jettison cap awareness -- jettison the caps directly away from part COM, or according to config setup? (Will be used by SC-B-CM and upcoming parachute-docking-ports)

**Comment by shadowmage45** [comment]
1.) intentional, and mentioned in the patch notes that the icon does not change color yet/etc (will have some text denoting that it is armed/waiting as well)
2.) I added controls for you to adjust altitude; it is your responsibility to set it appropriately (even during final descent if needed).  Yes, it is based on altitude above sea level, inferred to be based on pressure, but simplified to an altitude.  Radar altitude (true altitude) would  not make sense in the context of a pressure-sensor.
3.) No, only a single staging-action is available per part; for the CMs it is used by the integrated decoupler.  Use the now-included action group functionality if you need it hotkeyed

**Comment by Jimbodiah** [comment]
1.) cool
2.) I don't know the altitude; hit the ground then add 1000m in hind-sight ;)
3.) Euhm, what's the staging of the pod, decouple?

**Comment by blowfishpro** [comment]
Just as a note, the stock parachutes use terrain altitude rather than ASL altitude to calculate when to fully deploy.  Deploying based on ASL altitude might be a usability issue because KSP landings tend to be imprecise.

**Comment by shadowmage45** [comment]
3.) I just remembered that 1.05 added per-module staging controls;  so, given that, I can probably add the staging control to the parachute but set it to default=disabled;  that way the player can select what they want to use for the staging action(decoupler or parachute).  I -might- also be able to use this to allow it to be triggered a second time, but will need to do more investigation regarding how a part handles receiving a second OnActivate call (if it receives it at all), and if it receives activate calls when disabled (would have a config field for 'triggeredOnActivate=1 (or 2)' depending if it should activate on first staging action or second).

**Comment by Jimbodiah** [comment]
:+1:

**Comment by shadowmage45** [comment]
WRT # 2 -- You do have a point, at least in that stock does not let you plan your de-orbit accurately.  I have so far not had a problem with altitude, as I generally pre-plan my returns to land me in the ocean; however this capability does not exist in stock (and I use mechjeb for mine).

So, I will consider changing the mains-safety-altitude over to using radar altitude.  However, this presents the problem where that radar altitude might place make it deploy before the drogues are deployed, and/or have other 'density not high enough' issues.

Honestly, I would much rather say 'too bad, plan your missions'; as this is what I do (and would expect of others); but don't feel like dealing with all the whining and bitching regarding it (people are lazy and don't like/know how to plan apparently).

**Comment by Jimbodiah** [comment]
I'm a crazy, seat-of-my-pants type of guy. I just plummet my kerbals down and they can take it or leave it. They are lucky I throw them down on the day side, gha!  ;)   But this way I have no idea about the terain I will be hitting, sometimes it's 0m, sometimes it's 2K. Right now I just aim for water or set the altitude to the max value. I usually go for a coffee break or a pee when they are descending on chutes.

**Comment by shadowmage45** [comment]
Have updated main-deploy altitude to be based on radar-altitude.  It will switch from semi-to full deploy at 75% of whatever is input.  E.g.  If you input 400ft, it will trigger mains semi-deployment at ground alt + 400ft, and switch to mains full-deploy at ground alt + 300ft.

Am still investigating handling of staging action; will probably have something in place in the next day or two.

**Comment by Jimbodiah** [comment]
Thanks Mage!
