### ISSUE TITLE
Modular SRB request, nosecone

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#132]
I'd like to kindly ask if the nose cone for the Atlas V-500 boosters can be added to a future release of the modular SRB?

links:
http://www.b14643.de/Spacerockets_2/United_States_3/Atlas_V/Gallery/SRB_1.jpg
http://space.skyrocket.de/img_lau/atlas-5-551__av-010__new-horizons__2.jpg

**Comment by shadowmage45** [comment]
Pretty sure I already have a slanted nosecones selection on the SRBs?  What would be the point of this particular one?  What advantage would this one give over the existing one?

**Comment by Jimbodiah** [comment]
It looks cooler?

And I like to build rockets that look like real ones. The current slanted pointy one looks funky (in a weird way).

**Comment by shadowmage45** [comment]
Proper place for this discussion is in #70  -  but no, I do not feel like making more geometry (and texturing) just for the heck of it.

**Comment by Jimbodiah** [comment]
![readimage](https://cloud.githubusercontent.com/assets/16107012/11962135/c6a5f15c-a8dd-11e5-96f3-0276472bddd3.jpg)
