### ISSUE TITLE
SSTUDeployableEngine - change over to be an external non-engine based plugin

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#134]
- WARNING - Will likely break any existing in-flight vessels using the old deployable engines module.
- Switch it over to be an external animation-control-only type module; will need to be defined in the config -after- the engines and animations modules so that they are init'd properly and fully by the time it runs init (and/or use the Start() hackaround).
- All user-interaction will need to be routed through the animation-control module
- All user-interaction for the engine will need to be disabled in favor of the user-interface of the animation control module.
- **-MIGHT-** be able to force-disable the engine action groups in favor of ones added manually by the controller plugin.

**Comment by blowfishpro** [comment]
I'll try to research this too.  My recollection is that I couldn't figure out how to disable actions previously, but I didn't look too hard.

**Comment by shadowmage45** [comment]
I'm pretty sure I know how to disable the engines' own action groups and GUI stuff (had to do some of this recently for the auto-depletion-decoupler).

I think I have the basic implementation figured out at this point (granted, I'm at work, so can't test things for a bit) -- just need to sit down and actually write the code for it :)

**Comment by shadowmage45** [comment]
Mostly works/working - still need to re-implement a bit of the gui stuff, and put in place a couple of sanity checks.

Basically turn off stock gui and action groups, and add own events and action groups.  These simply manage the animation and then call Activate() and Shutdown() on the engine module as needed.

This implementation should be compatible with most engine modules;  anything that derives from the stock ModuleEngines.
