### ISSUE TITLE
Custom Decoupler price balance

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#136]
The custom ring decoupler is currently about 10x the price of other decouplers.

**Comment by shadowmage45** [comment]
Have halved the cost per cubic meter; will do some comparisons vs stock decouplers and see how it looks.

**Comment by Jimbodiah** [comment]
Is there a chance to get engine prices balanced? They are all 20k, so I tend not to use them in career mode.
