### ISSUE TITLE
Request LH2 tank

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#138]
Might I ask if you could add just LH2 as an option for the tank fuel-switch? This for nukes that run on LH2 only that used to run on just LF.

**Comment by shadowmage45** [comment]
LH2 is an -optional- resources at this point, that I'm really not sure I'll be keeping around.

With that said, yes, if I keep it around, I will enable the tanks to use LH2 only as an additional fuel option.

BUT -- if I do end up keeping LH2 around, I -will- be implementing boiloff... just a heads up... things won't be OP forever.

**Comment by Jimbodiah** [comment]
NP with boil-off, I only use them as primary lifter anyway, so it's a non-issue for me. You may want to consider a cooling system like KSPI using Ec and I think Nertea is looking into something similar for his LH2 systems.

But if you're thinking about that already, then you are already mentally committed to the idea ;) You have to implement it for us geeks anyway now with the cfg, so might as well just stick it in there as a standard option. If it comes with the mod then anyway (redistribute CR), people will not need to install anything else if they don't already have it from one of the other mods.
