### ISSUE TITLE
SC-GEN-IPA not loading in career

### ISSUE THREAD

**Issue by lynwoodm** [shadowmage45/SSTULabs#139]
Log: https://github.com/lynwoodm/KSP-Files/issues/1

On a new career, with minimal mods. Just a few for functionality and a couple of part mods as per log details. Selected the IPA to load into VAB and it appears as shown in forum.

**Comment by shadowmage45** [comment]
Hmm... apparently I did not add the tech-limits to the config for this part; so the max 'limited' radius will always be zero; hence it showing up as a stick :)

Will add the tech-limits today, and this should be re-testable with the next release (hopefully fixed).

**Comment by Jimbodiah** [comment]
:100:
