### ISSUE TITLE
SC-B-CM - Heatshield needs balanced

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#140]
Part needs max temp increased
Heatshield needs some hand-tuning of the usage curves/etc

**Comment by shadowmage45** [comment]
Balanced for 1600 peak temp, ~450 ablator used, for a mun to 30k capture.   Could possibly be tweaked a bit more, but need to gather more information regarding re-entry from duna/etc returns.

**Comment by lynzrand** [comment]
**Update**

The heatshield is fine with me now in RSS+RealHeat, with this patch[1] installed. It has 187 ablator left when performing a LEO lifting reentry. Might not be enough when reentrying directly from the Moon or Mars.

[1]Patch is:

```
@PART[*]:HAS[ModuleAblator|ModuleHeatShield]:HAS[!%RSSROConfig[*]]:AFTER[DeadlyReentry]:NEEDS[RealSolarSystem,!RealismOverhaul]{
    @MODULE[ModuleAblator|ModuleHeatShield]
    {
        @name = ModuleHeatShield
        // Globally, the base is 5. Consider making this 8.75 for all but Mk1pod
        @lossConst *= 0.0008
        @pyrolysisLossFactor *= 50
        @reentryConductivity = 0.01
        @ablationTempThresh = 1000
    }
}
```

**Comment by shadowmage45** [comment]
That patch does literally nothing for the heatshield on that pod, at least not for the SSTUHeatShield -- that patch would only effect DRE/stock heatshields, neither of which I support.
