### ISSUE TITLE
SSTUModularFuelTank - duplicating models on symmetry updates

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#142]
http://forum.kerbalspaceprogram.com/index.php?/topic/117090-sstulabs-low-part-count-solutions-orbiter-landers-lifters-dev-thread-11-30-15/&do=findComment&comment=2351884

 It occurs when symmetry is on, and only the selected side meets this.  
Reproducing steps:  
(Maybe need Realfuels installed, not sure about it)  
- Select a tank, change its size
- Attach it to a side decoupler(I've only tested with this), do not add anything in the bottom.
- Change its length, size, nose or mount for a few times
- Notice collided texture on one side

If it doesn't reproduce the issue, try detaching it and attach again. For me, it works.

**Comment by Jimbodiah** [comment]
I had it without real fuels or MFT.

**Comment by shadowmage45** [comment]
Tracked it down to the method I was using to update symmetry -- was feeding it the symmetry counterparts the references for the data from the updated part, rather than their own data/objects.

Fixed in dev, and it all seems to be playing nicely now.
