### ISSUE TITLE
Parachute inoperable when Realchute and FAR installed

### ISSUE THREAD

**Issue by lynzrand** [shadowmage45/SSTULabs#144]
Parachute inoperable (at least for me) when Realchute and FAR installed. The craft just accelerates and hits the ground hard.

Steps:
- Install FAR and Realchute
- Drop the pod with either parachute-installed SSTU parts attached to the top, then deploy the chute.
- Watch it accelerates to the ground with the chute above
- BOOM!

A RC Patch is needed for this probably.

**Comment by shadowmage45** [comment]
Feel free to submit a PR with the requisite fixes then (code or config).  I do not use FAR or Realchute, and will not be supporting either.

Edit: If you find there is a code-side change needed for interoperability, please let me know and I will be glad to make accomodations.

**Comment by lynzrand** [comment]
Got it. I may do it after my final exam.

**Comment by shadowmage45** [comment]
Moving this under #193 --  Will investigate at some point in the next few releases.  However if you do find a solution before I do, please let me know :)
