### ISSUE TITLE
Fairings on tanks will not scale down to 0.625

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#145]
I just noticed when trying to build a 0.625m rockets that the modular tank fairings will not scale lower than around 1m.

**Comment by shadowmage45** [comment]
These are actually just config fields in the configs for the fairings, so you are free to set them to whatever min/max values you want, through direct editing or user-made patch.

However, I have set the default value to 0.3125 for the module for top/bottom min radius.  This - might- have strange side-effects, but will deal with those as they become apparent.

**Comment by Jimbodiah** [comment]
Thanks!!! :+1:
