### ISSUE TITLE
Engine price list

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#148]
Mage, no idea how pull-requests work, so here goes via Issues...

I made a brief excel sheet listing your engines (singles only) and stock equivalents. The final column is a recommendation, but please feel free to change to your own insight. The smaller ones will become cheaper, the large ones more expensive.

http://kerbal.nl/sstu_engines.xlsx

**Comment by shadowmage45** [comment]
Thanks for the data.

Prices seemed reasonable, and have been merged into dev configs.  Will be available with the next update/release.

**Comment by Jimbodiah** [comment]
:+1:   Thanks, Mage!
