### ISSUE TITLE
USI LS patch

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#149]
Should you want to include it at some point...

USI LifeSupport (Supplies/Mulch) for 3 days on each CM/CMX and 9 additional days on each SM.

http://kerbal.nl/sstu/USI_LS.cfg

**Comment by shadowmage45** [comment]
https://github.com/shadowmage45/SSTULabs/pull/152

**Comment by shadowmage45** [comment]
Please reduce the mass of the parts proportionate to the mass of the supplies being added to them and I will merge this in.

**Comment by Jimbodiah** [comment]
Other than changing your cfg files for the parts in question, I don't know how to do that. Or is that what you want me to do?

**Comment by Jimbodiah** [comment]
The difference is 0.004t on the A-CM for the TAC load-out, and 0.008t for the B-CM (this x3 for the respective SMs). I think that is negligible, correct me if I am wrong. 

Yeah, 4kg for 3 guys for 3 days, talk about rationing!

**Comment by shadowmage45** [comment]
:)

Sounds reasonable for mass, and likely un-noticable from a thrust/balancing perspective.

For reference, you can change the mass of a part in the same patch file that adds the resources, such as:

```
@[part_name]
{
@mass = <set mass>
@mass =+ <add mass>
@mass -= <subtract mass>
}
```

Will work on merging these in for the next release

**Comment by Jimbodiah** [comment]
All new to me, thanks!!! Seems pretty straight forward.

@mass is the new mass, could you reference it like  @mass = mass + 0.002?   I get that @mass =+ 0.002 also works, just trying to figure out how the variables work between original mod and patch.

Also, can I call another module in that patch as well. Say I want to use the TAC CO2 scrubber module in the Apollo SM (now where have we seen that before), would that work if implemented in this TAC_LS patch?

**Comment by shadowmage45** [comment]
the syntax for manpulation via variables is a bit more complex than that --
https://github.com/sarbian/ModuleManager/wiki/Module-Manager-Syntax
https://github.com/sarbian/ModuleManager/wiki/Module-Manager-Handbook

```
//This would return the mass of the current part:
@MODULE[ModuleEngines]
{
    @PROPELLANT[LiquidFuel]
    {
        @mass = #$../../mass$
    }
}
```

Is how you reference the mass while in an engine module;  I'm not sure how to reference the mass for a part within its own part file, but its likely something similar.

MODULES -- yep, you can add new modules with a patch, just omit the @ on the module definition (the @ tells it to -modify existing-; without the @, it will -add new-).

**Comment by shadowmage45** [comment]
LS patches have been merged into dev and distro repositories, will be available with the next update.

**Comment by Jimbodiah** [comment]
Thank you!
