### ISSUE TITLE
New Parts: SC-ENG-RS-68 Engine Mount / General Engine Shrouds

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#150]
Single-size (3.75m) purpose-built shroud for RS-68 engine, to mimic those on the Delta-IV launch vehicles.  Will not be available for clusters, and will only be available in a single size.

**Comment by blowfishpro** [comment]
It could probably be adapted to other engines with some minor modifications.  The RS-25 is about the same size as the RS-68, so if you eliminate the cutout/bulge for the turbine exhaust ports it would almost certainly fit nicely.  If you open up the bottom of the bulge it might be able to fit the F-1 at a larger stack size (see [this](http://historicspacecraft.com/Photos/Rockets/Delta4CBC_AFSMM2009RK_01.jpg) image)

**Comment by shadowmage45** [comment]
As I just added a 'vertical offset' capability to the engine plugin, re-using (or creating a very similar) shroud for other engines is now much more doable.

Will consider creating a few more generic varieties and including those (and the specialized rs-68 shroud) all as the next round of mounts (can usually fit 3-4 per texture).
