### ISSUE TITLE
Science levels for engines

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#151]
Request to start off earlier with lighter engines and work up.

![image](https://cloud.githubusercontent.com/assets/16107012/12252231/a81a516c-b8d5-11e5-89e6-48c45bf6603b.png)

**Comment by shadowmage45** [comment]
Actual tech-node names (need these names for config values; cannot use the names as listed above, those are the description names)
AJ10-190 - generalRocketry
AJ10-137 - 
RL10A-3 - generalRocketry
RL10A-4 - 
RL10B-2 - 
J-2 - heavyRocketry
RS-25 - 
RS-68 - veryHeavyRocketry
F1 - heavierRocketry
F1B - veryHeavyRocketry

Cannot locate any 'precision propulsion' node data, nor 'propulsion systems' (http://wiki.kerbalspaceprogram.com/wiki/CFG_File_Documentation#PARTS_Configuration_Files)
Will do further research when I have access to the live research-tree data.

Will also need to look over these a bit more -- most of these engines will only be available later in the game (mostly after 3.75m stuff is unlocked).  Prior to that point it will be mostly stock engines (until I can find and model a few smaller ones).

**Comment by Jimbodiah** [comment]
Even smaller engines? These are already flea-powered ;)  I'll see if I can find the actual names; these came from the TechTree in-game.

**Comment by shadowmage45** [comment]
Please see #88, as it is the proper place for this discussion.  Have started a google-docs spreadsheet to maintain the information.
