### ISSUE TITLE
SC-GEN decoupling

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#162]
It is not clear which "disable staging" is which end. Perhaps change the text (I know it's WIP ;) ). 

Perhaps the possibility to also make the decoupler one step shorter (size of the ullage motors)?

Love it!!!!!

**Comment by shadowmage45** [comment]
Yep, you need to use the 'enable/disable' staging controls in the editor.  (I have not finished the config, so they have not been fixed there yet)

I cannot change those texts -- is part of the stock decoupler modules, and not under my control (as far as I'm aware... will check though, perhaps they made it a config value).

Size -- hmm... perhaps; would require quite a bit of additional code to handle, as the 'minimum size' would then be dependent upon the current scale of the ullage motor.

And of course the thrust / fuel quantity still needs balanced (it is probably a bit overpowered at the moment).

**Comment by Jimbodiah** [comment]
The first report of blowing up was me not getting how to detach it, gheghe ;)   But I do get explosions when I add both retro and ullage to each other, trying to figure out how that will work.

As for text, can you fix that the top one will be the top of the decoupler and the bottom text the bottom of the decoupler?

Re scale: it's no biggy, just leave it as-is.

The flame is bigger than that of my engine ;) Cool looking though, and gets your blood pumping when it seperates.

**Comment by Jimbodiah** [comment]
This decoupler will also solve the issue I made asking for an inverted petal type fairing, as I can now taper the bottom section (or top depending on how you look at it) on something like an Ares V with the tapered EDS tank and larger diameter first stage. So two of my requests in one, how cool is that?!

**Comment by shadowmage45** [comment]
Have switched around the order of the modules, and adjusted the decoupler text to clearly state which staging you are adjusting.  Apparently that was part of the 1.05 changes as well -- adding per-module staging stuff to all part modules at the base level.

I probably will be adjusting the flame a bit; the entire thing was cloned from one of the BPCs I think, so its a bit...large.

Will look into lowering the minimum size dynamically to the model height;  it would mean removing the config value entirely for minimum height, or else setting it to an extremely small value.

Have also removed the exhaust damage from the engine module, and they should be much safer to use in both retro and ullage configurations.

**Comment by epower1** [comment]
Something very odd with the new decoupler for me.  
After attaching to the upper stage, the decoupler will not recognize a right click for GUI.
Further, it can no longer be removed from the rocket.  If I drop it unattached into the VAB I can no longer select it.  I checked the debug and the only thing that came up was an error "Cannot find fx group for that decoupler."

Repeated on a freshly downloaded version of KSP windows and SSTU -0.3.26-pre-3. No other mods.
I'm assuming the output log would be of use.  Should I post it on the forum in a spoiler so I don't clutter github with it?

**Comment by Jimbodiah** [comment]
The decoupler can only be selected by clicking on one of the four motors. is this what you are ecperiencing?

**Comment by epower1** [comment]
Bingo.  I must have missed that part.  Thank you very much.

**Comment by Jimbodiah** [comment]
I think this is because it's not finished yet.

**Comment by shadowmage45** [comment]
For reference, please post bug repots/logs/etc HERE -- the forum is NOT the place for them (they will get lost, forgotten about, and the problem never fixed).  The forum is for discussion, general feedback, brainstorming, showing off your creations, etc.

Re - colliders -- will not be changing.  KSP does not support non-convex colliders (hollow colliders) -- so the fairings will not have colliders.  You will -always- need to grab this part by the motors.

**Comment by Jimbodiah** [comment]
Could auto-decouple be enabled by default?

**Comment by Jimbodiah** [comment]
The motors don't really do anything on small diameter (1.25 and lower) tanks now, I think thrust and fuel may be too low.

**Comment by shadowmage45** [comment]
Quite possible, I didn't do any rebalancing after I 'fixed' the plugin end of the rescaling.

Will look into this over the weekend; should have it rebalanced for the next release.
