### ISSUE TITLE
SC-FR staging detached payload

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#174]
Is it possible to detach the payload on a manual command as per the petal adapter? On most cases I do not want to release the payload when the fairings are dropped. ie a LEM on top of a departure stage where I need to dock the Orion to it and burn to the Moon; here I want to detach the fairings, but not the payload.

Re the fairings in general: I tend not to use them, same with the stock ones. The great benefit of procedural fairings is that they also strut the payload in place so it does not bend like an elastic band as with the stock fairing systems, and you get better looking fairings to be honest. I know Chaka uses the ProcFairing plug-in (so it might be redistribute-able) and even has other fairing shapes added. Maybe this is the way to go, or duplicate that functionality into your own coded model?

**Comment by shadowmage45** [comment]
1.)  Right click on the part and disable the decoupler staging.

2.)  Nope, I will not bundle/rely on external plugins, for the reasons I've posted many times.  (And I don't like the way p-fairings work anyway).  And no, I will not be duplicating their code... as I don't like how they function in the first place.

**Comment by shadowmage45** [comment]
Will default the decouplers on the fairings to be not-staged (as apparently I forgot that when setting up the parts)

**Comment by Jimbodiah** [comment]
1.) Thanks! Sometimes life is too simple for me to see it (most of the time just too complex).

2.) Hence the question if you could do something similar, as I know you don't want dependencies and rather make your own modules. Right now I have stuff hanging out the fairing if I wobble too much, or the payload will just start to wobble and transfer this to the ship which tries to compensate (SAS).
