### ISSUE TITLE
A-CM surface attach

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#177]
Surface attach to the A-CM is a bit tricky on some places. I often add science parts there but on some parts it will float in the air or the angle will jump.

**Comment by Jimbodiah** [comment]
I have just used the A-CMX on a munlander, and can not board it once I EVA, also there is no ladder to grab near the door as on the CMX (edit from CM). Had it twice in a row. Had not tested this before as I tend to use the Orion for everything, but just started a new career.

**Comment by shadowmage45** [comment]
Colliders - I use an optimized 12-sided collider, that doesn't fit the visible mesh perfectly, so there will undoubtably be places where things don't line up perfectly.  Unavoidable unless I double/quadruple the number of verts or tris on the collider, which is very detrimental to performance if applied to too many parts.

CMX ladder/hatches -- noted and fixed.  Apparently I had not marked them as a trigger collider.  Will be available with the next update.

**Comment by Jimbodiah** [comment]
:+1:
