### ISSUE TITLE
A-CM parachute

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#179]
A lot of times I do not get the Safe to deploy message even though velocity is under 260m/s and altitude is <2km.

Chute deploy text reads "unsfe", don't know if this is a typo or just too long to fit otherwise.

**Comment by shadowmage45** [comment]
Thanks, will take a look at it -- are you using any heating changing mods?  (as the safety check depends on some ksp thermal global values, among other things)

Also, it is pressure-curve based -- so 250@2k might be just too fast too low (too much pressure, would rip the chute apart); this is a separate check from the thermal shock check (thermal check mostly kicks in ~>mach1).

Generally it is intended that you should be around 250 m/s closer to 6-8k, where the lower air-pressure results in lower dynamic pressure, and thus safe-to-deploy; but I will take a look at some re-entries to verify that it is all functioning as intended

Typo -- noted and fixed.

**Comment by Jimbodiah** [comment]
No other mods but parts, no FAR/DRE or anything. I was watching from around 8K when I could open my chute, up but it only dips under 250m/s around the 5-6K point. At 2K it is already well under 200m/s. But when I deploy anyway under 250m/s it just opens up without any problem.

**Comment by shadowmage45** [comment]
I had no problems with re-entry speeds or parachutes not opening during testing.  Please delete your PartDatabase.cfg file (contains drag cube data) and allow it to regenerate, and test again to see if the problem persists.

**Comment by Jimbodiah** [comment]
That seems to have fixed it, did two runs and no issue with the unsafe message.

**Comment by shadowmage45** [comment]
Thanks, please let me know if it pops up again; will re-open and investigate more.
