### ISSUE TITLE
Ship Core: Series C - Issues and Enhancements

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#181]
## General Issues Tracking
- ~~Buoyancy of SC-C-DM - floats mostly submerged~~
- ~~Add second DM variant without periscope, or just remove it entirely - the OM now has a forward facing window....~~
- ~~Increase size of hatch on OM so that a kerbal might have a chance of fitting through it. (will require geometry adjust, re-uv/update-uv, rebake, and retexture).~~
- ~~Finish / add emissive textures (can copy from series-a optimized glow texture)~~
- ~~Decrease SAS torque power~~
- ~~Decrease RCS thruster power~~
- ~~Decrease mass~~
- ~~Add drag cube modifier back onto BPC; it helps it for a variety of reasons (and is a good incentive to mount it on the nose of a vessel)~~
- ~~Investigate DM hatch usability~~
### Original Post

```
Hi Mage,

Just some questions and remarks. Love this thing already!!!

- Cabin lights on/off... WIP textures probably?
- Will the DM come with a port on the top, so it can be used for other builds?
- The capsule is completely submerged on splash down, the water just covers the top of the capsule (does not sink though)
- SAS torque is a bit OP
- The engine flame is quite a bit behind the craft, and HUGE. I thought I was firing up an F1 
- I will PR the new LS patches in a minute to go with the next update
- The solar panels don't track the sun.
- Will the periscope work with some sort of docking mod eventually, or didn't you once mention you would make a camera view?
```

**Comment by shadowmage45** [comment]
Mostly it can be summed up as -- prototype parts, nothing is finished yet...
- Lights - textures are not finished for the emissives, hence, no glow
- DM - nope, no docking port (real thing does not have a docking port there), will stay as a simple attach node.  However, it does have an airlock/hatch on the top so it could be used as a stand-alone module with docking port located elsewhere.
- Floating -- will check, might need to adjust buoyancy center or something (also, its quite heavy at the moment)
- SAS - yes, needs decreased all around, if you find some good #'s, let me know
- effects - just fixed in dev (doing an effects pass)
- solar panels - nope, fixed panels; real soyuz panels are not sun tracking either
- perisocope - yes, and no.  Yes it will work with RPM cameras view (or possibly others.. hullcam?), but would need patches to enable it.  No, I will not be making a camera view.  Considering making a variant without periscope, as I'm not a huge fan of it myself.

**Comment by Jimbodiah** [comment]
"solar panels - nope, fixed panels; real soyuz panels are not sun tracking either"

Damn those cheap russians!!!

Re the periscope, yeah it sticks out like a sore thumb. Looks stock-alike too to be honest, but so does the real thing. Russians were never into styling anything. Ever check out the ISS tours, where you notice right away you are in the Russian section.

**Comment by shadowmage45** [comment]
Yah, they generally go more for function over fashion, and will go to great lengths to optimize their designs.  But it also seems to work out well that way in the end, even if it does result in some 'strange' looking designs.

Will leave this issue open for general tracking of problems with the Series-C stuff;  please feel free to update it with any other info as it pops up.  Will be updating/editing the OP/title shortly.

**Comment by Jimbodiah** [comment]
The solar panel of the C only works on one side (ie facing the sun one way or the other), is this correct?

**Comment by shadowmage45** [comment]
Yes, that is intended and correct, and as far as I know the way those panels actually function.

Edit:  When the textures are finished, this will be more apparent, as the side that will not produce power will have all of the back-side frame details on it.

**Comment by Jimbodiah** [comment]
You can EVA on the launchpad while the LAS is on, which means the kerbal just drops down. Is there any way to block EVA when the LAS is attached? Also, is there any way to get back in when you EVA on a complete OM/DM/CM?

**Comment by shadowmage45** [comment]
Should be a hatch on the OM (the round gray thing).

**Comment by Jimbodiah** [comment]
The docking port you mean?

**Comment by shadowmage45** [comment]
nope, on the side of the OM there is a round opening; that is where the EVA hatch is located.

![screenshot1](https://cloud.githubusercontent.com/assets/1503399/12407171/e0593872-be11-11e5-8029-95e9804fd559.png)

**Comment by Jimbodiah** [comment]
Ah okay. I'll try it out tomorrow.

**Comment by shadowmage45** [comment]
Any other issues with these parts that I should try and clean up?  Only things left that I'm aware of are cosmetic stuff -- periscope and eva hatches.

**Comment by Jimbodiah** [comment]
Eva frim DM sends you spinning into space

**Comment by shadowmage45** [comment]
Is that while the DM is by itself?  
You should only be EVA'ing from the DM after the OM has been jettisoned (or at least the OM is not present).  
Stock code should prevent you from doing it otherwise (it should say hatch obstructed).
