### ISSUE TITLE
RS68 clusters

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#184]
Could these (2-4 engines) also get the Jupiter style mounts?

**Comment by shadowmage45** [comment]
No, the engine will not fit in those mounts at any reasonable scale.  I intentionally removed that mount from the engine after I saw how poorly they fit.  Don't blame me, blame the designers of DIRECT/Jupiter rocket renderings -- they did not include the thrust structure or exhaust arms in their designs (at the given design scales, it would be impossible for the engine geometry to fit in some of their designs, without massive modification to the engine).

**Comment by shadowmage45** [comment]
Using the in-line mount might work better with the upcoming custom RS-68 variant I have planned -- it does away with the thrust arms and shortens the mounting cage making it much more suitable for clustering of the engine and use in generic mounts.  Not sure when I'll get around to finishing this engine, but it is on the planned list and already has most of the geometry available from the existing

**Comment by Jimbodiah** [comment]
Ok. thanks
