### ISSUE TITLE
SC-A & SC-B mass rebalance

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#189]
SC-A-CM - 5,560 kg \* 0.44 = 2446.4kg  (or 2.5t); only slightly less than the 3.1 that it currently sits at
New Mass = 2.5t (total, including ablator, monoprop, etc)

SC-A-SM - 24,520 kg \* 0.44 = 10788.8kg (10.8t) (total mass) -- 6110kg dry mass \* 0.44 = 2668kg (currently @ 3.5t, reduction of ~0.8t).
New Mass = 10.8t total, 2.7t dry, 8.1t propellant

SC-B-CM - 10387kg \* 0.44 = 4570.28kg (4.6t); current is 5.2, reduction of 0.6t
New Mass = 4.6t

SC-B-SM - 15461kg \* 0.44 = 6802.84kg(total mass) -- 6185kg dry mass \* 0.44 = 2721.4kg (currently @ 6t, reduction of ~3.2t).
New Mass = 6.8t total, 2.7t dry, 4.1 propellant
### Progress:
- Masses have been adjusted.
- SC-C Parachute re-adjusted, ~6m/s @ SL
- SC-C-DM drag looks good now, properly slows to <250m/s by ~8k
### TODO:
- Need to recalc heat stats for SM's
- SC-A-CM parachute untested
- SC-A-CM heatshield untested
- SC-A-CM drag untested
- SC-A-SM needs heat recalculated
- SC-B-CM parachute untested
- SC-B-CM heatshield untested
- SC-B-CM drag untested
- SC-B-SM needs heat recalculated
- SC-C-DM needs heat-shield efficiency reduced
- SC-C-SM needs heat recalculated

**Comment by Jimbodiah** [comment]
Quite a bit on the B-CM. I've changed my cfg to reflect the new weights (my A-CM was already at 2.5t though). I tend to increase thrust to 40-50 to make the Orion playable, as with 11 we're in the realm of ion engines and burns take forever (1s per m/s dV). Will see how this balances out.

**Comment by shadowmage45** [comment]
LoL, 50kn is more than the -real- SM has (it only has ~30kn).  Its more of a thruster than an engine, and burns are supposed to take several minutes.

SC-B = 11.4t @ 11kn = ~0.095 TWR

Real Orion = ~26t @ ~30kn = ~0.1 TWR

I would say it is very close, and quite acceptable :)

**Comment by Jimbodiah** [comment]
I dont have the patience at 11kN ;)

**Comment by shadowmage45** [comment]
Ahh.. I have no problem with 20+ minute burns (ions/NFP stuff), and I think the longest I've done was about 1 1/2 hour burn (Kerbin -> Jool insertion burn from a 2m meter orbit, on some crazy orbital shipyard that was never meant to transfer between planets)(done at 4x physical warp, as that is just a looong burn otherwise).

Good thing there is always ModuleManager to settle such differences :)

**Comment by Jimbodiah** [comment]
How do you get warp in orbit? I just go drink coffee or watch youtube videos while I wait. No problem for a 4 year mission to duna, but freaking annoying for the first out of ten tourist/sattelite/resupply hauls I want to make to the mun/minmus.

What do you mean with MM? Tell me, tell me... what am I missing?

**Comment by shadowmage45** [comment]
Hit Alt + > and you'll get physics timewarp, can be used anytime, even with engines turned on.  Only goes to 4x, but, it certainly helps with super long burns.

ModuleManager -- You know you can write your own patches to stuff right (you don't need to edit config files)?  That is what one of the main functions of ModuleManager -- end-user patches.  That way you can write a patch to set things to whatever values you want, keep it in a separate directly for your personal patches, and whenever your mods update, you can just update them without worrying about having to go back through and re-edit things.

**Comment by Jimbodiah** [comment]
Jezussss... Never knew about the time warp with alt.

Mm: I have some patch cfgs like the tac and usi LS I sent to you, is that what you mean? I have some to change other parts as well, maybe I am using MM and just don't know it?

**Comment by shadowmage45** [comment]
Yep, those are pretty much what I was referring to.

You can use the same methods to adjust the thrust on engines, their ISP, the fuel-ratios/fuel types, part masses, models, textures (where defined in config), part scales, descriptions, costs, tech-nodes... anything that is in the config file.

**Comment by Jimbodiah** [comment]
Yep, but I hardly change anything, just LS patches really. Only the thrust on the Orion, the rest is stock now that you've changed the SAS on the LCs and prices on the engines... i should PR the orion thrust ;)
