### ISSUE TITLE
Work with magico from StageRecovery to implement generic recovery API

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#200]

**Comment by Jimbodiah** [comment]
:+1:

**Comment by shadowmage45** [comment]
I've been talking with him over the past few days to work out a generic API that can be used by -anything- that adds drag to a vessel.

The goal is to get an implementation that will not require hard-coding to support other mods' interaction -- they would merely need to implement and register a callback method the API can query to determine the drag force for a vessel, and thus its terminal velocity.

This could, in theory, be applied to nearly anything -- ballutes, air-brakes, parachutes, etc.

**Comment by Jimbodiah** [comment]
Are there any plans to add a gridfins part for braking/steering at some point? Together with chutes in the nosecone, this might be a good combination for StageRecovery.

**Comment by shadowmage45** [comment]
Negative on the steering and braking.

This is to get SSTU parachutes (or other drag-causing parts) to work with StageRecovery.  This has nothing to do with control surfaces or use of the parts on an active vessel to actually create drag -- just a means to estimate terminal velocity for a discarded stage for the purposes of StageRecovery.
