### ISSUE TITLE
Engine pricing on Merlin/J2X/H2 and rebalance RL10s

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#206]
Hi Mage,

Could you please change the pricing of the new engines as follows (balanced according to existing ones):
Merlin 1B: 2750
H2: 7500
J2-X: 9500

Rebalance:
RL10A-3: 400
RL10A-4: 525
RL10B-2: 650

I noticed that basically the prices all boil down to ±9.5 x Thrust

**Comment by shadowmage45** [comment]
Sounds good to me; configs have been updated dev-side.

Most engines will probably follow a very simple formula, aside from those where there are context based reasons to do otherwise (e.g. RS-68 and F-1B are 'low cost' engines, RS-25 is a 'high-cost/re-usable' engine).

**Comment by Jimbodiah** [comment]
Thanks! Final balance is up to you, these figures just follow the stock values for now to make them useable in career.
