### ISSUE TITLE
SC-TANK - Volumes vs. Cryo-Engines / NF Tanks for LH2O and LH2

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#207]
It seems SSTU tanks hold less LH2 than stock tanks or other mods. The ratio is almost exactly 50% for LH2-Only and about 25% for LH2/Ox.

LF/Ox matches stock 1:1, so no issues there.

**Comment by shadowmage45** [comment]
As stated on the thread, from your pictures, this appears to be an error in someone's factoring/calculating for their volumes.

The big-orange stock tank only holds 32k liters (32m^3).  But they have 64k liters (64m^3) of LH2 in there somehow? (verified that it was 64k liters by checking the mass vs the density listed in the part-resource).

**Comment by Jimbodiah** [comment]
The fuel switch is from CryoTanks. I will ask Nertea how he got that value.

**Comment by blowfishpro** [comment]
Nertea definitely doesn't use a constant units to volume conversion.  If I'm reading [this patch](https://github.com/ChrisAdderley/CryoTanks/blob/master/GameData/CryoTanks/Patches/CryoTanksFuelTankSwitcher.cfg) correctly, then a 1 unit tank (which would hold 0.55 units of oxidizer and 0.45 of LiquidFuel) would hold 10 units of pure LH2, or 6 units of LH2 and 0.4 units of oxidizer.

**Comment by shadowmage45** [comment]
As the double-density tanks are intentionally done by Cryo-Engines, I am going to leave this issue open for a few days/weeks for general feedback and discussion regarding the LH2 volume and mass balancing.

### Volume balancing:

Current thinking is to just leave things as-is.  If other mods want to use non-realistic volumes in their tanks, that is entirely their choice.  -Might- offer a patch to make other mods' volumes consistent with reality, though this would likely be an optional patch, disabled by default (I don't like messing with other peoples' balance).

### Mass balancing:

Likely need to do a bit more examination regarding the dry-masses of LH2 tanks.  In general they should have a slightly worse mass-fraction than LFO tanks; whereas they use the exact same mass fraction in my current setup.  Easy enough to adjust, but need to find a good balance for it / good statistics to base things on.
