### ISSUE TITLE
General Enhancement - Add differential thrust capability to RBDC (different top/bottom thrusts)

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#209]
Should allow for much finer balancing of the jettison trajectory and spin.

Will require two engine modules; one for top, one for bottom.
Can use the stock thrust-limiters to effect differential.

Implementation wise this will require re-exporting the model through Unity with a unique set of transform names for each top and bottom rings.

Will also require adjusting the module to adjust the -max- thrust on both engine modules.

**Comment by Jimbodiah** [comment]
:+1:
