### ISSUE TITLE
Modular SRB, first glance

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#215]
Awesome, Mage. I'm in love with these new boosters already!!!

The only thing I noticed so far is that the nozzle angle is identical in symmetry mode, meaning they both point to the left instead of outward with two, and different directions on 3+ boosters.

[edit] on't know if it's just my KSP acting up, but with larger boosters it seems they always hang/droop/wobble in the RBDC instead of being fixed/locked.

I'll play more with the tomorrow (3am here)

**Comment by lynwoodm** [comment]
I've always had this problem with the boosters not staying in the RBDC. I don't know if it's me or a real bug. In any case, I put 2 pairs of struts on it to keep it steady. Makes me wonder if I am doing something wrong, even after carefully placing the boosters in these things and carefully measuring every aspect to make sure they are properly seated in the RBDC and they still flop out. _shrugs_ I figured it was just user error and just strut it up and keep my trap shut.

**Comment by Jimbodiah** [comment]
Yeah, that does seem to be a stock issue, but when I went back to the hangar and launched again, it would usually go away. Now with the new boosters it seems to manifest every time and will not go away. Just mentioning it as I noticed this behavior.

**Comment by shadowmage45** [comment]
Nozzle angling - noted and fixed.

Joint mechanics -- nothing I can do regarding stock joint mechanics; they suck; it is a known problem, and the reason KJR exists.

**Comment by lynwoodm** [comment]
Figured as much on the joint mechanics. Even though I have KJR installed, it doesn't stop the wobbling. Not asking for a fix nor requesting anyone to look into it. Easy fix for me is to add struts.

**Comment by shadowmage45** [comment]
Have just noticed that the diameter fine-adjust slider does not work properly.  Looking into this now.

Have also just fixed some null-refs with the default nozzle-type that would cause the gimbal/MJ to stop functioning.

Joints -- if it is still a problem with installed KJR then there -might- be something going on with it.  I do not have KJR on my dev install and generally result to using struts for larger test-craft.  Will do some investigations with KJR installed to see if I can duplicate the problem  (others have reported similar in the past with the old SRBs, but I was unable to duplicate it).

**Comment by shadowmage45** [comment]
I just tested with KJR, and I could not duplicate any floppy-booster problems:

Those are 2.5m diameter x ~25m boosters, with no struts, and would def. be sagging in stock.

![screenshot4](https://cloud.githubusercontent.com/assets/1503399/12874483/1210cd28-cd92-11e5-8cff-404241e052a6.png)

**Comment by lynwoodm** [comment]
Okay, seems legit that it works for you. Here's my results. 

Looks like it's set in there doesn't it? This is the standard SSTU 5 segment SRB. 
![screenshot from 2016-02-07 14 36 48](https://cloud.githubusercontent.com/assets/15900022/12874818/d1e7516e-cda9-11e5-88b6-cf5f9101fd63.png)

Get on launch pad and this is what happens. 

![screenshot from 2016-02-07 14 35 54](https://cloud.githubusercontent.com/assets/15900022/12874821/e66eaea2-cda9-11e5-9163-c30a55b07e94.png)
![screenshot from 2016-02-07 14 46 11](https://cloud.githubusercontent.com/assets/15900022/12874822/ee5c69d8-cda9-11e5-87f1-8a2a373101aa.png)

Even changing variable height, does nothing to effect them. they still "fall out" of the decouplers.

![screenshot from 2016-02-07 14 40 37](https://cloud.githubusercontent.com/assets/15900022/12874830/12cbe618-cdaa-11e5-81fa-bfb76c61471f.png)
![screenshot from 2016-02-07 14 41 28](https://cloud.githubusercontent.com/assets/15900022/12874831/148daca2-cdaa-11e5-8b42-fdb9909349b0.png)

Like I said, this may be an issue on my end, as it usually is, but all I'm saying is that I'm not crazy. It could be a mod that I have; which I don't know what mod could actually interfere with KJR not working on this part, but anything is possible. 

I'm not asking for a fix, nor am I looking for any help in this matter. All I'm saying is that my results differ from yours. Easy fix, put a strut on it.

**Comment by shadowmage45** [comment]
I believe you, as I've seen others experience that problem, with screenshots as well with them sagging actually very badly, far worse than in your pics.

However, it does appear that KJR is working at least somewhat in your instances, as without it you would experience far more sag/flex -- in stock, the boosters will criss-cross themselves through the main tank when I do not strut them.

Probably also need to take in consideration how the stock joint mechanics work, and that the RBDC is no different than any other stock decouplers in that regard.  The top and bottom rings do not add joints -- the only attach point/joint between the booster and the decoupler is at the center point; and the only joint between the decoupler and the rocket is at the center point.  The only purpose of the rings is to tell you where the jettison-thrust-transforms are located at.

Even with KJR, extremely heavy loads will experience some amount of flex; it doesn't eliminate it completely.  The best test would be to compare against a similarly shaped and weighted load mounted on a stock decoupler (other mods' boosters, giant fuel tank); this would let you know if there is something effecting just the SSTU parts, or is a further reaching problem (KJR itself, base joint mechanics).

I wish I could fix the problem entirely, as I think it looks silly when it starts sagging/clipping through the rings, but I've not yet found a way to do so (besides re-creating parts of KJR :( ).

One thing that you might try (and I'll be playing around with it soon on this end), is to increase the node-size that is defined for the surface-attach-node in the parts.  Someone mentioned recently that it can have an influence on the joint-strength for surface-attached parts, though I have not yet tested it.

**Comment by lynwoodm** [comment]
Like I said, man. This isn't a big problem for me. I just put a couple of struts on it and it does fine and I'm okay with doing so. I did notice, however, when you decouple, the SRBs shoot back into the rings and clear the rocket like they are supposed to. That's all I really wanted them to do in the first place. You have bigger things to spend your time on than a silly decoupler issue. 

But, I will do the node size resizing to see if that fixes it and keep you posted.

**Comment by lynwoodm** [comment]
Confirmed on the fix, it solves this issue. Set your height on the main tank, set it a size bigger than what your SRB is. Place the SRB into the decoupler, size it down to fit. If you move it, resize the decoupler where you want it.

**Comment by Jimbodiah** [comment]
Just prior to detaching the boosters, they are not producing any thrust which means they will go back to a centered position.

node size resizing?

Regarding multiple nodes... Would it be possible to make two surface attach nodes on the Modular SRB with integrated seperatron? Or do multiple nodes on a single part not work in KSP?

**Comment by shadowmage45** [comment]
KSP only supports a single surface-attach node.  However, it can be repositioned/reoriented through plugin code if needed (I already do so for most modular parts).

**Comment by blowfishpro** [comment]
@SixDasher KSP vessels are constructed as a tree of parts, so there's only ever one node connecting two parts (docking ports can violate the tree structure but they're sort of a special case).

Moving the attach node when in the flight scene might work, though it would have to be done for both the decoupler and the booster (assuming that the boosters don't get built-in decouplers at some point).

Another option would be to add re-enforcing forces at the ends of the booster (essentially what struts do).  This has the potential to invite the Kraken if done wrong though.

**Comment by Jimbodiah** [comment]
How does Quantum struts work? Would that principle be an option to add to the top/bottom of the booster?

**Comment by blowfishpro** [comment]
@SixDasher Quantum struts works the same way as regular struts (creating a spring force between two parts), the only difference being that it does some raycasting to figure out what parts and when to create forces between (IIRC).  But that's way more than necessary for SSTU - if Shadowmage decides to go the reinforcing forces route, they can just be between the decoupler and whatever it's attached to (and the booster).  It should serve its purpose reasonably even if the "correct" part to attach to isn't the same.
