### ISSUE TITLE
Mounts on engines switching to different size

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#220]
Engine mounts tend to switch to different sizes when going from VAB to launch pad. Also fairings on the mounts do not always join to the tanks but stop a bit short of it. I've included a rar with screenshot and log files.

http://kerbal.nl/sstu/sstu_mount.rar

edit: This is from today's 2nd release.

**Comment by shadowmage45** [comment]
From the screenshots, the fairing problem is actually just the space where the mount -should- be.

However I cannot duplicate anything like that in testing.  Both engine-tank mounts and engine-mounts appear to maintain their custom sizing properly.

Your log indicates there are some issues with procedural parts (the mod) during loading, causing some null-reference exceptions; try removing that mod/those parts and see if the issue persists.  

I could not see anything else notable in the logs; no other null-references or exceptions that I could spot, and no SSTU-debug/error messages either.

I'll do more thorough testing when I have time / more information on how to duplicate the problem.

**Comment by Jimbodiah** [comment]
It's only on engine mounts, not on the tanks (as far as I can tell). I'll try without the other mods in the meantime.

**Comment by shadowmage45** [comment]
Noted.  Will do more testing on this tonight.

Is there any specific combination of parts / craft setup that seems to cause the problem to manifest?

Any specific order-of-operations that causes the problem to occur?

My general tests were
1.) Start with SC-B command pod.
2.) Add MFT-A default-sized tank
3.) Add an SSTU engine (used RS-25 for testing)
4.) Change engine mount type and/or size.
5.) Launch craft (total of three parts; pod, tank, engine)

Which did not cause the problem to occur.

**Comment by Jimbodiah** [comment]
All parts mods removed, only mechjeb etc left... Same issue with engine mounts and their fairing changing sizes and no longer joining after going to the launch pad.

http://kerbal.nl/sstu/sstu_mount2.rar

I've had this since the last update 3.28pre1/2, but not on all engines. In the example above it was the J2 single engine. It always seems to be engines on 2nd+ stages. I start with the command pod and work down, but place the items first and then start changing the diameters, mounts and lengths of tank.fairing.

**Comment by shadowmage45** [comment]
Is this still happening on your end?

Still have not been able to duplicate the problem on this end; even tried duplicating the craft as close as possible from your screenshots, but all mounts stayed at their proper sizes.  Nothing in the log is pointing to anything worrysome either.

If you have a SSTU/stock only craft where this is happening, would you mind uploading/posting it?

Another thing to try would be to completely remove the SSTU folders, and do a fresh re-install of the mod.  There could be some old/duplicate config files creating conflicts.  Wouldn't hurt to clear out the ModuleManager cache and PartDatabase.cfg files either.

**Comment by Jimbodiah** [comment]
Had the same issue just now. See attachment for logs and screenshot.

http://kerbal.nl/sstu/mount_resizing.rar

**Comment by shadowmage45** [comment]
Let me know if this is an issue with the newest releases using the new engine cluster plugin;  it is an entirely new codebase (with a much cleaner layout), so may or may not have the same problem.

**Comment by Jimbodiah** [comment]
will do
