### ISSUE TITLE
SC-GEN-PDC - node positions or geometry off when set to max height

### ISSUE THREAD

**Issue by blowfishpro** [shadowmage45/SSTULabs#223]
![screenshot0](https://cloud.githubusercontent.com/assets/10545461/13029642/acde9aac-d246-11e5-8ee2-e3f9cd3f785d.png)

This one seems to happen/not depending on the exact configuration.  It looks like the interstage node might be a little off too (tested by attaching stock parts to it)

![screenshot7](https://cloud.githubusercontent.com/assets/10545461/13029645/cef77820-d246-11e5-8ac3-362b6f2bf09a.png)

This one looks like the node is just a little off and it's only noticeable when the decoupler is streched.

**Comment by shadowmage45** [comment]
The first one is fixed in today's release (uploading now)....

Will look into the second, as I've noticed it myself.  Aye, only seems to happen when the decoupler is at its max height.
