### ISSUE TITLE
Pricing on MUS-ST and -CB

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#231]
The MUS-CB and -ST still have (very high) fixed pricing. Could these be made dependant upon size as per MFT-A and -B?

**Comment by shadowmage45** [comment]
Source code says that they -do- scale the cost with size (and resource type).

Will do some testing though, as there may be a bug in there somewhere.

**Comment by Jimbodiah** [comment]
There is a base price in the .cfg, maybe that is why it is so high: I notice the MFTs have 0 as a price in their config, the MUS has 20K as the base price.

**Comment by shadowmage45** [comment]
Ahh, indeed; that (combined with a small bug) is the cause of that.

I have updated the code to negate the config price when it is calculating cost (as the other modules do).  This should correctly set the base cost to zero, and all costs should then be those specified in the fuel type (and mount) configs.
