### ISSUE TITLE
High graphics load when placing engines, and partly tanks

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#246]
With the new version (was running pre4 before this) I get very choppy screens in the VAB when I add engines and to some extent modular tanks. Removing the engines return a smooth running screen again.

The log is spammed with 
[LOG 19:15:22.186] ---Docking  : 3b
[LOG 19:15:22.196] updated shielding status, new shielded part count: 3
[LOG 19:15:22.203] ---Docking  : 3b
[LOG 19:15:22.213] updated shielding status, new shielded part count: 3
[LOG 19:15:22.220] ---Docking  : 3b
[LOG 19:15:22.230] updated shielding status, new shielded part count: 3
[LOG 19:15:22.237] ---Docking  : 3b
[LOG 19:15:22.246] updated shielding status, new shielded part count: 3
[LOG 19:15:22.253] ---Docking  : 3b
[LOG 19:15:22.263] updated shielding status, new shielded part count: 3
[LOG 19:15:22.269] ---Docking  : 3b

Logs:  http://kerbal.nl/sstu/jitter.rar

**Comment by Jimbodiah** [comment]
This also causes the game to crash after a few minutes. Installing pre5 for the time-being.

**Comment by shadowmage45** [comment]
Hmm.. this sounds like its likely related to in-editor updates;  I'm probably triggering a never-ending cycle of updates (e.g. editor update hits the engine part, which triggers another update, which triggers yet another update when it reaches the engine; on and on...).  And/or I've not cached an editor value properly which is causing it to re-update with every frame.

Is it just the engines causing this problem or are there other parts that trigger it as well?

**Comment by Jimbodiah** [comment]
I get the feeling engines are the main issue, but also think the tanks add to the effect as well. No issues with CMs/SMs.

**Comment by Jimbodiah** [comment]
So far so good, will test further tonight.
