### ISSUE TITLE
No Collider on the bottom of the E fuselage 

### ISSUE THREAD

**Issue by lynwoodm** [shadowmage45/SSTULabs#247]
Cannot mount a decoupler on the bottom of the E fuselage. This was performed on my testing game with dependencies only. 

![screenshot from 2016-03-01 02 30 11](https://cloud.githubusercontent.com/assets/15900022/13420610/c2479f62-df55-11e5-8937-945caaf27be8.png)

Not sure if a log will do any good here, but if you need it, I'll provide it.. ever so generously.

**Comment by shadowmage45** [comment]
Thanks, and noted.

Already fixed in dev-repo; apparently I forgot to include the colliders while re-exporting the parts.  Sadly I noticed about 5 minutes after I posted the update last night.  

Have also fixed the offset gear doors problem :)

Both should be available with an update this evening.

**Comment by lynwoodm** [comment]
Roger that.
