### ISSUE TITLE
R107/108 wobbly

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#248]
I can not for the life of me get anything to fly in a straight line with these engines. They wobble all over the place like gimballing is doing the opposite of what is expected. This is not just from the last patch though, been like that from the start with the new engines, I just haven't used them again since today :)  I saw an issue come by a while ago but can not find it right now.

**Comment by shadowmage45** [comment]
Whatever is causing this I highly doubt there is anything that I can do about it (without killing the gimbal setup for those engines entirely).

Really won't know until 1.1 is released and I can use the stock gimbal with axis-limits in it.  Still don't think it'll make a difference... but we'll see.

Marking as 'wontfix' for now (as there is nothing I can do at the moment), but will leave open and re-investigate during 1.1 updating.

Edit:
Also, I have had no problem launching rockets _manually_ using those engines-- it more relies on -NOT- using MJ (MJ can't fly it worth a damn) than anything else.  Turn on MJ and it goes nuts, do it manually (and gently!), and you should have no problems.

**Comment by Jimbodiah** [comment]
Must.Drink.More.Vodka.

**Comment by shadowmage45** [comment]
Stock is fixing the gimbal modules in 1.1 to be able to limit axis -- so I should no longer need the constraint-based hack in order to get the gimbals working properly (which I -think- is what MJ/etc is struggling with).

So, will revisit this one when 1.1 is released and see if the stability stuff is fixed or still present.

**Comment by Jimbodiah** [comment]
Thanks!!!  I do indeed use MJ. Mechjeb is life!!!  ;)  Don't have the patience to do the 20.000th launch by hand again.
