### ISSUE TITLE
Shuttle thermals

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#254]
Nevermind the first remark (deleted), that was what was in the cargo bay, duh).

The fuselage will not survive re-entry (150km orbit with de-orbit burn, 2300m/s re-entry). It overheats and explodes unless you disable heat damage.

**Comment by shadowmage45** [comment]
No thermal balancing has been done yet.

**Comment by shadowmage45** [comment]
I intend to add a custom heat-shield module that will simulate the thermal properties of heat-soak tiles such as those used on the shuttle.  The current implementation is a stock-ish hack to enable -very- gentle re-entries.

Will also need to do some adjustment/checking on cargo-bay occlusion and shielding.

**Comment by Jimbodiah** [comment]
Ah, that would explain it. Sorry :)
