### ISSUE TITLE
Left E-Series Wing needs re-sizing.

### ISSUE THREAD

**Issue by lynwoodm** [shadowmage45/SSTULabs#257]
Let's just say, this thing is HUGE. 
![screenshot from 2016-03-10 22 18 35](https://cloud.githubusercontent.com/assets/15900022/13692283/297fac6e-e70e-11e5-9c15-a76a72063d3d.png)

Will see if this is on my end, or a legit problem.

**Comment by lynwoodm** [comment]
Seems like you changed the re-scale value to 18 while the right one is a re-scale value of 1. 

`PART
{
module = Part
name = SSTU-SC-E-WL
author = Shadowmage

TechRequired = heavyAerodynamics
entryCost = 8000
cost = 4000
category = Aero
subcategory = 0
title = SSTU - SC-E-WL - Wing - Left
manufacturer = SSTU
description = Ship Core - Series E - Wing - Left.

MODEL
{
    model = SSTU/Assets/SC-E-WL
}
MODEL
{
    model = SSTU/Assets/SC-GEN-LG-A
    rotation = -90, 6, 0
    position = -0.49881, -2.71157, 0.42753
}
**rescaleFactor = 18**`

**Comment by lynwoodm** [comment]
Changed the value and now restarting. Will advise.

**Comment by lynwoodm** [comment]
Success. 
![screenshot from 2016-03-10 22 41 02](https://cloud.githubusercontent.com/assets/15900022/13692624/455ea464-e711-11e5-9e45-cb967b98d375.png)

Would you want to re-do the download? Or just put an APB in the forums to make this simple change?

**Comment by shadowmage45** [comment]
Noted and fixed, will likely re-upload the package here shortly.

**Comment by lynwoodm** [comment]
before you do that, check on your radial decoupler. I made another ticket on the subject. added photos to show what was going on.
