### ISSUE TITLE
Radial Decoupler radius doesn't match the radius of tanks/srbs at stated diameter. 

### ISSUE THREAD

**Issue by lynwoodm** [shadowmage45/SSTULabs#258]
While sizing the radial decoupler to a tank. The sizes do not match said radius on the decoupler and appears to increase in difference when part gets larger or smaller. Just doesn't match. 

![screenshot from 2016-03-10 23 14 51](https://cloud.githubusercontent.com/assets/15900022/13693183/6e93a776-e716-11e5-9293-6113bed17382.png)
![screenshot from 2016-03-10 23 15 09](https://cloud.githubusercontent.com/assets/15900022/13693185/6e984858-e716-11e5-89e8-9b5e59bc5044.png)
![screenshot from 2016-03-10 23 18 06](https://cloud.githubusercontent.com/assets/15900022/13693184/6e977a54-e716-11e5-93af-31b3fc41af58.png)
![screenshot from 2016-03-10 23 18 13](https://cloud.githubusercontent.com/assets/15900022/13693186/6e9d3886-e716-11e5-8d84-b5759584b874.png)

I tried with both tanks and srb and I get the same results. This is off my test build with only dependencies, cryo engine mod and some of my part modifications. I will supply logs if you need them.

**Comment by lynwoodm** [comment]
Supplied logs anyways, just in case it was a problem on my end causing this. 
[KSPlog.txt](https://github.com/shadowmage45/SSTULabs/files/168452/KSPlog.txt)

**Comment by shadowmage45** [comment]
https://github.com/shadowmage45/SSTULabs/commit/bcf2f088d6c1acd0be86a078217c4c7cb3d81e56#commitcomment-16635981

change the modelDiameter in the config from 2.25 to 2.5

Fixed in dev, will be available with the next regular release

**Comment by lynwoodm** [comment]
_slaps his forehead_ I totally forgot you can adjust the diameter with the slider bar to fit. Talk about a "wow, I'm stupid" moment.

**Comment by Jimbodiah** [comment]
The blocks that attach to the main core stay big despite scaling the rings
