### ISSUE TITLE
New Part: SC-ENG-RD-0110

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#261]
# stats/info

Low-tech (early) Kerolox upper-stage engine.  ~1.45m overall diameter (intended for 1.875m rockets) (2.24m \* 0.64).  0.49m individual bell diameter.

4-chambered engine, with single common combined axial turbopump.

0.67 tons
122kn vThrust  
105kn sThrust
326 vISP
280 sISP

**Comment by blowfishpro** [comment]
302s seems rather low to me ... is that with the Isp scaling?  Those numbers seem much more in line with stock lower stages than upper stages.

**Comment by shadowmage45** [comment]
Yes, that is with the stock scaling (which nothing is using at the moment due to the LH2 patch);  IIRC the actual ISP is ~280-326, so its not the most efficient engine to begin with.

**Comment by blowfishpro** [comment]
Wikipedia and Astronautix both give 326, yeah.  Not incredibly efficient, but reasonable for the era and cycle.
