### ISSUE TITLE
Bug - SC-E RCS stops responding when control transform changed (control from here...).

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#262]
This is due to the RCS modules being disable for input from certain axis, to remove much of the stock quirkiness regarding them.

Unfortunately, when you change control transforms, it changes the -input- scheme of the RCS (rather than the control scheme), and thus what was previously a 'yaw' command now looks like a 'pitch' command, and the thrusters will not respond correctly (because the yaw thrusters are disabled from pitch input).

Really not sure that I'll be able to solve this one adequately -- seems to me that the stock module needs to reference the input vector vs the parts default transform and not the currently selected control transform.

**Comment by shadowmage45** [comment]
http://forum.kerbalspaceprogram.com/index.php?/topic/134407-axis-limited-rcs-not-responding-after-control-transform-change/#comment-2461765

Going to see if the experts have any input on the subject.

**Comment by shadowmage45** [comment]
As-per NathanKell; there is nothing that can be done to fix this issue as-is.

Likely I'll have to remove the axis-limiting from the RCS modules, which will result in some less-than-optimal RCS balance and fuel use.

No other way around it though.....

**Comment by Jimbodiah** [comment]
As RCS is only use for docking, could you not fix the rcs transforms to only work in regards to the docking port position?

**Comment by shadowmage45** [comment]
I use RCS for rotation/translation during regular flight as well (I generally disable reaction wheels as I feel them to be a bit cheaty).  Translation mostly just for docking...but I need the rotation input to work as well (which is partially broken currently when using the docking-port control from here option)

So no... setting them up purely for docking would not work for me.
