### ISSUE TITLE
SC-A-SM - Mass

### ISSUE THREAD

**Issue by blowfishpro** [shadowmage45/SSTULabs#263]
Almost exact same delta-v, compare the masses of these two setups:

![screenshot18](https://cloud.githubusercontent.com/assets/10545461/13799630/8cd65c1c-eade-11e5-823e-63be023dfb0d.png)
![screenshot17](https://cloud.githubusercontent.com/assets/10545461/13799629/8cd5d77e-eade-11e5-94cd-047e2fc4f86f.png)

The SM is about 4 tons more than the MUS with the same delta-v.  Granted, not everything is the same between them, but does the addition of the reaction wheel and antenna really justify that much mass increase?

**Comment by shadowmage45** [comment]
I'm going to have to do some checking, as that seems...impossible.  The dry mass on the SM is only 2.7 tons, so there is no way that it should have that much more mass.

I double checked the stats on the SM, and they are correct -- 2.7t dry mass, 8.1t propellant mass (~45% of real values), so the error in this case is more than likely in the MUS part.

```
Mass: 54,060 lb (24,520 kg)  (24.5-18.4 = 6.1 * 0.45 = 2.745)
Structure mass: 4,200 lb (1,900 kg)
Electrical equipment mass: 2,600 lb (1,200 kg)
Service Propulsion (SPS) engine mass: 6,600 lb (3,000 kg)
SPS engine propellants: 40,590 lb (18,410 kg) (*0.45 = 8.2t)
```

I'll do some investigation on those in the next few days

**Comment by shadowmage45** [comment]
Part of this came down to the SM still using an old/unpatched ISP of 300 vs 319 for the stand-alone engine.

(https://en.wikipedia.org/wiki/Apollo_Command/Service_Module)
    SPS ISP: 314 s (3,100 N·s/kg)
    Spacecraft delta v: 9,200 ft/s (2,800 m/s)

Loading up KSP now for some more detailed testing, as that alone should not explain such a large discrepancy.

**Comment by shadowmage45** [comment]
Even after the ISP change/fix there is still a bit of discrepancy; the MUS tanks have lower dry mass than the SM.  And thus the rocket equation kicks in.. in reverse; less payload equals less fuel required, less dry mass from those fuel tanks, etc, etc...

If you set the MUS to contain the same amount of fuel as the SM (2025 mp), there is a total of ~1.1t in dry mass difference difference between the two setups; which I would consider acceptable considering what the SM offers (balanced rcs, docking light, transmitter, life-support supplies (I think..), and (eventually) a science bay / experiment).

Comparison shots, after the ISP change:
![screenshot26](https://cloud.githubusercontent.com/assets/1503399/13800568/163f2004-eaf0-11e5-97f6-b1cf40f9174a.png)
![screenshot27](https://cloud.githubusercontent.com/assets/1503399/13800569/16400c94-eaf0-11e5-89c9-bd6a0597c7fd.png)
![screenshot28](https://cloud.githubusercontent.com/assets/1503399/13800567/163da954-eaf0-11e5-8bb5-6c742e06c721.png)
![screenshot29](https://cloud.githubusercontent.com/assets/1503399/13800570/165bb1d8-eaf0-11e5-8632-cb203896c973.png)

So... I'm going to consider this fixed for the time being, but leave this open to discussion for a bit.  Will likely be doing a rebalancing of the pods / ship-core series parts in the next few weeks/month to make them more applicable to the stock system (and less OP compared to stock parts).

**Comment by blowfishpro** [comment]
Makes sense to me.  Forgot that to verify that the engines were actually the same.
