### ISSUE TITLE
SC-E-FS Cargo Bay Shielding

### ISSUE THREAD

**Issue by Theysen** [shadowmage45/SSTULabs#264]
I reported this issue some time ago but didn't have the time to keep on testing. 

Parts in the front of the Cargo Bay (attached to tubes, structural bars or below / on the sides of the bay are not considered shielded. Seems like the area is excluded somehow from the detection.
Just seems to appear in the front of the bay, rest works flawlessly. 

[http://imgur.com/a/hBESb](url)

**Comment by shadowmage45** [comment]
Thanks for the report; will investigate for the next scheduled release (Saturday).

**Comment by shadowmage45** [comment]
Had a guessed at / incorrect value for the top position of the shield, resulting in it being almost 2m short.  It should now properly shield everything up to the cockpit wall (and a tiny bit within as well).

Will be available with the next update.
