### ISSUE TITLE
SC-E-FS docking port

### ISSUE THREAD

**Issue by x3l1a** [shadowmage45/SSTULabs#266]
Something is wrong here...during the docking maneuvers dont' work, I use MechJeb. The shutte is cool but with rcs is not easy, is unresponsive..

**Comment by shadowmage45** [comment]
duplicate of #262

**Comment by shadowmage45** [comment]
In short -- you need to dock manually, using the default part control transform -- stock has a bug where when you swap control transforms it does not update the input scheme for the RCS, and they stop responding to inputs that they -should- respond to.
