### ISSUE TITLE
SSTU - E - FS Fuselage No Collider

### ISSUE THREAD

**Issue by x3l1a** [shadowmage45/SSTULabs#267]
Hi, is Impossible insert inside the shuttle parts or components to be transported [http://oi68.tinypic.com/9qws8x.jpg](url)

**Comment by shadowmage45** [comment]
Nope, colliders are there and working just as intended.

You need to hold alt while placing the part to force it to snap onto a node.

Also, the MFT tanks need to be dropped and picked up again before they will surface attach properly (stock bug regarding changing models/colliders, nothing I can do about it).

![screenshot30](https://cloud.githubusercontent.com/assets/1503399/13830729/249c1ffe-eb94-11e5-8aec-a9307e63fd21.png)

**Comment by x3l1a** [comment]
ok thanks :) :+1:
