### ISSUE TITLE
MFT-A/B tri-mount

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#270]
When you select the three engine mount on the Modular tanks, the centerline is offset to one side for some reason, causing thrust to not come from the center.

![mft_mount_01](https://cloud.githubusercontent.com/assets/16107012/13900270/a6e4e426-ee02-11e5-9717-e21bf43871a5.jpg)

**Comment by Jimbodiah** [comment]
It looks like you copied the 4-way mount and chopped off the 4th node?

**Comment by shadowmage45** [comment]
I'm not encountering any problem with the node locations during testing.  

RCSBuildAid is telling me there is zero torque:
![screenshot0](https://cloud.githubusercontent.com/assets/1503399/13906337/5231d5c8-ee99-11e5-9790-0c1c44d70cc9.png)

Nor am I encountering any torque in flight:
![screenshot1](https://cloud.githubusercontent.com/assets/1503399/13906352/c69bd472-ee99-11e5-9987-05637778a84b.png)

**Comment by Jimbodiah** [comment]
Thry the different sizes. The large version is the only one that works correctly, the rest all get offset

**Comment by shadowmage45** [comment]
Noted, will try the other sizes. 

In the future, it is handy to include that information in the initial report; less wasted time on testing things that don't need to be tested = happier developer = more real work getting done.

**Comment by SixDasher** [comment]
If you'd click more than once you'd have caught it yourself a while back, meaning no useless bug reports from me.

**Comment by shadowmage45** [comment]
I have tested every tri-coupler adapter and could not see any off-center thrust problems.

If you have a stock+SSTU craft that replicates the problem, please feel free to post/upload/link it here and I will re-open and investigate further.
