### ISSUE TITLE
SC-ENG-RS-68 - RealPlume configs aren't working

### ISSUE THREAD

**Issue by blowfishpro** [shadowmage45/SSTULabs#283]
Managed to get the turbopump exhaust effects working by setting `transformName = RS-68-RollExhaust` for the second plume, but I can't figure out why the first isn't working, particularly since the `Hydrolox-Lower` plume seems to work fine on the RS-25.

**Comment by blowfishpro** [comment]
Observed the same thing with the RD-107A - can get the vernier effects working but not the mains.  Maybe a SmokeScreen issue?

**Comment by blowfishpro** [comment]
Oh duh, because there's only one engine module now and only one of the effects will actually get used.

Looks like RealPlume is currently incompatible with this sort of setup.  But RO will encounter this issue too, so I think it's only a matter of time before someone comes up with a permanent solution.

**Comment by blowfishpro** [comment]
Relevant KSP-RO/RealPlume#20

**Comment by blowfishpro** [comment]
Found a sort of workaround, one of the plumes just has to be on a different effect type on the engine

```
@PART[SSTU-SC-ENG-RD-107A]:NEEDS[RealPlume&!RealismOverhaul]:BEFORE[RealPlume]
{
    PLUME
    {
        name = Kerolox-Lower
        transformName = RD-107A-MainFXTransform
        localRotation = 0,0,0
        localPosition = 0,0,0.5
        fixedScale = 0.25
        energy = 0.5
        speed = 1
    }
    PLUME
    {
        name = Kerolox-Upper
        transformName = RD-107A-VernierFXTransform
        localRotation = 0,0,0
        localPosition = 0,0,0.25
        fixedScale = 0.1
        energy = 0.4
        speed = 1
    }
    @MODULE[ModuleEngines*]
    {
        %powerEffectName = Kerolox-Lower
        %runningEffectName = Kerolox-Upper
    }
}
```

Power and running aren't exactly the same - power is based on thrust/maxThrust, whereas running is based on throttle, but as a temporary fix it might work.

**Comment by shadowmage45** [comment]
Thanks for investigating :)

Yah, I hadn't even touched the RealPlumes stuff as I couldn't find a SmokeScreen that was compiled for 1.1; had noticed Sarbian had done an update, but there was no built .dll and I didn't feel like setting up the project to compile it myself.

As soon as there is a 1.1 release available I'll start playing around and fixing up the plumes;  I intend to fully support RealPlumes as I'll be using it in my games :)  (stock plumes are.... lacking... in a few features and general selection)

**Comment by blowfishpro** [comment]
Sarbian has CI set up for a bunch of mods, so even if there's no forum post you can check [here](https://ksp.sarbian.com/jenkins/) for updates.  Jenkins compiles the DLLs, so no need to set to compile on your own.

**Comment by PhineasFreak** [comment]
RO already has this problem, at least for one engine (and with more to come): [AIES LR-91](https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RealPlume_Configs/AIES/liquidEngineorbit2.cfg)

It drove me crazy while trying to find why it didn't work...

**Comment by shadowmage45** [comment]
I think the temporary work-around of using the 'runningEffect' for the verniers will be fine;  most people would not notice the slight difference in throttle-derived-output vs power-percentage-derived-ouput.

Will look into setting up RealPlumes sometime this week and get all the vernier-equipped engines fixed up.

**Comment by shadowmage45** [comment]
Have updated all vernier-equipped engines to use runningFX and powerFX for their RealPlumes effects.  While not ideal I consider it an acceptable solution given the limitations imposed by how RealPlume sets things up.

Will be available with the update later today/tonight.
