### ISSUE TITLE
SC-A-SM: Switching side panel texture resets side panels to transparent

### ISSUE THREAD

**Issue by blowfishpro** [shadowmage45/SSTULabs#288]
However, it does not update the toggle.  Opaque can be achieved again by pressing the toggle twice.  Only happens once - once it is fixed after observing the issue, it will not happen again for the same part.

**Comment by shadowmage45** [comment]
Fun...
Likely related to unity's retarded material vs. sharedMaterial setup.
Going to take a bit to get this one tracked down and fixed due to that.

**Comment by blowfishpro** [comment]
Take your time of course.  This is a minor annoyance anyway with an easy workaround, so I'd say pretty much everything is higher priority

**Comment by shadowmage45** [comment]
One liner apparently; I wasn't properly resetting opacity status on texture change.

Fixed in dev; available shortly.
