### ISSUE TITLE
SC-GEN-RBDC Radial Booster Decoupler - NRE Spam and FlightScene Lockup

### ISSUE THREAD

**Issue by Theysen** [shadowmage45/SSTULabs#289]
By attaching a Radial Booster Decoupler onto any part the FlightScene renders a blue screen plus a bugged NavBall and input is locked, forced to exit via desktop. 

Logs:
https://www.dropbox.com/sh/tufx9sa8zzhahab/AACitQ7NLA6b0SY7F9ZWtVg0a?dl=0

**Comment by shadowmage45** [comment]
Thanks for the logs;

This appears to be related to KSPs changes to IPartModuleMassModifier, and/or their failure to make sure the part is initialized before querying the part-modules for their mass (e.g. GetModuleMass is called before OnStart; hence the module has no data to derive its mass from).

Will see what I can do about getting it cleaned up for the next release.

**Comment by shadowmage45** [comment]
Fixed in dev; if part is uninitialized return some dummy default values.

Will be available with an update later this evening (after I get home from work).
