### ISSUE TITLE
SC-GEN-RBDC Radial Booster Decoupler - wobble around anchor point

### ISSUE THREAD

**Issue by Theysen** [shadowmage45/SSTULabs#292]
The part attached to the decoupler rotates around the anchor point of the RBDC and whole part wobbles around. RBDC connection point visibly clips ín and out the root part. Effect increases with size and spacing between the decoupler rings. Stock install, no KJR. 

Logs: https://www.dropbox.com/sh/tufx9sa8zzhahab/AACitQ7NLA6b0SY7F9ZWtVg0a?dl=0

**Comment by shadowmage45** [comment]
Sounds like stock noodle-rocket-joints to me.  There is little/nothing I can do about stock joint mechanics.  If not using KJR you -will- need to strut anything attached via the RBDC (just as you need to with the stock radial decouplers).

KJR is -highly- recommended for SSTU rockets.

To verify if this is a problem with that particular part, can you attach screenshots showing a comparison of the same payload attached using the stock radial decouplers vs. the RBDC?

**Comment by Theysen** [comment]
Here's a short clip: https://youtu.be/6BszhJP_Ne0

I certainly remember playing the first 1.1 dev release (although they were size 1.25m due to the bug I reported) that those didn't wobble into the center tank at the anchor point (without struts, no KJR). 

If this is truly stock behaviour now I'd maybe suggest setting KJR as dependancy though (they are stiff as a brick with KJR of course).

**Comment by shadowmage45** [comment]
Video currently flagged as private :(

Will take a look at this tonight though and compare vs. the stock decouplers.  There have been some oddities in the past with those parts, and I have not tried them personally in 1.1 yet (my play-time is non-existent recently);  so there may well be some conflicts/etc going on.

KJR is already on the 'highly recommended list' (or at least I thought it was?).  If it is not, I'll update the forum thread to indicate it as such.

**Comment by Theysen** [comment]
My bad, I forgot that youtube handles Private different than other sites. Should work now as 'not listed'.
I read the forum entry about that, you're really missing out on your great stuff.

**Comment by shadowmage45** [comment]
I would say this is a stock joint-strength issue.

Screenshot comparing RBDC (left) with a stock radial decoupler (right).  They both are about equally sloppy.

![screenshot1](https://cloud.githubusercontent.com/assets/1503399/14726599/9724d972-07e0-11e6-996b-cad55289cece.png)

With that said, the RBDC also seems to move its own geometry around whereas the stock decoupler does not.  Will do a bit of investigation on that... but might not be anything that I can do about it (other than recommend KJR or 'moar struts').

**Comment by shadowmage45** [comment]
Okay... so I have removed the custom node-size specification from the RBDC and it now acts equivalently to the stock radial decouplers.  Previously I had a node size of '9' specified; have now removed the specification to match up with how the stock decoupler node is defined.

Nothing more that I can do about joint strength without delving into replicating parts of KJR.

Never hurts to point these things out though when you spot them; about half the time they really are bugs :)

Leaving this issue open to remind me to add KJR as 'Highly Recommended / Almost a dependency' to the forum OP and wiki.

**Comment by Theysen** [comment]
Alright, thanks for investigating. KJR is mandatory anyway for big scale crafts as you stated.
