### ISSUE TITLE
RS-68 Clusters not working properly

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#299]
Multiple reports on the forums of the RS-68 not wanting to go beyond cluster layout of 3 engines

No clue yet on this one... nobody is providing logs or anything beyond just complaining....

**Comment by lynwoodm** [comment]
I checked the clustering for this engine. What's happening is that the description for the cluster on the slider doesn't go past Triple Angled, but the engines still progress in cluster.
![20160429122744_1](https://cloud.githubusercontent.com/assets/15900022/14922484/e36da2d4-0e05-11e6-956c-8ca9825f85cf.jpg)

**Comment by shadowmage45** [comment]
Hmm... strange... likely some incorrect layout definitions in the part that are causing it to null-ref somewhere in the GUI update parts (where the exceptions get eaten and go unreported...).

Will investigate this for the next update (hopefully tomorrow).

**Comment by shadowmage45** [comment]
Turned out to be an index-out-of-range error due to a typo in the debug logging statement for the split-thrust-transform config-node mangling code.

Fixed in dev, will be available with the next update.

Should also fix up any similar issues with the other the RD-XXX engines
