### ISSUE TITLE
Zero Boil-Off Hydrolox tanks experience boil off at high levels of time acceleration

### ISSUE THREAD

**Issue by bwy-dev** [shadowmage45/SSTULabs#306]
at time acceleration beyond 10,000x ZBO tanks still boil off hydrogen. I'm not sure what else to add, steps for repetition are to put a ZBO tank out on the launch pad and time accelerate to 100,000x.

**Comment by bwy-dev** [comment]
![screenshot17](https://cloud.githubusercontent.com/assets/11640444/15073053/2b0cb89e-138f-11e6-832b-8b681be3124c.png)

The boil off is low enough that I'd expect it to be a floating-point error

**Comment by shadowmage45** [comment]
Hmm... seems like it might just be that (float-point error).  Though I would think that X \* 0 would always == 0, but perhaps the floating point implementation isn't as smart as that :)

Even more strange is that there is boiloff, but no cooling cost.  Might actually be a bug in the implementation in regards to timewarp (it is not specially handled at all, instead relying on planetarium universal time and calculating a delta between updates).

Will look into this shortly, should have it fixed up for the next release.

**Comment by shadowmage45** [comment]
Having looked into this; the problem is not that the ZBO stops working, it is that you run out of EC and/or the EC is not updated properly; it could even be that at very large time warp that your vessel does not hold enough EC for a single update.

Going to do a bit more investigation using some RTGs for power generation to see if I can keep the power generation in line with the ec costs.

**Comment by shadowmage45** [comment]
Indeed, with sufficient power generation and power capacity it all works as expected and ZBO tanks do stop boiloff even at 100,000x timewarp

![screenshot3](https://cloud.githubusercontent.com/assets/1503399/15093347/84914ae8-1442-11e6-969f-c4b27a7af43b.png)

Closing as a non-issue; feel free to re-open if you can provide further information.
