### ISSUE TITLE
Incompatibility with TCA and some Service Modules/integrated parts.

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#341]
## Data from forum:

Got rid of Space Y and Kerbalism. Same issue with Throttle Controlled Avionics mod installed. SM engine auto starts on pad if TCA is installed. Works fine if its not.

Here is the logs and craft file from the latest run:

https://dl.dropboxusercontent.com/u/6187623/SSTU Issues/SSTU CMSM.craft

https://dl.dropboxusercontent.com/u/6187623/SSTU Issues/output_log.txt

https://dl.dropboxusercontent.com/u/6187623/SSTU Issues/KSP.log

Mod List:

http://imgur.com/TXriLIc

The spontaneous SM decouple does not seem to happen even with TCA installed. Ill see if I can narrow that one down to another mod.

**Comment by shadowmage45** [comment]
## Additional information from forum:

 The culprit for all the log spam appears to be a mod called Atmosphere Autopilot. If I add it to the above mods list SSTUTools starts throwing hundreds of exceptions per second on my ship about update heat. Still looking for what causes the automatic SM decouple.

SSTUTools.SSTUAnimateEngineHeat.updateHeat

**Comment by shadowmage45** [comment]
Potential solution to the Atmosphere Autopilot problems --

Rather than use a raw index to find the engine module, instead use the index of the module in the sub-list of engine modules.  This will ignore all other modules, and -could- clean up issues caused by other mods' plugin code re-arranging modules.

Thus if a part only has one engine module, the index will always be zero (0).  If a part has two engine modules, the index would be 0 or 1 depending on if it was the first or second engine.

**Comment by robrown1** [comment]
Finally tracked down what is making the SM auto decouple. Its a mod called Routine Mission Manager. http://spacedock.info/mod/362/Routine Mission Manager

If you have the CM set to SM DC Staging Disabled it will auto decouple on return from scene change. If you Enable it won't. Easiest way to repro is is create a stack of CM and SM, go to pad, F5 quicksave, F9 Reload. Bam, decouples every time.

Likely a separate issue from SM engine auto start.
