### ISSUE TITLE
Cannot (quick)save vessel

### ISSUE THREAD

**Issue by macluky** [shadowmage45/SSTULabs#348]
[EXC 23:47:54.936] NullReferenceException: Object reference not set to an instance of an object
    SSTUTools.SSTUVolumeContainer.updatePersistentData ()
    SSTUTools.SSTUVolumeContainer.OnSave (.ConfigNode node)
    PartModule.Save (.ConfigNode node)
    ProtoPartModuleSnapshot..ctor (.PartModule module)
    ProtoPartSnapshot..ctor (.Part PartRef, .ProtoVessel protoVessel)
    ProtoVessel..ctor (.Vessel VesselRef)
    Vessel.BackupVessel ()
    FlightState..ctor ()
    Game.Updated ()
    QuickSaveLoad.doSave (System.String filename)
    QuickSaveLoad.OnSaveAsSave ()
    QuickSaveLoad.<SpawnSaveAsDialog>m__273 ()
    DialogGUIButton.OptionSelected ()
    DialogGUIButton.<Create>m__809 ()
    UnityEngine.Events.InvokableCall.Invoke (System.Object[] args)
    UnityEngine.Events.InvokableCallList.Invoke (System.Object[] parameters)
    UnityEngine.Events.UnityEventBase.Invoke (System.Object[] parameters)
    UnityEngine.Events.UnityEvent.Invoke ()
    UnityEngine.UI.Button.Press ()
    UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData)
    UnityEngine.EventSystems.ExecuteEvents.Execute (IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData)
    UnityEngine.EventSystems.ExecuteEvents.Execute[IPointerClickHandler](UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.EventFunction`1 functor)
    UnityEngine.EventSystems.EventSystem:Update()

I believe the container does not exist:

> private void updatePersistentData()
>         {
>             if (containers != null)
>             {
>                 persistentData = "";
>                 int len = **containers.**Length;
>                 for (int i = 0; i < len; i++)
>                 {
>                     if (i > 0) { persistentData = persistentData + ":"; }
>                     persistentData = persistentData + containers[i].getPersistentData();
>                 }
>             }
>         }

**Comment by macluky** [comment]
Running 1.1.3 with 0.4.31.108 for KSP 1.1.2 (05-07-16)

**Comment by macluky** [comment]
can confirm that downgrading to sstu 108 fixed the issue

**Comment by shadowmage45** [comment]
That version is... very... out of date.

Please try using the latest versions (0.5.32.121) and let me know if the problem persists.

**Comment by macluky** [comment]
Ah, my bad. I believe the readme file from which I extracted the version number is out of date. It was 0.5.32.121 since I actually installed it to play with the new station parts. (which are awesome btw.)

I meant downgrading to 108 fixed it. Sorry for messing that up. I ran KSP 1.1.2 for a long time hence the older SSTU, but I just had to try the new parts.

**Comment by shadowmage45** [comment]
Ahh... noted.

I'll see if I can duplicate the issue on a 1.1.3 install with the latest dev code.  

Though, from looking at the code, that error should be impossible as there is nothing that could be null in that code block that isn't already checked.

**Comment by shadowmage45** [comment]
I have not been able to duplicate this problem with the latest versions.

My next thought is that there is an earlier exception that caused the module to not initialize properly.

Would you be able to upload a full KSP.log file for a time when this problem is occurring?

**Comment by macluky** [comment]
Not at the moment, but Val and her team are almost done on Gilly, once they are back at Kerbin, I'll update back to latest version since I can live with the loss of an interplanetary vessel, but can't sacrifice the crew for a ticket :-)

Btw I presume you are right, RemoteTech was buggy at the time. Let's postpone for now, I'll retest with the latest version during the weekend and update the ticket.

Thanks for your patience!

**Comment by macluky** [comment]
Hi,
Sorry that I didn't report back, have not had the issue again since updating (which means nothing in the land of software ;-) I think your suspicion  was correct. Thanks for the search!
