### ISSUE TITLE
No installation instructions

### ISSUE THREAD

**Issue by violentrat** [shadowmage45/SSTULabs#350]
Not sure where I am missing the info but not seeing the proper installation instructions for any of the files. I saw the ship files were removed so not sure if I am even supposed to be trying to use SSTULabs at the moment.  If someone has a second I appreciate it.

**Comment by shadowmage45** [comment]
This works just like very other mod.  
Add the GameData/SSTU folder from the .zip to your KSP/GameData folder.  It should end up with KSP/GameData/SSTU/<all the sstu stuff>.
