### ISSUE TITLE
Texture bug?

### ISSUE THREAD

**Issue by ddaniel1011** [shadowmage45/SSTULabs#352]
this white texture and mod or even and a bug in my game?
![sem titulo](https://cloud.githubusercontent.com/assets/22151249/18438966/d9491bfa-78d9-11e6-85e4-08af590d0edc.png)

**Comment by shadowmage45** [comment]
Those parts are not finished yet and do not have textures.

Note how it says

```
UNFINISHED PROTOTYPE PART - UNTEXTURED - MODEL NOT FINISHED - NOT FEATURE COMPLETE - 
```

In the part config?

Yeah, that is there for a reason.
