### ISSUE TITLE
IVA's

### ISSUE THREAD

**Issue by Modsojoy** [shadowmage45/SSTULabs#354]
I could make an IVA For the SC-B-CM(Orion Replica) with ASET Props, If there is not one already.(seen on the forum thread you are looking for IVA Creators)

**Comment by shadowmage45** [comment]
Thanks for the interest.  You are more than welcome to create one if you would like; would be much appreciated by me and at least a few other users.

However, I would like to make sure you know what you are getting into.

For those parts there is currently zero work towards an IVA.  No models, meshes, nothing.  You would be starting from scratch on the IVA, creating the interior mesh, making the textures for the mesh, exporting it through Unity, setting up the IVA config, and finally doing all the props work.

If none of that sounds like a problem to you, then welcome aboard :)  If you are interested, respond here or shoot me a PM on the forums (preferably on the forums), and I'll work on getting you the necessary modeling assets for the task (the external meshes / blend files).

**Comment by Modsojoy** [comment]
Ayyy, I have made two IVA’s before so this is no problem, Also I no longer have a forum account or else I would have PM’d you to begin with. The only issue is texturing, How good do they have to be?

**Comment by Modsojoy** [comment]
So, Whenever you get the chance if you could link - or better yet email- the 3D Bits i could get started(Currently tied up with another Project(BDB's LEM) So more like started in a few days)

**Comment by shadowmage45** [comment]
Texturing -- doesn't need to be anything special.  As long as it is good enough to give you an idea of what is going on, should be good enough for me.

Have sent the .blend file to the email address listed on Github, if you do not receive it please let me know and I'll find another delivery method.

**Comment by Modsojoy** [comment]
Ayy i shot ya an Email, I wanted the .blends for all your Manned Capsules/Pods that dont have IVA's.

**Comment by Modsojoy** [comment]
Also i need a Screenshot of the Part in unity before export because the IVA "up" axis is different from the External models "Up" Axis.

**Comment by Modsojoy** [comment]
![sc-b_int](https://cloud.githubusercontent.com/assets/21351692/18816955/76ea29b0-8322-11e6-8a40-18efd5c168ea.PNG)

External Adapted to Internal and the Main panel Mesh started, Also - you have an Amazing Mesh for the External, Its the hell of alot easier to convert.

**Comment by Modsojoy** [comment]
![sc-b_int1](https://cloud.githubusercontent.com/assets/21351692/18817065/e1391536-8324-11e6-9b36-cd155aff8ff7.PNG)

Main panel and Basic side panels done, Also added a cross-hair, Let me know if i should remove it.

**Comment by Modsojoy** [comment]
Also - you Didn't have to be so formal in the Email.

**Comment by Modsojoy** [comment]
Do you want me to submit a Pull request with the IVA Or just send you the files Via email?

**Comment by Modsojoy** [comment]
![the fuck](https://cloud.githubusercontent.com/assets/21351692/18818074/2a17fdda-833e-11e6-9f07-57f9b1107890.PNG)

So - quick question, Do you have any clue why most of the Verts have red dots on them, And wtf is going on with this, the handle was extruded off the capsule itself and it seems to have carried some of the UV Map data from it.

**Comment by Modsojoy** [comment]
OK Ignore last post, needed to Unpin everything.

**Comment by Modsojoy** [comment]
Im assuming this is the Apollo pod so - 
![contrast](https://cloud.githubusercontent.com/assets/21351692/18818308/e93e40fc-8343-11e6-9ef5-888dade719e8.PNG)

**Comment by Modsojoy** [comment]
![sc](https://cloud.githubusercontent.com/assets/21351692/18826021/43a83a70-8399-11e6-87cf-a6d7a3c22d00.PNG)

Cutaway view, Going to see what it takes to make a Cut-mask for the IVA Overlay.

**Comment by Modsojoy** [comment]
Should i follow standard Stock panel texture layouts (Tabs between panels) Or should i get creative with it.
![jewsgas](https://cloud.githubusercontent.com/assets/21351692/18827735/4c021a52-83a2-11e6-9baf-b8d9ff3a7009.PNG)

**Comment by shadowmage45** [comment]
Looking good so far geometry wise.

Texturing -- whatever you think will look best.  Tabs is probably a good place to start.

Files -- you can email them to me, or post up a link to dropbox/etc when they are done.
I'll work on getting the rest of the capsule files to you shortly; few things I need to clean up in those files first.

**Comment by Modsojoy** [comment]
Yeah - the file you sent me was all kinds of Odd, Transforms and Leftover bits everywhere.

**Comment by Modsojoy** [comment]
![jewishism](https://cloud.githubusercontent.com/assets/21351692/18959727/38fe3cde-8635-11e6-8e74-70075ee9b68c.PNG)

**Comment by shadowmage45** [comment]
Looks like it needs some smoothing and edge splits setup on the model, and perhaps some low-poly-simplification on a few things (notably those arms in the front look to have absurdly high poly count on the bent portion).  But that is about what my WIP stuff looks like as well (smoothing and low-polyfication come later in the modeling process).

Other than that the geometry is looking good so far -- I like the handles and accessories... those are bits of detail that I've always had a problem coming up with / doing properly.

**Comment by Modsojoy** [comment]
What arms? The Tubes? Also edge splits? Whats the point of that?

**Comment by Modsojoy** [comment]
I left flat shading on for the Tube in the front to give it a paneling effect, Those lines are Small dot patterns meant to look like screw/Rivets.

**Comment by shadowmage45** [comment]
Edge Splits -- also called smoothing groups, sharp edges, etc.  Allows you to have both flat and smooth shaded areas on the same mesh.  In blender these are 'sharp edges', used with the 'auto-smoothing' function.

Arms -- was referring to the two arms that are extending out from the camera in that screenshot.  They appear to be made from a nurbs path or other procedural tool, but appear to have LOTS of polys on where they do the 90' bend.

On the paneling rivets and edges -- are you familiar with the creation and use of normal-maps?  They can lend a ton of 'depth' to small detail bits like that.

Anyhow, not trying to be critical of a 'work-in-progress' as I know how it goes (some things just aren't done yet), just wanted to make sure they wouldn't be staying with hard-edges.  Might look okay on the interior paneling... though I would personally still do that using smoothed edges + diffuse/normal textures to make the paneling look.  You are the one doing the work though... so whatever works best for you :)

**Comment by Modsojoy** [comment]
The "Arms" Are meant to be like Oxygen/Electrical Tubes/Wires going to the LM/Station/Whatever, I have no clue how to make spec/norm maps,

**Comment by Modsojoy** [comment]
WIP texture shots.
![texman](https://cloud.githubusercontent.com/assets/21351692/19026125/0c4f3a18-88f0-11e6-88a9-d6b42069d1c0.PNG)

Also making a Crew optical Alignment sight as a prop
![coas](https://cloud.githubusercontent.com/assets/21351692/19026134/2d8e835a-88f0-11e6-8217-9e459f8dfce2.PNG)

**Comment by shadowmage45** [comment]
Sorry have been a bit busy/distracted this week.

Geometry still looking good, keep up the excellent work :)

Normal / specular maps -- let me know when you get there and I can likely help you out with those.  I'm pretty good with both at least from a technical perspective.
