### ISSUE TITLE
No engine icons in R&D, VAB, or SPH. No engine models at all in VAB/SPH.

### ISSUE THREAD

**Issue by taterkerman** [shadowmage45/SSTULabs#356]
Title says it all, there are no engine icons appearing anyplace they should. There are in fact no models to place at all.

**Comment by Pappystein** [comment]
Confirm and Add that no models appear to be present on Engines.  ver 0.5.33.126 KSP Build 1.2.0.1586 (x64)

**Comment by taterkerman** [comment]
Loaded game, threw log file in for you.
[KSP.log.zip](https://github.com/shadowmage45/SSTULabs/files/533850/KSP.log.zip)

**Comment by shadowmage45** [comment]
Thanks much for the log.

Looks to be related to... setting up the mount sizes for an engine.  I removed the OCTO mount definitions, but may have forgotten to remove their use from the layouts.

Derpy move on my part, but should be able to fix it up easily enough.

**Comment by taterkerman** [comment]
Figured it was something really trivial because it was so systemic, and clearly it must have worked recently for you, because it's so easy to notice.

**Comment by shadowmage45** [comment]
Yeah, was one of those last-minute changes... where I just happened to forget what all it affected, and figured it was so small I didn't bother testing it.

Have just fixed the config files, and will do a recompile/repackage later this evening with the fixes (after testing...).
