### ISSUE TITLE
Spherical Tanks have graphics alignment issue

### ISSUE THREAD

**Issue by Pappystein** [shadowmage45/SSTULabs#357]
Tater posted this in the forum
MFT-S structural details are approximately 15 degrees rotated from the other truss type tanks and bays EG MCB-A.

**Comment by taterkerman** [comment]
Here's my image:
![misalignment](https://cloud.githubusercontent.com/assets/17967275/19423062/ac3c5cec-93d9-11e6-8140-1653c30ed2a9.png)

**Comment by shadowmage45** [comment]
Strangely the tanks look fine in blender.  Must have been a problem in Unity that I didn't catch when I last re-exported those parts.

Will take a look at those this evening, likely can get them fixed up properly.

Hmm... also looks like I forgot to add the AO bake to the frame itself (it appears to be present on the tank, but no the frame).
