### ISSUE TITLE
New Category names

### ISSUE THREAD

**Issue by taterkerman** [shadowmage45/SSTULabs#358]
category = Communication

category = Electrical

category = Coupling

category = Ground

category = Thermal

Comm gets antennas, electrical gets solar, batteries, etc. Coupling gets docking ports and decouplers. Ground gets all landing gear/legs. Thermal gets heat shields, radiators, etc.

**Comment by shadowmage45** [comment]
Awesome, thanks for the info.  Should be able to update the parts using those names.

Sometimes I wish I had access to KSP at work so I could get info such as that.... but then I realize what a terrible idea it is (I would likely get no actual work done)

**Comment by taterkerman** [comment]
I’m home today waiting on a guy for a quote, lol.

**Comment by shadowmage45** [comment]
- HGA moved to Communication
- IPA, ISDC, RBDC, PDC, DP1, DP0, WDP moved to Coupling
- MHS moved to Thermal
- Solar panels moved to Electrical (24 parts)
- Nothing to move into Ground

**Comment by taterkerman** [comment]
I missed one!

category = Payload

This is used for the stock fairings now, and presumably the petal adapters would also go here?

I was so programmed to not even notice them since I no longer use them... that I didn't notice them, lol.
