### ISSUE TITLE
Right click UI issue

### ISSUE THREAD

**Issue by taterkerman** [shadowmage45/SSTULabs#359]
When a texture (or adapter, docking port, etc) name exceeds ~10 characters, it uses 2 lines, though only one is available. Makes it hard to read.

![right_click_ui_issue](https://cloud.githubusercontent.com/assets/17967275/19450027/11d52080-9465-11e6-8d8b-b33dcc8d0aec.png)

**Comment by shadowmage45** [comment]
Sadly this is a stock bug with the UI widget that I can do nothing to solve (at least the UI formatting end of things).

The only option on my end would be to truncate those display values at ~10 chars.  This would require altering the code on all of the UI control setup bits to pass in a different value for display vs. the actual data value (which is probably 60-80 different UI controls to update, spread across quite a few different modules). 

Honestly, I think they are more readable like that than they were in 1.1.3 with the values being cut off randomly.

Will take a look over the code though and see what it would take to manually truncate those values.  If I have to do it on every single UI control individually, I'll likely just leave it as-is.  

Edit:  The problem with truncating the values is that 90% of the adapters/selections would all end up displaying the same 10 chars (adapter-xxxx).

**Comment by blowfishpro** [comment]
This seems to be an unfortunate thing that happened to `UI_ChooseOption` in a very late prelease (if not 1.2 final).  Probably nothing modders can do, unfortunately.

**Comment by taterkerman** [comment]
Figured I'd toss it out here, I noticed it as a new behavior. My first reaction was to try and drag the UI window slightly wider, but that's not a thing :) .
