### ISSUE TITLE
Stock Game Settings Options

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#365]
- Options for game-settings menu.
  - ~~Boiloff enabled~~
  - ~~Model selection GUI or widget~~
  - others
  - ??
  - profit

**Comment by taterkerman** [comment]
This doesn't belong here, but is there anything on the level of plain text, or cfg stuff that you need/want done (assuming it would make your life easier)?

**Comment by shadowmage45** [comment]
Thanks for the offer :)

I might be able to find a few things that don't require extensive prior knowledge or lengthy explanations.  Will see what I can come up with.

**Comment by shadowmage45** [comment]
Have added boiloff and 'use model select gui' as game options.  Investigating where else I can use simple game options for various settings.

**Comment by taterkerman** [comment]
Figured it's the least I can do.
