### ISSUE TITLE
Using your RCS parts, get error

### ISSUE THREAD

**Issue by FHoulbreque** [shadowmage45/SSTULabs#385]
Using any of the SSTU RCS systems, I get a repeted error as you can see from my log below:

> [ERR 18:02:01.625] Module RcsSounds threw during OnUpdate: System.MissingMethodException: Method not found: 'Part.GetConnectedResources'.
> at Part.ModulesOnUpdate () [0x00000] in <filename unknown>:0 

Seems to be a missing file.

**Comment by shadowmage45** [comment]
'Module RcsSounds' appears to be a separate mod, and an out-of date one at that.   (The only way to get a MissingMethodException is by version mis-match between libraries).

 I locate any 'Module RcsSounds' in the stock API/module list, and I know that it is not an SSTU class/module.

Do you have full log files available?

(For reference, my RCS ports do not have any sounds, and still use the old RCS effects system)

**Comment by blowfishpro** [comment]
Probably this mod: https://github.com/pizzaoverhead/RcsSounds

Definitely not updated for KSP 1.2

**Comment by FHoulbreque** [comment]
Sorry for this bug which is not related to you... But only happens with your RCS and not the stock one... don't know why. It's coming with KSPI Extended... I'll check that, thanks
