### ISSUE TITLE
New line needed in the probe core

### ISSUE THREAD

**Issue by taterkerman** [shadowmage45/SSTULabs#386]
hasHibernation = True

1.2 allows probes to go into a sleep mode to conserve power.

`MODULE
{
	name = ModuleCommand
	minimumCrew = 0	
	RESOURCE
	{
		name = ElectricCharge
		rate = 0.0275
	}
        hasHibernation = True

}`

**Comment by shadowmage45** [comment]
Noted; should be able to add that in for the next release.

Overall power consumption and probe-capabilities will also be receiving a balance pass in the near future.  Will likely be moving the pods-with-integrated-probes to use the PartUpgrade system to unlock advanced probe-core functionality separate from the pods themselves -- so they will by default come with a probe-core with only minimal functionality, which can be independently upgraded to provide the advanced pilot/probe features.  Possibly even an upgrade to allow for science transmission directly from pods?...

**Comment by taterkerman** [comment]
Cool.I was thinking about balance WRT our discussion about sounding rockets, and other unmanned craft. The new stock hibernation capability is great, actually. I like the idea of time-limited probes, I just think that they should actually be possible, lol.

The pod functionality seems reasonable. As an aside, how hard would variant probe cores be? Like using the tank nosecones as an option, perhaps with a container (combo probe core, EC, and monoprop, for example. The only really useful addition for probes might be tiny versions of some of the RCS thrusters, too..

**Comment by shadowmage45** [comment]
Have added hibernate mode to all LC, SC and ST probe/command-enabled parts.
