### ISSUE TITLE
Tank SC TANK MFT A and parts are not resizable

### ISSUE THREAD

**Issue by x3l1a** [shadowmage45/SSTULabs#390]
Helloooooo
why not longers how the option for adjust the diameter ?
thanks shadowmage

**Comment by shadowmage45** [comment]
They do still allow scaling, but stock game config options are dumb and disabled by default.

If you are playing in sandbox mode
* Go to the space center
* Hit the 'Esc' key
* Go to game options
* Go to advanced options
* Enable 'Apply upgrades in sandbox mode'

**Comment by Tetrago** [comment]
can't find that in 1.2.1, when I press escape the only similar option is "settings". (Doesn't have advanced options or apply upgrades in sandbox mode)

**Comment by Tetrago** [comment]
FIX: It's settings, difficulty options, advanced, then apply upgrades.
