### ISSUE TITLE
Landing Module?

### ISSUE THREAD

**Issue by Tetrago** [shadowmage45/SSTULabs#391]
I have not used this before, I may be dump, but in videos I see the lander type command module (the orange things) and a lander section under it, with legs and etc. Either its not a thing, a bug, or the part doesn't look that way in the parts bar. Explanation please?

**Comment by taterkerman** [comment]
I honestly can't understand what you are saying. The lander crew module is there (2 smaller ones, and a large one). The orange tanks are toggled on/off via the "variant" option in the right click in the VAB.

The modular landing tanks have many tank variants, but the optional legs/solar/etc got messed up by the new KSP/Unity versions, so they are discontinued (at least for now).

**Comment by Tetrago** [comment]
Sorry, I didn't reread it. My question was about the landing legs. You answered just fine, and I now understande. Thanks :)
