### ISSUE TITLE
Command Pods Have No Drag

### ISSUE THREAD

**Issue by CtrlAltElitist** [shadowmage45/SSTULabs#392]
I have a bug where occasionally, the command pods from SSTU exhibit no atmospheric drag. While this is great for takeoff, it makes reentry impossible. I'm currently running SSTU-0.5.32.125 because it seems to be the last stable version for realism overhaul 1.1.3. If anyone could help me resolve this issue it would be great. I am running FAR 3:0.15.7.2 in addition to SSTU. If that helps

**Comment by taterkerman** [comment]
SSTU has never been officially worked on for RSS/RO, partially because the fact that FAR does not work for it is a known issue.

**Comment by CtrlAltElitist** [comment]
Makes sense. I'll still put up with it, because its a kick-ass mod. It seems to work fine if i just attach a FAR heat shield to the command pod. If it's stupid but it works, it's not stupid. Thanks
