### ISSUE TITLE
Can't change fuel tank,engine diameter in 1.2

### ISSUE THREAD

**Issue by AdityaShauman** [shadowmage45/SSTULabs#394]
Is this a common issue or just me? It seems that no one complaining about this, please help/fix it

**Comment by blowfishpro** [comment]
http://forum.kerbalspaceprogram.com/index.php?showtopic=117090&page=222#comment-2879106

**Comment by shadowmage45** [comment]
Not really a bug or problem with SSTU.

I have however added code in the next release that should 'fix' this, by force-setting the stock config for the option.

**Comment by AdityaShauman** [comment]
Thank you all!!! I'm looking forward to more parts added to this mod
