### ISSUE TITLE
SSTU-ST-CFG-50 - Inflat ? - RocketParts?

### ISSUE THREAD

**Issue by izzycloud** [shadowmage45/SSTULabs#395]
Hello

My exchange the operator language is not good.

Please how I will open a station module SSTU-ST-CFG-50?

What are "RocketParts"?

Where can I find them?

This MOD is very entertaining. :-)

Thank you very much for the positive response.

"Czechia"

**Comment by shadowmage45** [comment]
Use one of the SSTU - MFT fuel tanks.  Click the 'Configure Containers' button.  Inside that GUI it should let you select RocketParts as one of the resources for the fuel tank.

Once launched / in orbit, press the 'Inflate' button to use the RocketParts and finish construction of the CFG part.

**Comment by izzycloud** [comment]
I found it :-)


Great, thank you.
