### ISSUE TITLE
COS surface attach problems -- incorrect part colliders

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#397]
Surface attach items float a bit above the DOS module surfaces (LAB and HAB parts)

![screenshot_170103_002](https://cloud.githubusercontent.com/assets/16107012/21616365/7b773a5a-d1e1-11e6-9646-bc6948cf30e0.jpg)

**Comment by shadowmage45** [comment]
I'll take a look at the colliders for those parts.  I thought I had them set up pretty tight around the visible mesh, so there certainly shouldn't be that kind of discrepancy, at least not on the COS parts.

Hmm... looking at them in blender, they don't have any special colliders assigned, they appear to use a standard 'mesh' collider... which likely got screwed up when the ladders/etc got added to the base mesh.

Will see if I can duplicate the problem in my dev install, and then look into re-exporting the parts with custom collider if needs be.

**Comment by Jimbodiah** [comment]
It looks as thought the "surface" is at the height level of the yellow handrails instead of the hull itself.

**Comment by shadowmage45** [comment]
Hmm.. yeah, probably related to the default Unity mesh-colliders that are in place for those parts.  I likely never updated the colliders after I added the hand-rails to the models.

As a bonus, when I fix the colliders, there will be a slight performance increase when using those parts (from the more optimal / simpler colliders that will be used).

So, yep, apparently I need to add some custom colliders and re-export those parts...

**Comment by shadowmage45** [comment]
Fixed, will be available with a release later today.
