### ISSUE TITLE
Solar Panels with no attachment nodes

### ISSUE THREAD

**Issue by Pappystein** [shadowmage45/SSTULabs#398]
The following panels have no attachment nodes to allow for precise placement.
ST-GEN-DSP-ISS. 
ST-GEN-DSP-DOS-T
ST-GEN-DSP-BKT-A/B and C

Each of these parts have a large post that stand them off of the attached models.  While the rest of the SSTU Solar panels also have no nodes, they do not stand away from the attached model when not deployed, and thus are less in need of the ability to attach directly to a node.

Goal of this:  Allow a single unit of any of the above to be centrally attached to a top or bottom node of any space station part.  IE not have to rely on Mk1mod2 Eyeball placement.

**Comment by shadowmage45** [comment]
Fixed in dev repo, will be available with the next update.
