### ISSUE TITLE
ISS and Skylab solar panels arent included in the CommunityTechTree config for career mode

### ISSUE THREAD

**Issue by snekposter** [shadowmage45/SSTULabs#401]
Latest SSTU and KSP versions.

Tested in career mode, created two new career saves after wondering where the ISS panels were in my current save. When I used the debug menu to max tech progression in the ctt career save, the ISS and Skylan panels were not in the part catalog when searching for sstu with the part search menu. After reloading the game with the CTT folder moved out of the gamedata folder to my desktop, and using the debug menu again in a new career save, the parts were present. The only difference between the two saves is the first one was using the Community Tech Tree.
![screenshot80](https://cloud.githubusercontent.com/assets/25206943/22077440/726ffa8c-dd71-11e6-8301-0fb862fc05c0.png)
![screenshot82](https://cloud.githubusercontent.com/assets/25206943/22077452/781cd6b2-dd71-11e6-9130-21a4f24a1305.png)

**Comment by shadowmage45** [comment]
Yea, there were some incorrect node definitions in the CTT patch.

Already fixed in dev; will be available whenever I have time to push out an updated release (pending free time from working on other projects, may still be a few weeks...)
