### ISSUE TITLE
MFT turns black

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#411]
I just had a weird thing where the second stage MFT-A tank turned from white to black during a launch. I don't know at which point it happened exactly as I launched at night, but I noticed it when I got into the sunlight.
![screenshot_170210_002](https://cloud.githubusercontent.com/assets/16107012/22845236/eb0e8292-efe1-11e6-8ccc-1dfc2a83817f.jpg)
![screenshot_170210_001](https://cloud.githubusercontent.com/assets/16107012/22845237/eb0ff44c-efe1-11e6-88bc-aa1cd1a418f5.jpg)

zip files will not include for some reason, so here is a download link:
http://jimbodiah.com/mft_black.zip

**Comment by shadowmage45** [comment]
Hmm.. that is an interesting occurrence.  Looks like its not just a simple texture-swap error, as the pipes on the tank were also turned black.  Specular mask is still in place, though with my shaders that is a separate texture.  

Does a quick-save and reload 'fix' the problem?  (E.g. is it a temporary problem, or is it persistent with the craft/part?)

My first thought would be something in the shaders not playing nicely with.... something... (could be stock or other mods).  Or could be another mod setting the material.color to black for some reason.


Reading through the log there are quite a few exceptions from other mods (one example):
(Thanks for including logs though, give me at least a chance to see what was going on :) )
````
[ERR 22:36:18.601] Module RcsSounds threw during OnUpdate: System.MissingMethodException: Method not found: 'Part.GetConnectedResources'.
  at Part.ModulesOnUpdate () [0x00000] in <filename unknown>:0 
````
Going to be hard to tell if one of those is the cause or not....


Anyhow, if you can come up with steps to duplicate the problem reliably I will certainly look into it.

**Comment by Jimbodiah** [comment]
It's like the texture is just missing, as the black of that screenshot is not the same as the black texture. 

A reload does indeed show the original texture again.

I'm running a clean RSS install with no other visual enhancements  like EVE, scatterer, realplume etc. If it happens again I will remove all other mods to see if I can reproduce it.

RCSsounds is a remnant from Interstaller Extended, I will remove it, hadn't even noiced it was still in there.

**Comment by shadowmage45** [comment]
I have mostly tracked this down to something setting the 'Burn Color' in the shader to black (or one of the other color properties).

I believe that shader property is supposed to darken/blacken models when they are exposed to duration heating/re-entry effects.  AFAIK stock code doesn't do anything with the BurnColor property in default configuration, but there might be mods or stock config options that enable it.

I'll keep an eye out to see if I can spot where stock code plays with that shader property.  I might just be able to remove that property entirely from the shader.

**Comment by Jimbodiah** [comment]
I've not seen it since then.
