### ISSUE TITLE
SC-ENG - Remove 'GimbalSpeed' from configs -- conflicts with MechJeb

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#412]
MJ Appears to not function well with engines that have gimbal speed enabled, causes oscillating even when sufficient authority exists to hold a direction.

This might be caused only by the extra roll gimbal/exhaust on the Merlin-1A/B/BV engines.  Though I seem to also remember seeing problems with clusters of H-1s.

**Comment by taterkerman** [comment]
I can report that this happens with the "gravity turn" mod as well---which I think might be a branch of MJ that only does launches for a minimalist version of MJ. I like it for testing, as I can eliminate piloting errors to test really consistent launches.

On the engines with 2 gimbal sliders, I can eliminate much of the oscillation by killing the 2d gimbal entirely. Different engines tend to have different oscillations. One set (early Merlins?) oscillates in pitch, another type does so in roll.

I'd test, but my son has a friend over and they are messing with minecraft on my machine, lol.
