### ISSUE TITLE
MFT textures and mount option techtree related?

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#424]
I built a soyuz in Sandbox and when importing to a career save, the color and mount options were gone for the MFT-D, and no texture options for the MFT-A nose (soyuz style). Is this techtree dependant? I don't have a save further along so can't tell yet until I unlock more nodes on the tank upgrades.

**Comment by shadowmage45** [comment]
Hmm.. that is strange.

Neither the texture sets nor mounts are limited by the tech-tree in any way.  Swapping the craft file between saves should have no effect on either of those.

Was this between two saves in the same install, or between two different KSP installs (possibly with different mod sets)?

The only reason you should lose the texture-set options would be if for some reason those new texture sets were not available in the career game -- which would be a config/install based problem.

(Of course, there could be some obscure bug that is causing all of this).

**Comment by Jimbodiah** [comment]
I'll check it out, will edit the save file to add science and see if the texture option returns...

I never used the soyuz options before so I have never noticed.

**Comment by Jimbodiah** [comment]
Euhm... I think  solved it... I might have had José's pack installed on a prior sandbox save... Even when I have almost all the techtree unlocked the options do not come back so I am starting to doubt it's an SSTU thing. Do you have any other textures on the MFT-D besides the grey?

False alarm?

**Comment by shadowmage45** [comment]
Stock-SSTU only has I think 3 or 4 textures for the MFT-D -- gray, green, white, and black.  Edit:   Looking through the source now, and it looks like 'Gray' is all that comes with the stock SSTU install, the other colors must have been part of the old (deprecated/removed) texture-set pack.

If you loaded a craft that were using texture-sets that are not present in the current install, it -should- default them back to whatever the 'default' texture set is for that part (but there might be bugs / errors that cause it to not load the rest of the sets... never tried removing an in-use texture set).

**Comment by Jimbodiah** [comment]
I had a green soyuz when I saved the .craft a while back and when I imported it, it became grey on the D tanks, plus the A-tank with soyuz top had a green body with grey top. So I think this means it was using José's extra textures when I made it at the time.
