### ISSUE TITLE
Tank, Mount, Nose, and Adapter Texture Reworking / Cleanup

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#425]
Need to find a way to 'clean up' all the various tank, nose, and adapter textures to use a more unified set of base textures.  Few of these parts use any sort of detailing, it is mostly flat texture + noise + AO + specular; nearly perfect for texture-sheet re-use.

The goal of this change would be to reduce the number of textures needed/shipped with the mod, and to use a unified set of colors/masks across all parts.  So gray on a tank will be the same as gray on a nosecone, will be the same as gray on a mount.

### MFT Tanks - Nosecones - Adapters
* Might require making up one or more normal maps for some of the adapters -- some have paneling or stringer lines; most also use some masking to hide the seams in the diff, spec, and nrm textures -- can they be unwrapped in such a way that the masking is not needed (while still allowing for using straight lines on the texture sheets)?
* How to handle the adapters/nosecones/etc that have striped variants -- how could these be mapped onto the existing tank textures?
* Will obviously still require having multiple AO masks, one for each main line of parts (one for each tank variant, one for nosecones, one for adapters).
* Looks to be impossible to unwrap the adapters in such a way as so that they can use a common texture.  Any method that allows common texture use will either end up with massive distortion (no-go), or seams on every face (again, no-go).
* Can the MFT-D and L textures be mapped onto the same texture sheet?

### Mounts (engines, tanks)
Slightly more problematic with their model setups, but might still be able to use the same base texture sheets as the tanks, with some minor additions.
* Mounting detail ring -- the mounts mostly come with a ring of greeble on them.

### Removal of multi-adapter mount selections
* They don't get used and the texture mapping on them was highly problematic.  3/4 of the adapter texture sheet was just for these multi-adapters.

**Comment by taterkerman** [comment]
Does this include the hab stuff? Seems like the orange for inflatables should instead be gold foil, for example:
![the-isss-beam-is-just-the-first-of-the-expandable-habitats-bigelow-hopes-to-launch-into-space-the-company-is-also-building-a-larger-unit-called-the-ba-330-which-will-house-six-astronauts](https://cloud.githubusercontent.com/assets/17967275/23715653/8a5acf7e-03ea-11e7-8a76-32117d3790f2.jpg)

**Comment by shadowmage45** [comment]
Nope, this would not be touching the HAB parts (except for their adapters).

The goal for this...project... is to eliminate 3/4 of the adapter/nosecone textures and allow them to re-use the texture sheet from the tanks themselves.  Basically just a reduction in how many textures I need to manage, as well as ensuring that all of the adapters and tanks are color-matched.

Sadly I am unable to find a way to unwrap a cone-shaped-mesh that allows for texture re-use.  They need the ability to have normal mapping, and any attempts to re-use the same texture/UV area result in major texture distortion.  So, not sure how far this project/idea will be progressing (probably won't be progressing at all if the one thing needed for it to work turns out to be impossible -- the UV mapping).

**Comment by shadowmage45** [comment]
Looks like this is being done through #432.
