### ISSUE TITLE
Engine Cluster Pricing

### ISSUE THREAD

**Issue by jobadiah08** [shadowmage45/SSTULabs#427]
First, If this is actually an issue for Real Fuels or RO, let me know.

When playing with RO/RP-0, clustering engines does not multiply the price correctly when using upgraded engines. Example: RL-10
Base engine is RL-10A-1 @$1300 ea. Cluster of five costs $6500 (correct)
Upgrade to RL-10A-3-1 @$1550 ea. Cluster of five costs $12750 (should be $7750)

What appears to be happening is the cluster shows an upgrade cost of $1250 for the five engines to be upgraded, but then that additional cost is added to each engine in the cost. So instead of costing $250 to upgrade each, it is $1250. The cost equation appears to be (my guess)

Cost = (BasePrice+UpgradeCost)*EngineCount

Fix: Cost = BasePrice*EngineCount + UpgradeCost

This should keep upgrade cost from being charged multiple times.

**Comment by shadowmage45** [comment]
RO issue -- or more precisely RF and ModuleEngineConfigs.  Nothing that I can do to solve it.

If you note, I already properly calculate the engine cost when RO/RF/etc is not used.  So whatever the problem is, it is on their end.

**Comment by jobadiah08** [comment]
Okay, I wasn't sure what end it was on. I will take it over there. Thank you.
