### ISSUE TITLE
sc-b fuel tanks - too low breaking force/torque

### ISSUE THREAD

**Issue by riocrokite** [shadowmage45/SSTULabs#43]
Would be good to increase them for big fuel tanks, since when they're not specified they equal 22. I guess 1000-2000 for the biggest tank would be enough:)
It would allow tanks to be used for mobile tanker:
![GitHub Logo](http://i.imgur.com/v3xF6FR.png)

**Comment by shadowmage45** [comment]
Thanks for the heads-up.  

Will increase default breaking force and torque for all tanks in the part configs, and add an extended 'enhancement request' to add variable stats per tank size (will need added to configs, and support in the plugin for it).

Initial config-only change will be available with the next update (10-24-15).
