### ISSUE TITLE
Default option on isdc/mft

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#433]
Hi Mage,

Is there a parameter (or rather which one is it) to change the default setting for:

MFT: Cryo type textures instead of Kerolox.
ISDC: invert direction of the decoupler engines

I found basically every other option like cap/mount for the MFT and top/bottom decouple enables, but did not find a variable referring to above settings. Maybe there are variables, but they are just not used in the cfg files.

BTW: Would it be okay if I at some point uploaded a small expansion pack that I have made so far using SSTU, a little like what José did? Your name is on all the cfgs, I just edited/copied some of your parts with mm-patches to suit my play-style (like TAC lifesupport versions of the DOS modules to use as ATV, the radial materials bay as a complete science package, stuff like that).

**Comment by shadowmage45** [comment]
MFT:  change 'currentTankType = MFT-A-3-0'  to 'currentTankType = MFT-C-3-0' -- and it should default to cryo tanks (the ones with no piping).

ISDC:  add 'inverteEngines=true' somewhere in the modules' config.

Expansion pack:  I have no problem with you making or releasing one, and will provide whatever support I can to help you get it up and going.  Just let me know if you run into any questions.

**Comment by Jimbodiah** [comment]
I even tried all the angles on the ISDC to see if it was one of those :)

Thanks a million mage!!!!!  You made my day :) Less clicking is always better :)

Expansion pack (big words, more like Jimbo's personal SSTU tweaks). Everything is working right now, not hard stuff, just useful changes and additions for me personally. I'll let you know when I upload it. Anything I make of interest is free for you to take over, that goes without saying.
