### ISSUE TITLE
Scale slider on SC-E parts

### ISSUE THREAD

**Issue by blowfishpro** [shadowmage45/SSTULabs#436]
I think these get a scale editor from KSPWheel.  Maybe this should be disabled?  It doesn't seem to play well with everything else on the part.

**Comment by shadowmage45** [comment]
Ahh, yes, I knew there was something I forgot when adjusting the SC-E configs.

Yes, the scale slider should be disabled on those parts, it is an option in KSPWheelBase that will need to be added to the part configs (allowScaling = true/false).
