### ISSUE TITLE
SC-GEN-MHS (Heatshield) Will not resize.

### ISSUE THREAD

**Issue by Veit23** [shadowmage45/SSTULabs#441]
The SSTU Heatshield will no longer resize from the default size. The shield fairing will, however.
I am playing an Realism Overhaul and RP-0 Career, if that might interfere.
Please tell me if pictures will be needed.
Regards, Veit

**Comment by taterkerman** [comment]
In career have to unlocked the upgrades to increase heat shield diameter?

**Comment by Veit23** [comment]
I have tested this in sandbox, and the shield still will not change.
Regards, Veit

**Comment by taterkerman** [comment]
Check under difficulty, and make sure all upgrades applied in sandbox is checked.
