### ISSUE TITLE
SC-E IVA is positioned in the rear of craft. 

### ISSUE THREAD

**Issue by lynwoodm** [shadowmage45/SSTULabs#442]
I am not sure if this has been addressed or even been considered being addressed, but the IVA for SC-E IVA is appearing in the rear of the craft. It actually shows two cockpits, in which one kerbal is seated properly, while the rest are looking ahead (forlornly, I might add) to the bow cockpit. 

![20170417000000_1](https://cloud.githubusercontent.com/assets/15900022/25079056/fa56331e-2306-11e7-8823-db867c5d94b4.jpg)
![20170417000017_1](https://cloud.githubusercontent.com/assets/15900022/25079055/fa55cb72-2306-11e7-832e-6b8da498249e.jpg)

I seen you posted a cockpit for the SC-E fuselage from Jeast, but haven't tested it yet. Will this fix the problem? Or is it a positioning error? If you need more input on this, let me know. I will fish around some more.

**Comment by shadowmage45** [comment]
Thanks for the report; yeah, this is kind of a known issue.  Good to get it logged officially though.  Sometime inbetween 1.05 and 1.2, SQUAD removed the method that I was using to offset the IVA models, and I'm unsure as to a replacement.

However I have had some new IVA meshes donated to me, and merely need the time to rework them/etc.  ( #423 )

As with all things IVA related -- this is not very high on my priority list of things to investigate/fix.  If you (or anyone else reading this) is aware of a solution for the problem with the existing IVA (how to offset the IVA model relative to the part model), feel free to chime in and/or submit a PR, and we might be able to get the problem fixed in the short-term (rather than waiting for me to get to it, which might be never).

**Comment by lynwoodm** [comment]
From what I understand, the IVA is now in another layer of the Unity engine. I think it has to do with the see-through-hull function. The only other full part shuttle body that may have an IVA in the same configuration is Decq's Shuttle Mod. I have yet to download and use it, but he usually has a functional IVA for Realism. But, as you said, this isn't an issue that deserves a priority (and I don't actually blame you, IVA's are so time consuming and a PITA). I will look into how he has his set up. There maybe a way around it.

**Comment by lynwoodm** [comment]
*Update* I was wrong about the other mod. The cockpit was a separate part. Along with all the other parts that I thought were a one-piece-design. Le Sigh. You may have to end up either making the cockpit one part or just let it ride as is. As I see, you are working on bigger problems than this. My guess is that you will probably put this on the way back burner for a while.

 But, I will add; if you -did- separate the cockpit from the rest of the model, you don't have to worry about making an IVA for it. I'm sure people will start putting in IVAs from other mods in there. Unless there is a painless solution in the modding community this is one of those "10 meter cattle prod" scenarios.

**Comment by shadowmage45** [comment]
Well, -supposedly- there was a config-based solution added to stock code to allow for offseting the IVA.
Something like:
````
INTERNAL
{
    name = IVAModelName
    position = x,y,z
    rotation = x,y,z
}
````

But I've not had the time to investigate on if it works/etc.

You could give that a go and see if the 'position = X,Y,Z' line makes any difference.  It might be as simple as that.

**Comment by lynwoodm** [comment]
I could of swore that you had that in your IVA config? You have it for a MODEL.
`MODEL
{
	model = SSTU/Assets/SC-GEN-LG-B
	position = 0, 14.88477, 0.78482
	rotation = -90, 0, 0
}`
The IVA config doesn't have a position config, like I remember it had before. 
 I'm going to strip it down to sstu and dependencies to get the proper placement and will post the position for a fix if it fixes it.

**Comment by lynwoodm** [comment]
After taking a stab at this and with a full crew compliment, the seats that were set up in the Spaces/SC-E-IVA are showing up where they are supposed to be. However, using the IVA config-based positioning for the Part configuration did nothing to move that rear forward facing cockpit or move the first 4 seated kerbals forward to the bow of the shuttle. I don't think that old solution works anymore. 

I'd say just shove off the stove for now.
