### ISSUE TITLE
Saddle Truss masses to much at small diameters

### ISSUE THREAD

**Issue by blowfishpro** [shadowmage45/SSTULabs#443]
At its smallest size, it masses over 4.6t (this is 0.625m diameter, 0.5x height).  This seems a bit much to me...

**Comment by shadowmage45** [comment]
Indeed, seems a bit much to me as well.  Likely some mass parameters not setup properly, or the module is not properly scaling the mass.

Thanks for the report, will look into it shortly.

**Comment by shadowmage45** [comment]
Can confirm that this exists even in the current dev-code.  Doesn't appear to effect the fuel tanks, so seems likely that it is something specific in the modular-cargo-bay module itself, which is thankfully fairly short.

It is a bit strange though, as scaling it up past a certain diameter does start increasing the mass.

Hopefully this will no longer be a problem as I swap the cargo-bays over to using the MFT module directly, which I recently added animation support for in preparation of the swap.

**Comment by shadowmage45** [comment]
Fixed; had improperly set both fuel tank and volume container modules to not zero out the config mass (so everything had an extra 4.6+t added to it).
