### ISSUE TITLE
SC-E Parts Adjustment and Ideas

### ISSUE THREAD

**Issue by lynwoodm** [shadowmage45/SSTULabs#447]
I know this is a back burner issue, but I figured I'd get to work/address these small issues that I've came across while looking at the config files for the parts in this series. 

1. Fuel Gen is still using MonoPropellant as fuel source and hasn't changed over to the Aerozine50/NTO fuels for generation. I had in mind of giving 100 (maybe 25, debatable) more fuel of each and taking the 0.001875  usage from MP and divide that by 2 (which is 0.0009375) to give a balanced draw from both fuels. Just wanted to see if you'd like for me to change that and I will make a pull request and make it happen.

2. I had added the Crossfeed stock module to the FS part on my end and it seems to work properly as intended. Just a heads up to remind people to enable the cross feed on the tanks for the adjusted RBDC. I know you will get someone who will no be able to make it work and then you'll have to explain why. Again, I will make a pull request and make it happen if you'd like this feature for these parts.

3. How hard would it be to separate the cockpit module from the rest of the FS/FSX part? Would it effect heat dissipation? CoM issues? While I brought this up on another issue, I am concentrated on this work for less work for an IVA that you really don't have to make (yes, I like IVAs), since there are several out there that work wonderfully. While it would be one more part, it would solve the IVA issue instantly. The adjustment parameters just don't work anymore, except for the seats you have set up in the Space IVA. But, the other bright side to this is a smaller GUI for the fuselage and cockpit. instead of one long GUI for everything. 

Anything else I can think of and find, I will post it here and get your take on it (or anyone else). Again, I understand that you may not want to touch these parts or you just don't have time to fool with it. If I had a better working knowledge of Unity and Blender, I would be on this like white on rice, with your blessing.

**Comment by shadowmage45** [comment]
1.  Take a look at the SC-B-SM for what the setup for the fuel cell should be.  Probably very similar to what you have proposed, but I'm unsure on the specifics from memory.  I would leave the resource amounts in the part unchanged as they should have already taken into account the fuel-cell usage.  Feel free to put up a PR for this change once you get the specifics figured out.
2.  Very hesitant to add any more modules to that part.  It is already busy enough with all of the buttons on the right click menu.  Is the crossfeed module actually needed?  I suppose you can put together a PR for this as well, and I'll give it a test to see if the extra button or functionality is problematic.
3.  No thanks.  I have zero interest in splitting up the cockpit and fuselage; if I have to split the model up any further than it already is, I'll pull the entire line of parts and stop distributing them.  It is already split up far more than I would like; I'm hesitant to keep it even in its current form (I want it to all be a single part, sadly, KSP cannot support such complexities).  

Shuttle IVA issues -- as stated in the other ticket, I'm relatively certain that there -is- a method that can be used to offset the stock IVA into proper position.  Simply need to find what that method is, and how to use it.  You might be able to ask on the KSP forums what that method is -- someone knows, as I remember reading about it in their posts -- I just don't remember who, or what the thread was originally about (nor did I bother to bookmark things).  I'll do some poking and digging to see if I can locate the information.

Thanks for looking into the rest of the SC-E stuff; I haven't had the time to go back over those parts in quite awhile.

**Comment by lynwoodm** [comment]
Okay. The SC-B-SM fuel generator draws 0.0046875 for Aerozine50/NTO, respectively, to generate 1.5 Ec/s. The shuttle fuel generator puts out the same Ec/s. So, it would make sense for this generator to have that smaller amount of fuel usage for longer duration space flight than the SC-B parts. I'm not sure of the maths on this, but my original idea of dividing the MP fuel by two seems logical for me. 

Cross Feed Module
I changed the fuelCrossFeed = False to True to see if this was possible to do without the module. And it was, I just had to change the Cross Feed to Enabled on the Fuel Tank to get it to work. So, there's no need to put that module in there. I was "module happy" (well, I was euphoric about contributing.. yeah, ego). 

IVA
I will look further into the IVA problem. I will ask the community to see what needs to be done. To be honest, I don't see why your original adjustments to the IVA doesn't work with the first 4 original seats and the kerbals that supposed to sit in them? The adjustments affect the last 3 seats accordingly. If anyone has any bright ideas on this, please feel free to share them with me.

**Comment by shadowmage45** [comment]
So.. I have poked around at the KSP-API a bit, and think I might have found a solution to the IVA offsetting stuff.  Apparently while MODEL nodes use 'position = x,y,z' for positioning of the models, INTERNAL nodes use 'offset = x,y,z'.  (WTB consistency in the KSP API, paying well!!!!)

So, you might try something like this for the SC-E part config:

INTERNAL
{
    name = MK3_Cockpit_Int
    offset = 0, 1, -13
}
(replace the existing INTERNAL node in the part with the above bit of code)

It will lack the seat transforms for the extra 3 seats -- I'll need to find a way to work those back into the IVA, but the above setup should at least get the position of the rest of the IVA model correct.

**Comment by lynwoodm** [comment]
The offset parameter accomplished the desired result, placing the IVA in the correct place. Amazing what one flipping command accomplishes. It will still show 7 kerbals on screen, but the last two cannot be seen in the cabin. Otherwise functional. I think I have a mod that adjusts the MK 3 Cabin occupants to show 5? Heh, I don't care, at least I don't see the iva in the back of the ship anymore. 

If this works for the stock cockpit, I am wondering about the other ones? The new DECQ shuttle IVA houses 7 occupants and shows them in different areas of the cockpit. But, for now it works with just stock. If you are satisfied by this result, I can apply the changes for you. 

![20170502195554_1](https://cloud.githubusercontent.com/assets/15900022/25644169/fc3e2dae-2f71-11e7-8e7f-61fffba71a7a.jpg)
![20170502195657_1](https://cloud.githubusercontent.com/assets/15900022/25644168/fc3c065a-2f71-11e7-9b00-05aa5cc8e50a.jpg)

**Comment by shadowmage45** [comment]
Excellent news, glad that a solution to this has finally been found.

Extra seats -- now that a solution for the IVA placement has been found, it should be fairly simple to add the extra seats back in.  I'll take a look at the existing setup to see what all will need to be changed/adjusted, likely just a couple lines need to be changed in the existing files in order to fix the seat locations.

Other mods IVAs -- yep, same setup should work for them, and if they are compatible with the stock Mk3 cockpit, the exact same offset values should be used.  If you give it a try and find that it is working, feel free to put together an optional patch to convert the SC-E to that IVA model whenever the requisite mods are present.  Hit me up if you need help figuring out what the patch setup for those would be.

**Comment by shadowmage45** [comment]
Have tested the fix on the existing SC-E IVAs, and managed to get everything back into proper position (or at least as close as it ever was).  Including all 7 seats being present.

Fix is available in dev versions, and will be available with the next full release.

**Comment by lynwoodm** [comment]
Right on!

**Comment by lynwoodm** [comment]
Did some IVA experiments and you can put another IVA in place of the original with a patch. The one I was experimenting with doesn't exactly -fit- the SC-E-FS model (showing window edge artifacts). But, I can adjust the offset to compensate for this. Just a couple of problems: the kerbals are about a foot off the seats and the outside view for the portraits are black in background. Might be the original IVA? But, the fact that you can put another IVA in place of the one you made is very promising. 

*Update*
The "problem" with this IVA is not due to the offset. It's a original mod related problem, so nothing can be done in that department. I can post the config for this IVA if there are people who really want to immerse themselves.
