### ISSUE TITLE
SRBs zero-thrust/burn tim in RO

### ISSUE THREAD

**Issue by Vanya-Kerbalnovich** [shadowmage45/SSTULabs#451]
The modular SRBs report a burntime of NaN and a thrust of zero in the VAB. RealFuels correctly assigns a fuel, so the engine configs might not be playing nice with Realfuels. Install is KSP 1.2.2, with RO and RP-0.

**Comment by blowfishpro** [comment]
The RO SRB configs (which are 100% on RO's side) have been broken for a while.  They need to be completely redone I suspect.

**Comment by Vanya-Kerbalnovich** [comment]
Copy that. Thanks for pointing me in the right direction. These SRBs are so nice I can't wait to use them!

**Comment by shadowmage45** [comment]
If there are code-side changes needed in SSTU in order to make it all work, please let me know at that point.  Would need to be quite specific as what needs changed/fixed though, preferably through a PR.

**Comment by assassinacc** [comment]
related: https://github.com/KSP-RO/RealismOverhaul/issues/1625
