### ISSUE TITLE
Inflatable 

### ISSUE THREAD

**Issue by Pfalbo1** [shadowmage45/SSTULabs#452]
So... I don't know if i'm dumb at this point but to inflamate the SSTU part in mission you need a certain tons of RocketParts and i don't have any idea on what is this , so i tried rocket fuel but its not... it's not really a issue but i don't know what to do 
thanks

**Comment by blowfishpro** [comment]
You can switch any of the SSTU tanks to RocketParts, and they will contain the resource you need.

**Comment by JonRR** [comment]
I have the same issue. How do you change an Inflatable parts tanks to RocketParts? I can't see any option to do that? Basically they inflate in the hanger but not in the mission which is a little confusing...

**Comment by shadowmage45** [comment]
You don't change the inflatable.

You fly up a separate craft using an MFT fuel tank which is configured to hold RocketParts.  Dock.  Press the 'inflate' button.  Done.

MFT fuel tanks can be configured in the editor by pressing the 'configure container' button.  Alternatively there should also be a 'RocketParts' selection on the 'Fuel Type' slider.

**Comment by taterkerman** [comment]
Alternately (and this is particularly easy in stock ksp where getting to orbit is trivial), you can "configure containers" on a tank still attached to the inflatable after orbit (say the stage the fairing is attached to), and add some parts there. It is a little less realistic/role playing minus a docking port obviously.

**Comment by JonRR** [comment]
okay i will experiment with this. I should have posted earlier because i installed the latest version over-writing all the folders in the download SSTU and for some reason all my standard ships that come with KSP show now with invalid parts and also my original saved ship i was making has gone. Looks like i will have to reinstall KSP completely again. i have bigger problems than inflating hubs now!

**Comment by shadowmage45** [comment]
@JonRR -- the problems with 'missing parts' may be due to the patches in the 'SSTU-OptionalPatches' folder that delete/remove most of the stock tanks and engines.

Try installing the main SSTU folder, but -not- installing the 'SSTU-OptionalPatches' folder.

**Comment by JonRR** [comment]
you are correct, removing the Patches folder revalidates all the default ships. Not that i use any of them - but why is that? Is it a bug? And do we need the patch folder?

**Comment by JonRR** [comment]
Also does anyone know why when i updated and copied the files across i lost my saved ship (been working on it for ages) I thought they were saved in the main ships folder and i never touched that folder when i updated?

**Comment by shadowmage45** [comment]
I intentionally delete the stock parts (engines/tanks/others).  Because I think they look like crap and do not personally use them.

Do you 'need' the optional patches?  I think that should be self-evident from the name of the folder.  they are called 'OptionalPatches' for a reason  (hint:  its because they are optional....).

**Comment by shadowmage45** [comment]
Ships are stored in the 'saves' folder, inside the folder named for your specific save game in which you were working on the ship. 

You will need to copy that folder across to your new install.   (KSP/Saves/XXX -> newKSP/Saves/XXX)

**Comment by JonRR** [comment]
as a test, i tried adding a MFT tank configured as rocket parts, attached it to the lower docking port directly. Launch, orbit, try inflate and nothing happens - is there another step i'm missing or misunderstanding? I used the MFT - L lander tank

**Comment by blowfishpro** [comment]
@JonRR Are you sure you had enough `RocketParts` for that particular inflatable?

**Comment by JonRR** [comment]
not sure at all - this is all new to me, i've only got that small fuel tank / not sure how much rocket parts you need? Do i have to make it really big and somehow increase the amount of rocket parts? How would you tell prior to launch if you have enough rocket parts?

**Comment by blowfishpro** [comment]
`RocketParts` are a resource like anything else, so a larger container will have more of them and also mass more.  Each inflatable requires a different amount of `RocketParts`

The info on how much you need is in the part action menu I think (right click on the part).  It might also be in the part description.

**Comment by shadowmage45** [comment]
@blowfishpro  is correct.  You can right click on the inflatable part and it will list how many 'tons' of rocket parts are required.  It should also list this in the expanded part description in the editor parts list.

With that information you can properly size your fuel tank to make sure it has enough RocketParts onboard.  You can use the 'configure tanks' button on the fuel tank to look at the 'mass' of the rocketparts to make sure you have enough tons worth.

And a final note, when shipping the parts up to an existing station -- you don't need to ship them all at once, the inflatable will take 'partial' shipments -- just hit the 'inflate' button and it will use as many rocket parts as it can find, up to the number that it needs.

**Comment by JonRR** [comment]
ok all understood-  many thanks for all the info / hopefully i am on track now!
