### ISSUE TITLE
DOS nose textures

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#456]
The nose textures on the DOS parts do not have the beige version like the body and bottom.

**Comment by shadowmage45** [comment]
Which adapters are missing the beige textures?  Is it entirely un-selectable, or is the default assignment simply wrong?

Edit:  Configs look okay for the most part.  Is it the hub style adapters you are referring to, or all adapters in general?
(Hub-style are a known issue.... they have not yet been reworked into the new texture/recoloring system)

**Comment by Jimbodiah** [comment]
![screenshot_170530_002](https://cloud.githubusercontent.com/assets/16107012/26600483/9496ff0c-457c-11e7-87ea-51b3f3c6a458.jpg)

It is indeed on the node versions only; as this is what I always use I did not check the other ones until now.  I removed all mods and patches, but same results.



PS: When using the GUI  [>>] button to walk through the nose types, after the option "Adapter-3-4-Long" it will jump back to "Mount tank flat" instead of going to the next one. The same when at the first type "Adapter-3-1-flat" and pressing [<<] it will jump to Mount Tank flat and skip several top styles. This on COM and HAB, haven't check the other yet. It seems there are two Mount Tank Flat occurrences in the GUI list, one at the half way mark and one near the end.

**Comment by shadowmage45** [comment]
Ahh, yea, will take a look at the duplicate/double mount options -- would certainly create the problem that you are seeing.

Not quite sure how/why the HUB models got missed in the recoloring, almost looks like they are merely missing the shader assignment (textures look like the raw textures, prior to coloring being assigned).
