### ISSUE TITLE
DOS solar panels

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#457]
Solar panels on DOS modules will autoextend when you select a different version. The UI text will not update the status, and the panels will no longer respond to the UI command to open/close the panels.

**Comment by Jimbodiah** [comment]
Trying to upload logs, but github will not accept any file format. Let me know if you need them and I will send a link to you from my own server.

**Comment by blowfishpro** [comment]
@SixDasher you may be able to upload them if you zip them up first

**Comment by Jimbodiah** [comment]
nope, doesn't work either...

http://jimbodiah.com/ksp/dos_modules.zip

**Comment by shadowmage45** [comment]
As I reworked quite a bit regarding the animation handling, likely that I missed linking back up some initialization code.

If you change the panels and then launch the craft, do they work fine in the flight scene?  (just trying to narrow down where the problematic code is)

Is this on a custom part, or one of SSTUs included parts?  (Log looks like it is from a custom part... which if true... you'll need to update a few things in your configs regarding animations before things will work).  

Do the stock SSTU-DOS parts work for solar panel switching?


--From the log, pointing towards a config error on one of your customized parts:
```
ERROR: Config is for part: SSTU-ST-DOS-COM-USI (Part) is set to use RF/MFT, but neither RF nor MFT is installed, cannot update part volumes through them.  Please check your configs and/or patches for errors.
[LOG 16:53:51.491] ERROR: Animation controller was null for ID: 
[EXC 16:54:04.676] NullReferenceException
	UnityEngine.Transform.get_localRotation ()
	SSTUTools.SSTUSolarPanelDeployable.updateRetractLerp ()
	SSTUTools.SSTUSolarPanelDeployable.FixedUpdate ()

```

**Comment by Jimbodiah** [comment]
Same situation on launch platform.
![screenshot_170530_003](https://cloud.githubusercontent.com/assets/16107012/26600440/62af3d42-457c-11e7-9bac-491052c62594.jpg)

**Comment by Jimbodiah** [comment]
BTW the above is on a clean KSP + SSTU install, no other mods now just to make sure.

**Comment by shadowmage45** [comment]
Thanks for the confirmation, will take another look at these this evening to see what is going on with them.

**Comment by shadowmage45** [comment]
I can confirm the lack of panels working once the solar variant has been changed.  I'm not getting the log-spam that I was seeing in your linked log (might be different problems / parts), but the issue-as-reported is present.

Investigating now and will let you know how it goes;  if I can get a fix in place it should be available on the dev branch later this evening (or whenever it is ready).

**Comment by shadowmage45** [comment]
Looks like this was caused by an improper default animation-id setup in the updated StationCore module.  Have fixed the default in the source code, and all of the DOS modules look to be working fine.  

Cleaning up a few other errors that I spotted in the solar panel linking code, and should have both fixes available here in a short while.

**Comment by shadowmage45** [comment]
Just pushed a commit that should fix up the solar panel problems on the DOS parts.  You should mostly only need the plugin from the dev branch (direct link:  https://github.com/shadowmage45/SSTULabs/blob/dev/GameData/SSTU/Plugins/SSTUTools.dll  )

**Comment by Jimbodiah** [comment]
It works great now with the new DLL!!!

**Comment by SixDasher** [comment]
I just noticed the same issue on the inflatable HAB modules.
