### ISSUE TITLE
Solar Panels - Not working?

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#460]
Edit: looks like solar panel do not work, regardless if open or not.

**Comment by Jimbodiah** [comment]
I get Ec readings in the GUI for the panels I have tried and on the Orion SM. Any particular panel? 

BTW: I have had this happen and it turned out there was a solar eclipse happening. You get light rendered, but the sun is blocked by the moon thus giving no Ec.

**Comment by shadowmage45** [comment]
Thanks for checking on it.  Pretty sure I saw them working as well (after I fixed up the animation issues at least).

I think this was supposed to be part of the other issue (airstream shield not working), rather than its own stand-alone problem.  A bit hard to interpret the random postings on the forum sometimes....

**Comment by taterkerman** [comment]
I haven't done too much testing where it has mattered yet in 1.3 since the SSTU craft have large EC reserves.

**Comment by shadowmage45** [comment]
Should be a sub-issue/detail bit of #459, closing for general tidiness
