### ISSUE TITLE
Coloring GUI

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#461]
When changing fairing colors, changing the 2nd or 3rd color (detail etc) the selection will jump back to the first option, making it impossible to exactly change the other colors if not one of the defaults is selected.

press fairng, second color option
![sstu_colorgui1](https://cloud.githubusercontent.com/assets/16107012/26741949/cb2de114-47db-11e7-970b-11be6e48738e.jpg)

press color selection below, selection for fairing jumps to first option again by itself
![sstu_colorgui2](https://cloud.githubusercontent.com/assets/16107012/26741948/cb26d752-47db-11e7-94fa-bd0a62dc956d.jpg)

Not sure if it is only limited to fairings atm, but on most occasions the current selection stays active after changing the color preset

**Comment by Jimbodiah** [comment]
If you need the logs, let me know.

BTW, same issue on the PDC decoupler.

**Comment by shadowmage45** [comment]
Hmm... seems like it might be related to the 'gui refresh' code that I put in place (to catch updates to texture sets/models while the recolor GUI was open).

Will see about taking a look at this over the weekend; can certainly see how that would make using the recoloring work a bit painful.

**Comment by SixDasher** [comment]
Whaha, I found the color presets file. I am one happy camper now :)))
