### ISSUE TITLE
Techtree, tank sizes

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#463]
If I unlock the 6.25m tanks in Very Heavy Rocketry before the Large Volume Containment node (3.75m), the tank size will stay limited to 2.5m. 

The default techtree setup does not require all input branches to be unlocked, but the upgrades are configured in a way that all previous nodes are required?

**Comment by shadowmage45** [comment]
Hmm... I'm not exactly sure how the stock part-upgrades get applied, if it is 'order of purchase' or 'order in tech tree' or 'order in the config'.

I was under the impression that it used 'order in the config' and that the last one activated would win; so as long as larger diameters were later in the config, it wouldn't matter what order they were unlocked at in the tech tree.

Will do some investigation on this shortly to see what I can find out.

**Comment by shadowmage45** [comment]
I'm not seeing the behavior that you mention.  If I unlock VHR, and purchase the 6.25m upgrade, I get 6.25m tanks, even with LVC node un-purchased:

![screenshot5](https://cloud.githubusercontent.com/assets/1503399/26763493/f17452d2-4910-11e7-820b-e65ca0596faa.png)

![screenshot4](https://cloud.githubusercontent.com/assets/1503399/26763494/f2e7e1b0-4910-11e7-8daf-9c126f71acfc.png)

If you are playing with part-unlock costs, are you sure you purchased the upgrade for the 6.25m unlock?

**Comment by Jimbodiah** [comment]
OK, this is weird, as mine now works while I could not get it to go over 2.5m before. Maybe because I restarted KSP?

**Comment by shadowmage45** [comment]
Could be.  The 'upgrade system' hasn't received too much testing.  Even though it is a stock feature, it is not yet used in any stock parts... so there might still be some quirks with it in stock code that haven't been found yet.

Please keep an eye on this to let me know if any similar problems pop up, and I'll investigate as I can (and file a stock bug-report if needed).

**Comment by Jimbodiah** [comment]
I will see if it happens again. For now I will close this.
