### ISSUE TITLE
LMDE texture missing?

### ISSUE THREAD

**Issue by Maxzhao1999** [shadowmage45/SSTULabs#464]
I'm using the new release for KSP 1.3 but the LMDE seems to be missing textures? Is this intentional?

**Comment by shadowmage45** [comment]
Yes (intentional) -- it is a new model rather than a rescaled placeholder, and I have not yet had time to make textures for it.

**Comment by Maxzhao1999** [comment]
Good to know! Maybe this ticket will just act as a progress tracker or something. Loving the update so far!
