### ISSUE TITLE
Add Unlock/Upgrade system support for 'Tank Types' (lightweight, low/zero boiloff)

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#465]
Use stock unlock/upgrade system to limit available 'tank types' early in career modes.  Possibly add new 'semi-lightweight' tank type for earlier in career than the full 'lightweight' type.

**Comment by taterkerman** [comment]
Interesting idea. Would the unlocks correspond to the engine unlock nodes, I presume (i.e.: unlock varieties when the appropriate engines come online)?

**Comment by shadowmage45** [comment]
I haven't given any thought to the specifics of node placement yet; that is something that can be worked out given time.  I'm more worried now about figuring out what kind of code-side changes would need to be made, and how/where to specify the information (module/part vs global).  

I'm not sure they would be tied to specific engines though, as they are a bit more generic in use.  More likely they would be tied to general tech advancement; lightweight tanks would be along the composites/adv composites line (meta-materials?), low-boiloff/zero-boiloff would be located along the 'fuel systems' line, with ZBO being near the end of the tree (large-volume-containment?).  

Open to suggestions though on placement of the existing types, pretty sure they will all be sticking around,   I am already considering adding a few lower-tier lightweight tank variants to work as advancements in fuel tank technology, and perhaps even a lightweight-zero-boiloff that has increased EC requirements (less passive insulation/more active/pixie dust?; no clue on placement...).

---

I've also been considering including the 'fuel types' and/or specific resources to be unlocked through the upgrade system, and might as well consider that in this discussion as well.  I'm not sure it really adds anything though; being able to unlock a fuel for a tank is worthless without an engine to use it in, and the cost of the research for the fuel-systems for any given engine should be rolled up into the research cost of that engine.   

One final thought (as the balance to the above) is that it might be a workable idea to limit clustering of engines through upgrades. This would almost have to come through a per-engine (or family?)  unlock, as the complexity of plumbing and stability setup for say a cluster of RL10's vs a cluster of M-1's would be vastly different.  Possibly generic 'groups', such as 'small/medium/large - 1,<3,<5,<7,<=9' combinations (15 unlocks)?  It seems any attempt at anything less than being completely generic quickly multiplies out of control with the number of added unlocks/etc that would be needed.

**Comment by shadowmage45** [comment]
Have added preliminary (untested) support for upgrade/unlocks to the Tank Modifiers/Tank Type system.

Have setup the code in such a way as to do zero validation on existing values; existing craft/invalid configs will not be altered and should still work just fine, but any new craft will only be able to select the tank-types that have been unlocked.

Working through creating the actual upgrade part definitions, and then will be doing some testing to make sure the unlock methods actually work (attempting to do these without them being tied to any specific parts/modules, so that you don't need to add the upgrade/unlocks to every part that uses the volume-container system).

**Comment by Jimbodiah** [comment]
After having done tons of careers, you don't need more than 2-3 engines in early career phases. By the time I start to launch really big stuff, I have 75% of the tree unlocked already. It ltakes only 6-7 launches to get to 3.75m tanks. After doing 5-6 moon biome landings, you are basically up to the Orion capsule.

Only when you start doing RSS career are larger clusters of any interest.

**Comment by SixDasher** [comment]
What I am missing is a 1.25m decoupler in the second node of the techtree to correspond with the stock one.
