### ISSUE TITLE
ISDC and PPC coloring resets on size change

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#469]
The coloring on the interstage decouple and the probe core resets to white when you change the diameters. Upon opening the coloring GUI, the old colors are shown, but the part is white.

**Comment by shadowmage45** [comment]
I thought I had noticed something with those parts, but couldn't duplicate it when testing.

Will see if your posted steps trigger it;  should just be a material assignment fix up, once I figure out where it needs to be fixed at.
