### ISSUE TITLE
Heatshield decoupler not working

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#471]
The SSTU heatshield decoupler, when triggered, will not separate. Decouple sound is heard when triggered.

If you need clean logs let me know and I will make a dedicated SSTU install.

**Comment by Jimbodiah** [comment]
Also, the diameter size slider does not have fine graduations like the other parts; I can't make 1.50m parts etc, only one or two predefined intermediate settings.

**Comment by shadowmage45** [comment]
The decoupler is for the bottom node (not the top node like the stock heat shields).  Was that how you were using it?

Sliders -- interesting, should be easy enough to clean those up (plugin/config errors).

**Comment by Jimbodiah** [comment]
LOL, yeah, I thought it was to jettison the heat-shield. So I guess that one is working fine then, I have just been using an extra decoupler instead of the built-in one :)
