### ISSUE TITLE
NearFuture fuels

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#476]
Would it be possible to add the NF fuels to the volume container choices?    Lithium, ArgonGas, XenonGas.

**Comment by shadowmage45** [comment]
Yes, but it will need to be done through the optional patches set, as those fuels are not used in stock at all.

But seems like a good thing to do at some point, as I do use the NearFuture suite in my games, so would be good to have it fully supported in the fuel tanks.

**Comment by Jimbodiah** [comment]
I can try to make a patch for it, tried it for TAC LS but never got that to work back then :)

**Comment by shadowmage45** [comment]
Have added those resources into the existing tank-resource-adding-patch in the optional-patches setup.  

Will continue looking into more cleanup for the optional patches set, but really need time to get back into the game and play around with the recent versions of mods before much more can be done.

**Comment by Jimbodiah** [comment]
Ah, I just made a setup myself and I don't think patches alone will do it as they are also mentioned in the fueltypes.cfg

Thanks a million for adding them! Now I can deleten 30 more parts :)
