### ISSUE TITLE
Custom Shaders -- Do not work on Windows-OpenGL mode

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#477]
On windows, launching with the -force-opengl command line results in black-shaded models.

Likely cause is the Unity shader-compilation settings, need to be setup to include opengl shader variants.

**Comment by Jimbodiah** [comment]
Is OpenGL still a thing in 64-bit? I stopped using that after 1.0.5

**Comment by blowfishpro** [comment]
@SixDasher you can still use it, but if you have enough memory it's probably not necessary.  I've had better luck with `-force-d3d11` anyway

**Comment by shadowmage45** [comment]
Fixed in dev.  Apparently it is not enough to tell the Unity editor to include openGL shader variants, you ALSO have to setup the player-build-settings as if you were to be compiling for OpenGL (even though you never actually compile the build). 

Wonderful undocumented Unity crap...

But, at least it is fixed, and now I can move onto fixing other more.... real... problems.
