### ISSUE TITLE
Gamed Loading Issues

### ISSUE THREAD

**Issue by ShavedNaners** [shadowmage45/SSTULabs#478]
When loading the game it seems to go into an endless loading while trying to load SSTU/Parts/ShipCore/General/ProbeCore/SC-GEN-PPC/SSTU-SC-GEN-PPC. Using Version 0.5.34.134

[KSP.txt](https://github.com/shadowmage45/SSTULabs/files/1099986/KSP.txt) - log

**Comment by blowfishpro** [comment]
Try deleting and then re-installing Community Resource Pack.  Something seems off there.

**Comment by ShavedNaners** [comment]
I didn't have community resource pack in the data folder at the time and even with it it still failed giving the same errors in the log

I do have other mods i use alongside but i got rid of them to see if another mod was causing the issue but it doesn't work when it's just SSTU squad and module manager, and I don't think SSTU has dependencies either

**Comment by blowfishpro** [comment]
SSTU requires CommunityResourcePack.  It's failing because it's trying to find resources defined in CRP but they are missing.

**Comment by ShavedNaners** [comment]
Still even after updating it still seems to fail

**Comment by blowfishpro** [comment]
Okay, please provide an updated log as well as `GameData/ModuleManager.ConfigCache`

**Comment by ShavedNaners** [comment]
[KSP.txt](https://github.com/shadowmage45/SSTULabs/files/1100593/KSP.txt)
[ModuleManager.txt](https://github.com/shadowmage45/SSTULabs/files/1100594/ModuleManager.txt)

**Comment by blowfishpro** [comment]
Okay, I no longer see the problem I saw before, but I do see that you have duplicates of some things which might suggest that you didn't completely remove an old version of SSTU before installing the next version.  e.g. `SSTU/Data/ModelData/ModelData-SRB-A-Bodies.cfg` and  `SSTU/Parts/ShipCore/SRB/ModelData-SRB-A-Bodies.cfg` shouldn't both exist.

Try completely removing SSTU and re-downloading the last version for KSP 1.2.2 (which you are running) : 0.5.34.134, and then installing it again.  If that doesn't work, please post your updated log.

**Comment by ShavedNaners** [comment]
Thanks to seemed to fix it, i never had a previous version so that's weird, could have been another mod not sure

**Comment by shadowmage45** [comment]
Thanks for your help on getting this figured out @blowfishpro , and glad things got sorted out for you @ShavedNaners 

(sorry, have been away on a camping trip for a few days)
