### ISSUE TITLE
Modular Upper Stage - Add Longer Main Tank Option

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#479]
^^^

**Comment by blowfishpro** [comment]
Would you be willing to consider moving the default value even higher, say to 5?  I know there are legitimate concerns with texture stretching, but I don't think 2.2 is enough and a more permanent solution could take some time.

**Comment by Jimbodiah** [comment]
I still don't get why you want to stretch a MUS out that long. What is the use for it? 5x will make a crazy long tank

**Comment by shadowmage45** [comment]
I'm very much against setting a max scale that high, at least for the default configurations.  I think the 2.2 is even far too much scaling/stretching.

I've added the capability to patch in larger scaling values... so if people don't like the as-shipped configuration, they can very easily change it to suit their needs.

The proper solution is to make up a longer 'main tank' model and patch/add that into the part config.  Someone (meaning me, if I had time) merely needs to take one of the existing MFT-C tank models and strip out the flag-decal transform, re-export the mesh through Unity, and setup the new SSTU_MODEL def for it.  (Or someone needs to test if the SSTUFlagDecal module works properly when used with the MUS, in which case, the existing MFT-C tank models could simply be added along with the flag-decal module).

**Comment by blowfishpro** [comment]
@Jimbodiah try making something with RL-10s or Merlin Vacuum variants, take a look at the delta-v and burn time you're getting.  At least for me, it seems impossible to actually get decent use out of the engines with the current restrictions.

@shadowmage45 does any special setup have to be done with respect to shaders?  Also, does the MUS module currently support that kind of 'main tank' switching currently?

**Comment by Jimbodiah** [comment]
I just tried a few things in the VAB, but perhaps the problem lies elsewhere...

![sstu_mus_01](https://user-images.githubusercontent.com/16107012/28281817-9d442d06-6b28-11e7-9ab1-45e922d14bf7.jpg)

The tank on the right gives the same (±50m/2) dV as the MUS, where I have already removed the MP from the MUS. As you can see you need a much shorter MFT-A than you would a MUS. The top section on the MUS is about the same size as the MFT-A. The MFT is 0.15t lighter (on 2.2t total). Maybe you should look here instead of increasing the max length?

**Comment by shadowmage45** [comment]
@blowfishpro -- No shader stuff needed (if using an already defined and setup model), and yes the MUS already supports main tank switching.

As this is an ongoing.... problem... for some people (see the recent forum post), I'll take some time to add in a longer main tank option to the part for the next release.  (Configs and model done, just need to run the model through Unity/PartTools)  --  https://github.com/shadowmage45/SSTULabs/commit/7b1c0d59ec4dfc62c5692ddd822f28c77c2f8fdf

@Jimbodiah The split-tank variant is probably fine as far as max-length goes.  @blowfishpro  is talking specifically about the common-bulkhead variant, which would hold <2/3 the fuel of the split-tank variant of the same diameter when both are set to max-length. 

This is probably where the whole problem has arisen from -- I only use the split-tank variant; so of course the volume seemed fine to me (as the intertank and lower tank both add additional volume).  Thinking more on it though, I could definitely see problems with the shorter main-tank on the common-bulkhead variant.  The pre-rework/merge MUS parts actually had two separate 'upper tank' models; a shorter one used for the split-tank, and a longer one used for the common-bulkhead.

**Comment by Jimbodiah** [comment]
I thought the CB was removed and the MFT would be reworked at some point to hold rcs... OK, my bad then, I thought they meant them default HUS.

**Comment by shadowmage45** [comment]
CB wasn't removed entirely, merely merged with the ST into a single MUS part with a GUI based toggle.

MFT's with RCS -- still trying to find a 'clean' method to set it up, though I'm pretty close with the existing MUS-RCS code/handling.

**Comment by Jimbodiah** [comment]
One day, SSTU will consist of a single part that can be turned into anything, of any size and any color :)

**Comment by Jimbodiah** [comment]
You could go back to two seperate parts?

**Comment by shadowmage45** [comment]
No real reason to go back to separate parts.  The current setup works fine, some people just want longer tanks (which is doable, just nothing I had previously considered).

**Comment by shadowmage45** [comment]
New 'long' upper tank option is available:

Max length of short tank:
![screenshot0](https://user-images.githubusercontent.com/1503399/28293154-e1cea03c-6b0f-11e7-86e4-761525d7e06f.png)


Max length of long tank:
![screenshot1](https://user-images.githubusercontent.com/1503399/28293157-e4636e72-6b0f-11e7-864a-496e3eb613d2.png)


Anything longer and it begins looking like a noodle....

**Comment by blowfishpro** [comment]
Yes, I think that's quite sufficient for an upper stage ;)

Thanks for the quick turnaround!

**Comment by shadowmage45** [comment]
No worries, it was a bit of an omission that needed to be cleaned up.  What is shown above should all be available and working in the current dev branch if you wanted to give it a spin.

I might clean up the min/max scale a bit so that there is less overlap between the two tank lengths, and considering adding a 'short' tank variant as well to minimize texture stretching (squashing..) on the really short configurations. 

To finish off the set, I should probably add short/long variants for the lower tank in the split-tank setup as well; both for keeping ratios between tanks, and for allowing configurations of different upper/lower ratios.

**Comment by acolangelo** [comment]
That looks fantastic, @shadowmage45. I’ll give it a spin tonight, too, since I was prodding over in the forum. Sorry I missed this issue earlier—I failed to check closed issues.

**Comment by shadowmage45** [comment]
:)  I don't really expect you to check the closed issues; was just linking it on the forum to save myself some retyping of the discussion already here.

**Comment by blowfishpro** [comment]
New size works well for me!

**Comment by acolangelo** [comment]
Same here—fantastic work!

**Comment by Jimbodiah** [comment]
Freud would say you have phallic fixations.
