### ISSUE TITLE
Fairings in techtree

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#481]
The modular fairings have the same issues in the techtree as the decouplers did, as in my new career I am limited to 1.50m despite having unlocked the nodes for 3.125m tanks.

Are you okay with it if I do a PR with a new setup? It will have the same sizes as the decouplers in the same node level, and also move it to the aerodynamics section instead of construction (decouplers) ?

**Comment by Jimbodiah** [comment]
Ah, I see PF defines the sizes differently to SSTU, cq negating what is entered in SSTU. 

There is a common.cg file that defines the sizes per node. I will try to patch PF to match SSTU sizes so it will not limit SSTU.

**Comment by shadowmage45** [comment]
I'll take a look at the fairing upgrade nodes in SSTU to make sure they are available with the same diameter as the tanks, as well as possibly adjusting where the unlocks are located a bit.

On the PF front:
To be honest... I'm not really sure what is going on with the PF compat patches, or how Jose even got it all working in the first place using the SSTU base models.  I'm amazed that it is still working as those patches haven't been touched in a long time.
If you have any suggestions on things that need to be changed in the SSTU-PF patches, feel free to chime in; I don't personally use PF, so not familiar with its setup or balancing.

**Comment by SixDasher** [comment]
I can do the SSTU part via a PR, running it already on my save. I've manually edited the PF file with the SSTU nodes, trying to figure out how to MM patch it though as it is specified in a seperate genetic cfg file.

**Comment by SixDasher** [comment]
I've put up the changes, up to you if you will accept/change them.  I've moved the fairings into the aerodynamics branch of the techtree, thus requiring a seperate research line from decouplers and bringing it in-line with stock and PF parts.

The probecore and heatshielf also use the FR upgrades, so I updated their sizes to match those of the fairings. Maybe it might be an idea to use a different upgrade definition so they stay in the original techtree branch? If you want I can make those.

**Comment by Jimbodiah** [comment]
OK, I'm done...  Fairings, probecores and heatshield now in their respective tree nodes to match tank sizes and also match appropriate tree branches (hietshield with stock heatshields etc).

**Comment by Jimbodiah** [comment]
Here is the techtree with all the changes I made. Color coded for easy viewing :) The MFT was not changed, just there to show it's path in the tree as a reference.

![sstu_upgrades](https://user-images.githubusercontent.com/16107012/28119434-262d55b0-6715-11e7-9ce8-b8d9c8b6a955.jpg)
