### ISSUE TITLE
x.137  NF Propulsion fuels not showing up

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#495]
The new fuels are not showing up. Want me to investigate and PR for the next release?

**Comment by shadowmage45** [comment]
They are only added if you install the 'SSTU-OptionalPatches' folder from the repository (no longer included in the download).  I probably should have stated that in the patch notes (might also require MKS / other USI mods...)

What might be best in the long run would be to split off the NearFuture fuels into a proper NF patch set that only runs when NF-XXX is installed.

**Comment by Jimbodiah** [comment]
Thanks, I'll have a look.

I'll check why I couldn't get that to work before and see if I can make a patch for it.

**Comment by Jimbodiah** [comment]
Yeah, so I'm testing NF fuels on a bare sstu install and wondering why the fuels aren't showing up... might be nice to also install NF Propulsion. OMG, my brain on drugs.

If I figure this patch out I will also make one for TAC-LS and DeepFreeze.

**Comment by Jimbodiah** [comment]
NF Prop is on PR. Just looking at the fuel volume though, as that needs to be fixed. Will PR that when I figure it out.
