### ISSUE TITLE
TechLimits.cfg

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#497]
Where is this file referenced? I notice it has all the techtree limits for all the sizes, but can't figure where these are used.

BTW: Can I label issues as questions etc, or only you?

**Comment by shadowmage45** [comment]
Hmm... pretty sure that file is deprecated and not used anymore.  Should be able to be safely removed.

Pretty sure only repository admins can flag questions/etc (owners, authorized contributors).

**Comment by Jimbodiah** [comment]
OK, thanks. I did not see any interference from it while changing the upgrade paths, so was wondering about it's function and possible problems it may cause. I can try to delete it here and see what happens.

**Comment by shadowmage45** [comment]
Should be safe to delete -- all of the tech limits stuff has moved to the stock PartUpgrade system.  I think the file was just left there for reference, and then forgotten about :)

**Comment by shadowmage45** [comment]
Removing the file in dev repo; don't worry about a PR/etc.
