### ISSUE TITLE
LC2 - ENG wrong orientation of flames

### ISSUE THREAD

**Issue by riocrokite** [shadowmage45/SSTULabs#5]
![l2-eng](https://cloud.githubusercontent.com/assets/9766897/9653725/e110ed80-5225-11e5-89bc-257360b10687.png)

**Comment by shadowmage45** [comment]
:)

I must have rotated something in blender, and unity probably did its normal stupidity and didn't update the child transforms properly.

Will keep this in mind as I am going over and re-exporting the engines while updating them to a new emissive module.

**Comment by shadowmage45** [comment]
Fixed in dev; will be available with the next update.
