### ISSUE TITLE
SC-D initial testing

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#500]
Just tried it out, look cool already ! :)

- there are 3600 units of aerozine/nto in the SM, should this be so much (2400 m/s dV)?
- when using the LES it blows up the SM, probably the flame damage is turned on?
- the main chutes of the capsule keep the pod tilted a little like it is with drogue chutes, not sure if this was intended?
- when splashed down the capsule keeps sinking
- the SM engine flames are huge and too far away from the nozzles

Will test more tomorrow.

**Comment by shadowmage45** [comment]
It is only intended for testing in the editor for geometry / physical design purposes.

I'm not yet doing anything about its functions/balance/etc, and it is certainly not intended to be used or tested in the flight scene.

Basically right now I'm making sure that it fits in the adapters, attach-node positions are setup properly, and that there are no ugly seams or clipping when the craft is put together.

**Comment by Jimbodiah** [comment]
Hahaha, so I made a false start. It works pretty well for a clay model :)
