### ISSUE TITLE
Installation Issue.

### ISSUE THREAD

**Issue by KamikazeKricket** [shadowmage45/SSTULabs#513]
Hello, 

First of all I'd like to say that these mods are great and I really enjoy playing with them. However since I installed the new update, I can't play with them. All the tanks on the lander pods have disappeared, so have most of the Pods as well. I think the problem is mainly how I'm installing them into the game. 

If someone could tell me where to put everything, that'd be great. I can't remember how I did it the first time, and now I've managed to mess things up.

Thanks in advance.

**Comment by Jimbodiah** [comment]
All you need is the SSTU x.137 download from github, and make sure you also have Community Resource Pack

Your bare GameData folder should look like this for SSTU:

/CommunityResourcePack/
/SSTU/
/KSPWheel/
/ModuleManager2.8.1.dll

**Comment by shadowmage45** [comment]
@Jimbodiah's instructions are pretty much the basics of it.

If that doesn't work out for you, could you please attach/upload/post a screenshot of your game-data folder?

If that doesn't work out / lead anywhere, please upload your log files (KSP.log), as they might also have some information in them on what is messed up.

**Comment by KamikazeKricket** [comment]
I got it working now. It seems it was how I was putting some wrong files in the wrong places. The only issue now is that the new command module added doesn't have any textures. I don't know if thats me, or if its just because its a work in progress. 

Thanks for the quick response guys, and once again nice work.

**Comment by Jimbodiah** [comment]
The V modules have no textures yet, it is WIP

**Comment by shadowmage45** [comment]
That is correct -- the SC-V (VA) parts are un-textured currently.  They should be bright white :)

Sounds like you got it all sorted out, so closing this for now.
