### ISSUE TITLE
Xenon and Ore in MFT tanks

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#516]
Can I put Xenon and Ore as default in all the MFT tanks?  I am getting some issues where I add Xenon in the NF patch, but some tanks already seem to have it (not all) which causes exceptions/problems.

**Comment by shadowmage45** [comment]
Sure; stock resources might as well be supported in the stock configuration.

I always forget about them as I have them added through other patches in my personal games (the USI patch set).

**Comment by Jimbodiah** [comment]
Yeah, you have to keep track of where it is all defined, you can lose track quite easily.

I'l change the MFTs to hold them.

**Comment by Jimbodiah** [comment]
There is no SC-MFT-A.cfg or SC-MFT-D.cfg in the Master or Dev versions, is there a reason for that?

**Comment by shadowmage45** [comment]
Its a derp in Github regarding same-named folders with different capitalization...

https://github.com/shadowmage45/SSTULabs/blob/dev/GameData/SSTU/Parts/ShipCore/tanks/SC-MFT-A.cfg

They are in the lower-case 'tanks' folder at the bottom of the Parts/ folder list.

**Comment by Jimbodiah** [comment]
Dafuq. How did I even miss that. Thanks. 

Want me to copy them to the Tanks folder (and same with engines/Engines)?

**Comment by shadowmage45** [comment]
I think I'm going to have to do some low-level file manipulation to get them to read as if they were in the same directory.  Probably something like delete them from the repo, commit the changes, and then re-add them in.

**Comment by Jimbodiah** [comment]
I was thinking just make a new file in the correct folder and just copy-paste the cfg code into the new file.

**Comment by shadowmage45** [comment]
There isn't two folders though (on windows);  when I open it in windows explorer/etc, there is only a single 'Tanks' folder (uppercase 'T').

Hence the need for the workaround :)

**Comment by Jimbodiah** [comment]
You are good with work-arounds, I'm not worried ;)

{backs up savegames}
