### ISSUE TITLE
Upcoming Major Change - Optional docking port removal

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#522]
Due to ongoing (and seemingly impossible) to debug issues with the station-core selectable docking ports, it is seeming very likely that they should be removed in the interest of long-term stability.

This will increase part-count quite a bit on large modular-designed stations.  

Part of this increase in part-count can be mitigated by the upcoming 'DockingPortToggle' modlet that I will be releasing in the upcoming days/weeks.  It will add a toggle-able enable/disable to the stock docking ports (and probably SSTU by default?) that will essentially disable the docking ports per-tick search/lookup functionality which has been shown to be very performance intensive.  ( https://github.com/shadowmage45/DockingPortToggle )

----

The main problem that is going to hold this back from immediate implementation is the craft/part breakage that will occur.  Models and modules will be removed from existing craft, and they may be left with no way to undock.

Will be posting a bit of info on the forums for warning/feedback/discussion.  

----

If I can get some assistance in tracking down the root cause of the docking port issues (and a means to reliably reproduce the problems), and finally fix said problems, I will consider keeping the functionality in place as it is.

This would require a set of stock/sstu save game files in a pre- and post- error condition, with an explicit set of steps to trigger the error.    (The post-error save games are easy to come by; its the pre-error games -and having the problem reproducible- that it the difficult part)

**Comment by blowfishpro** [comment]
Have there been any docking port issues that could be reliably reproduced? (and still outstanding)

**Comment by shadowmage45** [comment]
Reliable as in 'reliable steps to reproduce the problem at will'?  No.  At least not that anyone has been able to provide me, or that I've been able to find myself.

Reliable as in 'keeps popping up all the time'?  Yes.  About one-in-five (maybe 1/10) from my experiences.  I can trigger the problem with < an hour of testing, but cannot actively reproduce it at will.

I've had the same craft give problems on one launch, and then had no problems after a revert, and then problems again on the next revert.  Flying almost the exact same path and taking the same steps (launch, orbit, rv, dock, move resources/crew, undock); sometimes the problem pops up, sometimes it doesn't.

Quite frustrating....

**Comment by Jimbodiah** [comment]
I had it once or twice now with DOS and COS units, but not reproduce-able. It just happens for some reason and will not go away unless you remove the parts in question fro the game and send up a new craft.

Right now I only place ports as separate parts and have had no issues.

**Comment by shadowmage45** [comment]
>> It just happens for some reason and will not go away unless you remove the parts in question fro the game and send up a new craft.

That is the real problem.  The fact that it won't go away without either manually editing the save-file (dangerous, error prone), or completely replacing both docked craft.

**Comment by taterkerman** [comment]
Yeah, I would have reported any issues if I had seen it again, and I have not. I cannot seem to figure out any reliable way to reproduce it.

Question: I assume people are seeing this in sandbox as well as career... I usually do play throughs in career to see if anything appears under those circumstances. Is there a chance that somehow part upgrades are related if it occurs only in career? (no idea, just spitballing)

**Comment by shadowmage45** [comment]
Possible, but unlikely, that the upgrades would interfere.

The code only checks the upgrades when it is populating the GUI list.  If a craft were saved with a docking port that was unavailable yet in the career game, it should still load in just fine with that docking port (but if you tried to alter it in the editor, you would be limited to the unlocked options).
