### ISSUE TITLE
Stand-alone rcs nozzles from Orion SM

### ISSUE THREAD

**Issue by Nightside101010** [shadowmage45/SSTULabs#529]
I really like the long RCS nozzles on the Orion service module. Would it be possible to have the angled and linear nozzles as stand alone parts?

**Comment by shadowmage45** [comment]
Not easily.

The models currently use the same texture sheet as the Orion-SM, and include pre-baked AO.  Meaning they cannot easily be split off without creating a full new 1024x texture just for two RCS ports (huge waste of memory and time).

Possibly in the near (or far) future, when I add recoloring support to the SM, it might be possible to break off the RCS (and solar panel) geometry into distinct models.   The recoloring shader uses a separate AO texture, so it would be easy to remove it for the stand-alone ports/panels.

**Comment by Jimbodiah** [comment]
It could make a cool DreamChaser variant, minus the OP engine that came with the mod.

**Comment by shadowmage45** [comment]
Now that I've reworked the SC pods to use the new recoloring system (with separate AO texture), this request becomes much easier to fulfill.

Basically now I just need to find time to split the meshes off, run them through Unity, and write-up the configs for them (shader setup, standard part configs).

Will see about getting these added in for the next release.  (As well as potentially the orion and soyuz solar panels as stand-alone parts)
