### ISSUE TITLE
Farscape?

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#530]
omg omg omg..  Whaddat?  Is that the revival of the old Farscape ship mod? Oooooohhhhh, please please please....

**Comment by shadowmage45** [comment]
Yes, but not by me; I'm just helping get the wheels working.

https://github.com/linuxgurugamer/farscape

(big Farscape fan myself, even though I don't believe such things belong in standard KSP; but could be good for some very heavily modded setups/near/far-future tech)
