### ISSUE TITLE
Docking port weight

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#536]
I just noticed the 1.25m docking port weighs 0.5t; seems kind of heavy perhaps? The stock ones and from other mods tend to be around 0.1-0.15t

**Comment by taterkerman** [comment]
SSTU ports also have a chute. The XL stock chute is 0.3.

**Comment by Jimbodiah** [comment]
Ah, never used those...  I'll patch up one without the chutes for my own gameplay. I have small tugs where the mass of the port makes it lobsided and I can't center my rcs (yes, OCD).

**Comment by shadowmage45** [comment]
^^ what @taterkerman says is the reason for the extra mass (integrated parachutes, docking lights, docking camera).

I've actually been wanting to remove the integrated chutes/lights/cameras for awhile now (possibly as a new part).  They add tons of polys to models that use the docking ports that already have their own integrated chutes/lights/etc (SC-A/B/C/Etc).

**Comment by Jimbodiah** [comment]
Wait, what?! Cameras?

I tend not to use these for chutes as they can not be repacked by engineers, and all the re-entry pods have chutes on them.

**Comment by shadowmage45** [comment]
Camera **Transforms**.  They do nothing by themselves.  At one point there was a patch for RPM/etc that added them as usable external cameras.  
No clue if that patch has made it through the various upgrades (don't personally use RPM, or even IVAs, so have not tested in recent months).

Chute repacking -- Hmm... good point.  Want to open up a separate issue ticket on it, and I'll see about getting that feature into one of the next releases?  Seems like a good idea to at least have equivalent functionality to stock parachutes in that regard.
