### ISSUE TITLE
Parachute repack by engineer

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#540]
As requested...

**Comment by shadowmage45** [comment]
Thanks for helping me stay organized :)

Will take a look at this for a near-future release.  Cannot guarantee it'll be done for the -next- release, but will be done soon.

**Comment by shadowmage45** [comment]
Requirements:
* Config field to determine if the chutes on a part can be repacked.
* Use game-settings to determine if engineer is required (sandbox vs career/tech)
* Can repack from inside vessel, or requires engineer to be on EVA?

Code:
* On chute repack -- how to reset model / recreate the jettisoned meshes?
  * On jettison, clone the meshes, disable original; jettison the clones.
  * On repack, simply re-enable the originals.
* New button for 'repack', only active when chutes are cut. 
  * Needs to be linked into initialization code for initial state.  
  * Needs to be linked into state-changes to determine when to activate/deactivate the button.

Would-be-nice:
* Rework module to use separate modules for each set of drogues and mains.  Would greatly simplify the module, needing to only store data for that specific setup.
  * Would require some interconnects between parts with multiple parachute modules?
    * Is it actually a problem if someone wants to deploy both drogues and mains at the same time?
    * How important is it to have replica-like functioning for parts with drogue/main chute deploy sequences?  - at least somewhat important, would be nice to still ensure that the Apollo/Orion setups function as intended regarding cap jettison.
  * **Would be a craft-breaking change**
    * Parts would need to be reworked with separate module configs.
    * Existing parts would lose their persistent state regarding chute deployment/etc.
