### ISSUE TITLE
Some engines' minimum and default mounts are too large

### ISSUE THREAD

**Issue by MikeOnTea** [shadowmage45/SSTULabs#547]
Both LR-81s' minimum and default mount sizes in single-layout mode are too large. What's weird is, that their default and minimum mount sizes become _smaller_ when switching from single to dual-layout mode.

The following engines also have a too large minimum mount size in single-layout mode, their default value is also a little on the high side: LMAE, LMDE, RD 0110 and the 3 NRV engines.
When you switch to dual-layout mode for these engines, i think the default and minimum sizes stay the same. So, while the code to determine sizes for dual-layout and up seems to be quite good, the single-layout case looks to be a bit off for these engines.

That said, are the sizes dependent on the mount style? That doesn't seem to be the case on my system, and while some minimum values look ok for the S-IVB style which takes quite some space, the other mount styles allow for far smaller mount sizes and thus at least the minimum values should be lower.

Attached are 2 sample screenshots:
LR-81's default(3.125m) mount:
![default_lr-81](https://user-images.githubusercontent.com/11480934/29753865-6d849cbe-8b7a-11e7-8b95-aa6c3124fad5.png)
LR-81's minimum(1.875m) mount:
![minimum_lr-81](https://user-images.githubusercontent.com/11480934/29753866-6d87bb74-8b7a-11e7-9262-9d38d615e57c.png)

**Comment by shadowmage45** [comment]
Note -- different mounts have different minimum sizes.  And certainly different sizes with different layouts -- you can only compare a mount for a given layout with itself, not with other mounts for the same layout, or even the same mount for different layouts.

What is the default and min size for the same mount for that engines?

Mostly I'm just not seeing what the problem is -- both of those pics look fine to me?

**Comment by shadowmage45** [comment]
Re: LR-81-8048/8096 -- looks like the 8048 might be set to use the same diameter for mount calculations as the 80496 (they both have the same mounting diameter specified in configs).  I'll take a look at the model/geometry to see if this all lines up.

What other engines appear to have incorrect default/min sizes?  (more specifically, which engines + mount + layout combinations?)

I'll be adding in some debug code to dump/output the list of engine/mount/layout sizing parameters.  This should at least let me see what combinations might potentially have problems, and compare the output values vs. the goemetry to see where the error is (config/code/model setup).

**Comment by MikeOnTea** [comment]
Well, as i noted, the mount does _not_ make a difference here, even with mount "none", i cannot get a smaller mount than 1.875m for the single-layout. I had to use the double-layout to be able to get a 1.25m mount for that engine.
Maybe that's one part of the problem already, that different mounts don't change the minimum size?
About the first pic, well, it's just the default mount, but i find it a little odd to have such a huge default for such a small engine (and as with the minimum mount, changing from single-layout to dual-layout makes the default mount _smaller_ instead of larger which doesn't make sense, so i suspect something's a bit weird here).
About the second pic, i cannot make the mount smaller than that (in single-layout), even though there's _plenty_ of space around the engine, the correct minimum would probably be around 0.625m (clips a tiny bit)-0.9375m.

**Comment by shadowmage45** [comment]
Thanks for the explanations, that makes a bit more sense.

On the first pic -- it is intentional.  The 'default mount' chosen is the S-IVB mount, which is the default for all 'upper stage' engines in single-engine configuration.  If you notice, there is very little wiggle room as far as making that mount smaller -- where the engine attaches will start clipping if made much smaller.  You are free to select a different mount if you would like a smaller outer diameter (the generic and S-II mounts would both allow for smaller outer diameters while not clipping).  If the other mounts (generic/S-II) are not allowing you to select a smaller size even though it looks like it should, that would point to an error in config for either the engine or mount.

On the second -- yep, that would appear to be an error (not sure where yet, need to run some tests/debug on it).  You should be able to get that mount down to possibly ~0.625m, but at least 1.25m.  The minimum size should be on a per-mount basis, as different mounts have different mounting areas (and mounting-attach-ratios).

**Comment by MikeOnTea** [comment]
Ah! I Just noticed that the S-IVB mount automatically changes to the S-II mount when you change from single-engine-layout to multiple engines, which explains why the dual-engine-layout allows a smaller mount diameter.
This is probably good news, as that means the only real issue is that changing mounts manually does not change/update the default and minimum mount sizes.

So, to rephrase that once again, when i change engine layout to dual-engine SSTU changes the mount to S-II, it updates the minimum and default mount diameters to 1.25m/2.5m, but when i keep single-engine layout and change the mount manually from S-IVB to S-II, the minimum and default mount diameters stay at 3.125m/1.875m.

This is true for all engines, i think, so the issue is not actually LR-81 specific.

Sorry for the confusion.

**Comment by shadowmage45** [comment]
I believe the behavior of the module is setup to 'preserve user selected 'mount diameter' unless it is outside of the min/max range of the newly selected mount'.  This is separate from the 'default' (which only applies when selecting a new layout), and also separate from the 'min' (which only applies when attempting to change the size manually).

So, to recap, the desired/expected/intended behavior is;

Changing layout = It auto selects the default mount for the layout, and sets the size to the default size for that layout/mount combo.  The min and max size should be setup for that specific layout/mount combination.

Changing mount = It keeps the selected diameter if possible, else sets it to the closest of min/max to the current diameter.  The min and max size should be setup for that specific layout/mount combination.

Changing size = it should allow you to change size within the min/max range for that given layout/mount combination.

Will verify this when I'm doing testing though.

**Comment by shadowmage45** [comment]
Can confirm the issue of the min size not being correct when changing to a new mount within a layout.  Thanks for catching that :)

Looks like it was missing some code to update the min/max for the layout.  Have added it in, and am testing it out now.  

It appears to work at on first tests; the new minimum size is updated on mount selection change properly.
![screenshot2](https://user-images.githubusercontent.com/1503399/29798764-5edf2c2c-8c1c-11e7-9c56-4970a799476e.png)

Going to give it a bit more working over to make sure it didn't expose any other errors, but so far it is working as the code would suggest it should (so, as intended mostly).  
* Keeps the current diameter selection when changing mounts
  * If current diameter is outside the min/max of the new mount, set it to the closest of min/max for the new mount.
* Uses the pre-calculated/preset 'default diameter' for the mount when changing layouts

**Comment by MikeOnTea** [comment]
Thanks for fixing this so quickly! Looks very good on the screenshot. :)
