### ISSUE TITLE
Installation Issue (Again)

### ISSUE THREAD

**Issue by KamikazeKricket** [shadowmage45/SSTULabs#548]
So,

I'm on a different computer and I had to get Kerbal Space Program and all my mods again. This being my favorite mod, it had to be first. 

Well, I forgot where I need to put all the files. Could someone please tell me where I need to put the folders from the mod download, nothing I'm trying seems to work properly. 

Thanks for your time.

Also, I recommend a little explanation on how to install this mod. No offense, I absolutely love this mod and the work you've done, but it's the only one where I can't figure out how to install it.

**Comment by taterkerman** [comment]
The CommunityResourcePack, KSPWheel, and SSTU folders go inside the GameData directory, along with the ModuleManager dll if you don't have one installed.

**Comment by KamikazeKricket** [comment]
Well it seems everything is in place for the most part now except for the Soyuz launch abort system, its just staying at a grey texture.

**Comment by taterkerman** [comment]
It's gray because the recoloring is being added, allowing you to make it any color you wish. Likely just partially done in this pre-release. Its fine.

**Comment by shadowmage45** [comment]
Ahh, yes, I may have missed the texture/defs for the LAS/BPC.

I'll make note of it and get it fixed up for the next release.

**Comment by shadowmage45** [comment]
Good news on this front -- future releases will include installation instructions (a simple .txt file).  Will also have a slightly more intuitive packaging format.

Still working on figuring out why the SC-A-BPC is untextured, the configs all look to be in place, so is likely an improperly specified transform name or similar.
