### ISSUE TITLE
SC-B-SM - Remove secondary engine module / implement MultiModeEngine module

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#55]
As it is, the current implementation only confuses MJ/KER when you have only a single engine enabled.

Also, there is little need for redundant engines in KSP.

Suggestions include repurposing the secondary engines as powerful RCS (would require recompiling model with the transform orientations rotated properly).

**Comment by blowfishpro** [comment]
Is there any data on why the actual Orion is planned to have two sets of engines?  I can't find any.

**Comment by shadowmage45** [comment]
I believe it was just for redundancy, though I can't seem to find any information on it at the moment either (all source just list 'auxiliary propulsion system', without justification or rationalization for it).
