### ISSUE TITLE
Length and thrust calculation of SRBs broken in 0.6.36.138

### ISSUE THREAD

**Issue by MikeOnTea** [shadowmage45/SSTULabs#550]
In 0.6.36.138, it looks like the length calculation doesn't respect the diameter of SRBs anymore, thus boosters with small diameters are too long and have too low thrust to push that higher weight.

**Comment by shadowmage45** [comment]
Interesting... must have broken some of the volume/thrust calculation code when working on the upper-stage SRBs.  Looking into this now, will let you know what I find out.

**Comment by shadowmage45** [comment]
Ahh, this actually appears to be due to a miscalculation when setting up the model scales; at some diameters they get stretched vertically, but the thrust calculation is not including this volume.  Testing out a fix now, and will see where this leads.

**Comment by shadowmage45** [comment]
Seems to be working properly again, thanks for pointing this out.

![screenshot0](https://user-images.githubusercontent.com/1503399/29799349-485e5faa-8c20-11e7-915e-ac1f4ff35578.png)

![screenshot1](https://user-images.githubusercontent.com/1503399/29799350-4a859e92-8c20-11e7-8c04-c52226becadc.png)
