### ISSUE TITLE
RealFuels Compatibility - may be broken at the moment

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#551]
Report from the forums:

( https://forum.kerbalspaceprogram.com/index.php?/topic/117090-wip13-sstulabs-low-part-count-solutions-orbiters-landers-lifters-dev-thread-08-28-17/&do=findComment&comment=3157170 )

> I have just installed SSTU mod and using Real Fuel too and I have the following bug.
>
> When using the SSTU - SC TANK - MFT-A - Standard Tank amount of fuel in the tank will stay at 2kL liter instead of increasing when size or diameter is increased. 
>
> Do you know why is that? Am I missing something? 
>
> EDIT: Btw, same happens with the Spherical Tank...

**Comment by blowfishpro** [comment]
I'll try to see if I have time to check in the next couple of days.

**Comment by shadowmage45** [comment]
Hmm... did quick test with latest RealFuels, and everything seems to be working fine.  The volume in the RF GUI even updates immediately on diameter changes.

**Comment by blowfishpro** [comment]
Yeah, everything seems fine to me as well

**Comment by shadowmage45** [comment]
I'm thinking that the reported problems were due to a mod / game version mismatch of some sort, sounded like he was still on 1.2.2.  Will post on the forums to see if anyone else is having problems / has more info on it, and if nothing turns up, will call this one 'solved'...
