### ISSUE TITLE
KIS 1.6 Integration Code likely broken 

### ISSUE THREAD

**Issue by pigzippa47** [shadowmage45/SSTULabs#557]
Bumping from KSP Forum:

When I added a MFT-A to my craft, it threw a "NullReferenceException: Object Reference Not set to an instance of an object" error, and the right click GUI menus on ALL parts stopped working.

I have noted that I can use the right click GUIs on other parts (including other SSTU parts, such as the MFT-S) before the MFT-A is added, and can reset this issue by leaving the VAB and returning.  
It occurs in both the VAB and SPH.

The MFT-S, MFT-D, and MFT-L have no issues and function normally. 

I have not experienced this bug with any other circumstance than adding and right-clicking the SSTU MFT-A.

Shadowmage interpreted Log Files to mean that the KIS Integration Code is Likely Broken.

[Mods](https://drive.google.com/file/d/0B5lyDs-DWz4ZRFd1eDFXWi1HNlE/view?usp=sharing)
[KSP Log](https://drive.google.com/file/d/0B5lyDs-DWz4ZeERsd0ozNXpiTk0/view?usp=sharing)
[Output Log](https://drive.google.com/file/d/0B5lyDs-DWz4ZY0NhQ3d0amFrTkE/view?usp=sharing)

**Comment by shadowmage45** [comment]
Thanks for filing the report (and bigger thanks for including the logs!).

I should hopefully get a chance to take a look at this sometime this week, and hope to have it fixed for the next release (current ETA - 9-24-17).

**Comment by shadowmage45** [comment]
I've fixed the code up so that it should no longer crash.

Unfortunately, due to some API/internal code changes in KIS, it does not appear that I can dynamically adjust KIS inventory volume any longer -- so I will likely be completely removing the KIS integration in the upcoming release.

**Comment by shadowmage45** [comment]
After a bit more investigation I've gotten the KIS inventory integration code working as well as it was before.  There are still other incompatibilities between many SSTU parts and KIS, but at least you can use the MFT fuel tanks as giant part storage again.
