### ISSUE TITLE
Structural tanks are too heavy

### ISSUE THREAD

**Issue by MikeOnTea** [shadowmage45/SSTULabs#564]
Structural tanks are a great idea. Yet currently they're too heavy, when you compare them with the stock structural fuselage or 2.5m service bays, which both are less than 1/3 the weight of a similarly sized structural container tank. Even an empty standard tank is lighter than the structural container.

I've tried a massModifier of 0.3 for structural tanks, which looks better balanced with regards to stock:
The stock 1.25m structural fuselage weights 100kg, the structural tank of equal size 103kg.
The stock 2.5m service bay is 300kg, the structural tank of equal size 287kg.

**Comment by taterkerman** [comment]
Yeah, but are the stock parts too light? My problem in stock is that it's too easy to get stuff to space, not that I need to buy a few kg.

**Comment by MikeOnTea** [comment]
No idea if the stock fuselages/service bays are too light, but what i heard is that the stock tanks are actually too heavy compared to real life when related to their fuel amount. Most engines are too heavy too, right?
So i guess the solution to being too easy to get to space is to use a larger scale system.
In any case, _if_ those stock parts really are too light, we should create an optional patch to rebalance them, because right now i would just stack service bays or use stock fuselages to get structural containers.

Edit: Just to add, other stock parts like cargo bays are also considerably lighter than structural containers of similar size.

**Comment by taterkerman** [comment]
I'd not stack any stock parts, ever, because they are far too ugly. I suppose I'd rather have them a realistic dry mass (and I have no idea if the current versions match a realistic expectation in that regard). I tend to use structural tanks only in places where I imagine them to be crewed sections, so I assume some amount of additional mass due to that. YMMV.

**Comment by Pappystein** [comment]
Food for thought:
Structural Fuselage is a 1.25m MONOCOQUE structure... Like an Airplane fuselage.  IE the skin is the primary strength-bearer.   MikeOnTea, you are comparing an AIRCRAFT part with a spacecraft part.  The closest comparison would be a single fuel balloon tank since it too is a monocoque structure.  By logic the baloon tank should be slightly heaver than the aircraft fuselage...    A two fuel balloon tank (like Kerolox or Hydrolox) would be heavier yet.

**Comment by MikeOnTea** [comment]
Well, first of all, i guess the "aircraft" parts in the game are actually spaceplane parts/spaceplane safe, and can just aswell be used on rockets (though i admit i don't have much experience with them). Then, i did not only compare it to the fuselage, but also to service bays and also to the space-shuttle-like cargo bays, although i didn't provide numbers for the latter. Now, i agree that fuel tanks should be heavier, but this issue is not about fuel tanks, but about the "structural tanks", structure-only parts with no further usage, no inner balloon for fuel etc. Those probably can be considered monocoque aswell!?

**Comment by shadowmage45** [comment]
Structural tanks will be heavier than a standard 'empty' fuel tank, as they are intended to have -much- higher crash tolerance (~60ms vs ~15ms).  As such I would say that twice the weight of an empty fuel tank would seem about appropriate (which is I believe where I balanced them).  Was not intended as a lightweight part, but as a heavy-duty structural part.  If it is not close to that balance, please let me know and I will investigate a bit.

One possibility might be to add a 'lightweight structural' tank type, that -is- lightweight, but has lower crash tolerance (~6m/s).  Would weight slightly less than an empty fuel tank, but have poor impact and heat tolerance.

**Comment by MikeOnTea** [comment]
Out of curiosity, what's the use case for such a high crash tolerance?

The stock fuselage has a crash tolerance of 10m/s and heat tolerance of 2000k, the service bays have higher tolerances for both values, but 10m/s and 2000k would be fine in my eyes, as i would want it to survive a reentry (with a same-size heatshield attached) and landing with enough parachutes.

One could go as far and make 3 options, a really lightweight that won't survive reentry, a medium one with 10m/s / ~2000k that will survive reentry with a heatshield attached, and that heavy duty one, not sure though if that's worth it.

**Comment by taterkerman** [comment]
Stock balance in that regard is kooky, too (like a lot of stock). Highest apollo LEM sink rate at landing was ~4 ft/s (1.22 m/s). People land hard in KSP, lol.

**Comment by Pappystein** [comment]
IRL there are very few Monocoque Rockets... Basically a Rocket with Monocoque structure is a true balloon tank.  IE Centaur or Atlas A-H + I, II and III.  The British Blue Streak is a 3/4th Balloon (the bottom half of the lower tank (don't remember if it was the HTP tank or the Kerosene tank,) is a full up ribbed structure.   To my knowledge very few rocket parts are fully monocoque.  Rather they are built to a much stronger standard since they fly deal with a much higher impulse.   

Sorry for the delayed response

**Comment by shadowmage45** [comment]
@MikeOnTea 
High crash tolerance -on a resource tank- would be for airdrop of supplies on atmosphere worlds (used to drop resupply packs to my Laythe base that way; slap a couple drogues on something with a ~40m/s tolerance, and drop it from orbit; unmanned, unguided).
On a structural tank -- it doesn't make as much sense.  I guess one could use them for a lithobrake aid?

Still haven't gotten a chance to look at this in-depth.  I took a quick look at the mass of the structural tanks compared to an empty LFO fuel tank, and it seemed about right to me for their current intended purpose (I think the structural tank was a few % heavier than the empty fuel tank).  Could probably still make them a bit lighter though, as they don't need the structure/mechanics for holding resources.

**Comment by MikeOnTea** [comment]
>  I took a quick look at the mass of the structural tanks compared to an empty LFO fuel tank

Well, i don't know how structural parts compare to fuel tanks irl, but i compared some stock structural parts to fuel tanks. In addition to the numbers for service bays and structural fuselages given above, another example: the 6t 3.75m cargo bay. This thing has 50 m/s impact tolerance and 2700k heat tolerance. A similarly sized empty LFO tank weights about 12-12.5t. And the cargo bay even has doors which should add to its weight, so a structural part without any fancy stuff like doors should be even lighter, i guess.

One could argue that some stock parts are a bit OP, but well, this mod uses stock balance, after all. One could also look at it the other way around, the stock fuel tanks are a bit underpowered/too heavy compared to the other parts, maybe intentionally so to make staging more attractive in the small kerbal universe.

**Comment by shadowmage45** [comment]
Reduced structural tanks to 0.65 * their previous mass value.  Also introduced a 'lightweight-structural' tank type that is only 0.25 * the previous mass value.

**Comment by shadowmage45** [comment]
Leaving this open subject to further balance changes/updates.  I'll have to dig into the MFT/VC code to see how best to set up the configs for stock equivalent behavior on structural parts.
