### ISSUE TITLE
MFT - Tank Modifiers - Need to adjust part cost

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#566]
Apparently 'cost modification' is already a thing in the plugin code.  Needs to be added to the modifier type definitions.
* lbo = 1.5
* zbo = 2
* light-zbo = 3
* lightweight = 2
* structural = 0.5
* structural-light = 1

----
Also need to finish enabling the tech-tree based 'upgrades' that enable these tank modifiers.

I think they simply need to have the upgrades added to the parts, and the plugin needs to check for the corresponding upgrades.

**Comment by taterkerman** [comment]
This is great, because balance is not all just mass.

**Comment by shadowmage45** [comment]
Done, and done :)

Tank modifiers will now influence the cost of the 'dry tank' according to the above multipliers (does not impact resource costs).

Have also (tentatively/WIP) added tech-tree unlock/upgrade nodes for the tank modifier types -- they should now only be available when the upgrade has been purchased for that modifier type (enforced in the GUI only; default config values could still specify a locked/invalid modifier type... but configs are easy to fix).

**Comment by shadowmage45** [comment]
Leaving this open, as the cost multipliers need to be further adjusted.  The reduced mass from the more light-weight tanks results in reduced base cost, as such the multipliers need to take this into account.

Alternatively, the cost could be calculated from the tankage volume, though this would be a potentially more disruptive solution.

**Comment by shadowmage45** [comment]
Lightweight cost was about right, left as-is (50% more than standard tank for any given tank size).
Structural cost and mass reduced a bit more; it was previously slightly below the standard tank.
ZBO-light cost increased substantially, it was previously less expensive than standard ZBO.  Also decreased its heat and impact tolerances a bit further (1->0.75).
