### ISSUE TITLE
Fuel tank texture switching does not apply to symmetry counterparts

### ISSUE THREAD

**Issue by blowfishpro** [shadowmage45/SSTULabs#57]
Main tank type and ends do, however, so I'm guessing this is just a bit of missing logic from the texture switching code.

**Comment by shadowmage45** [comment]
Yep, should be pretty easy to add in (now that I know how to do the symmetry stuff).  Few other areas that I need to look into as well.
Should have this fixed for the next update.

**Comment by shadowmage45** [comment]
Fixed in dev.  Texture set now updates all symmetry counterparts when texture are swapped.  Should apply anywhere this module is currently used, or used in the future.
