### ISSUE TITLE
4-1 short adapter lacks node.

### ISSUE THREAD

**Issue by taterkerman** [shadowmage45/SSTULabs#576]
I tried with a few DOS parts, and COS parts.

**Comment by taterkerman** [comment]
I checked all the others, I think, and they all work.

BTW, I checked in both the 1.3 and 1.3.1 versions.

**Comment by shadowmage45** [comment]
Thanks for the report -- noted and fixed.

Looks like it had a node defined, but it was in the wrong position (0.19 vs 0.964), so it was likely clipped/sunk into the model (and mostly unusable).
