### ISSUE TITLE
Procedural Probe/Decoupler - need orientation marks

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#577]
Hard to tell what direction is up/forward.  Inconvenient with the decoupler, but dangerous with the probe-core.

**Comment by taterkerman** [comment]
Could it be a different "top" color?

**Comment by shadowmage45** [comment]
Would work for the decoupler, yes, but the probe core also needs to know what direction is 'front'.  Which.... if I'm creative... could simply be a small triangle or something added to the front of the 'top' texture (so the sides are still smooth textured).

**Comment by shadowmage45** [comment]
Added stencil lettering to the top/bottom of the probe core/decoupler to differentiate top and bottom, as well as note what direction is 'forward' (for probe-core use).
