### ISSUE TITLE
SRB-A Length slider only visible on D variant

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#579]
The slider for the SRB length is only visible for the D body variant for me.

[v1.3.1 fresh install with .143 sstu version]

**Comment by shadowmage45** [comment]
It shouldn't be visible on -any- of the SRB-A models.  They are intended to be built in discrete segment sizes.

Will look into it / remove it from the configs.

**Comment by Jimbodiah** [comment]
But how do you select the length then like in previous versions?  [making screenshots now, just a sec]

**Comment by Jimbodiah** [comment]
djammit...  started a new career and it seems the length is now limited to technodes...

I'd like to change my title to "SRB-A with type D still allows length to be changed in low nodes oposed to A/B/C"  ;)

**Comment by shadowmage45** [comment]
Hehe, yeah, you can thank some of the forum guys for the tech-node-unlock changes.  Seems logical in the scope of the stock career setup though, and does keep the SRBs a bit more reasonable in the early-game.

Have updated the title to be a bit more representative of the issue.

I might be willing to leave the D variants' v-scale control enabled -- it doesn't have any geometry that would cause problems when scaled, only a minor bit of texture stretching/squashing.  Will have to take a look at the part and see how the models look when scaled, and setup proper min/max scale defs for the models as well (unless I have already done that -- which could be why the scale slider is showing up in the first place).

**Comment by Jimbodiah** [comment]
No problem on the node unlock, I just stumbled onto the discrepancy when looking why I couldn't change the length anymore  :)    Now I have to change my Science1 craft as it used an SRB as the first stage :)))   (haha, np man, I need to overhaul the craft files anyway for 1.3.1, which is why I started a new career).

**Comment by shadowmage45** [comment]
:)

Thankfully I think the majority of the 'breaking changes' that could happen in the near future, just happened with the last update, so hopefully the 1.3.1 version will be stable for awhile yet.

I am personally liking the changes to tech-node-driven unlocks though; it makes the progression seem a bit more stepped, and actually gives a reason to purchase some of the later nodes (which with the stock parts removed, some of which would be otherwise empty).

**Comment by Jimbodiah** [comment]
I've not really seen anything weird so far, just the SRB lengths, but on old crafts it actually spawns in the size you want, it will only limit to the new unlocks when you use the sliders; says "not found".

**Comment by Rodg88** [comment]
Speaking of the SRBs, even after buying the segment upgrades, I don't seem to be able to change the amount of segments in the VAB, except on the D variant (which only goes up to 2x). So it seems the upgrades aren't working?

**Comment by shadowmage45** [comment]
They were working in my career game when I was testing the feature.

Will try to do some additional testing on it for the next release.

**Comment by Rodg88** [comment]
If it helps, it was in a career game from 1.3.0 in which I'd already unlocked the SRBs and upgrades, before updating SSTU to .143

**Comment by Jimbodiah** [comment]
Remove the old srbs and add new ones, there may be issues with existing parts.

**Comment by shadowmage45** [comment]
@Jimbodiah brings up an excellent point.

In order to use the upgrades, you need to pull a -new- part out of the editor-part-list.  It is only at that time the upgrades are applied -- parts already attached to a craft do not get upgraded automatically.

**Comment by shadowmage45** [comment]
Think I'm going to leave this 'feature' as-is.  I'm fine with the length scaling being used on the -D body variants as there is little/no geometry that will be skewed improperly (which is apparently why I added the scaling specifications to those body models to begin with). 

It would be far more disruptive if used on the other body variants (that have the segment bands at regular intervals), and I would likely remove it from them if present.

This also gives one body variant that can be 'fine-tuned' for the lower-stage SRBs similar to the upper-stage SRBs.  So probably a net-win in the 'useful features' department.
