### ISSUE TITLE
Rebalance of docking port weights

### ISSUE THREAD

**Issue by MikeOnTea** [shadowmage45/SSTULabs#580]
The DP-1 port is probably a little on the heavy side with 500kg, but the small DP-0 port is too light weighting just 20kg like the stock port even though it also has parachutes.
I don't propose any new values here as i don't know how the sstu parachutes compare with the stock ones.

**Comment by taterkerman** [comment]
A version minus chutes is likely in the offing, particularly given that ports have been scrubbed from the station parts.

**Comment by shadowmage45** [comment]
Yes, a no-chute version should be coming along before too long; just some config work to duplicate/edit for the new part.

Re: Mass -- I'll do some comparisons vs. the stock parts and parachutes to see where these should be situated.

I think the 0.5t for the 1.25m is probably not too far off, but the 0.02 for the 0.625m is certainly too light for its functionality.

**Comment by shadowmage45** [comment]
Changed weights:
0P - 0.13t
1P - 0.37t
0 - 0.03t (no parachute)
1 - 0.07t (no parachute)

Yes, I added some 'no parachute' versions.  Will work on adding different texture sets / models for them in the near future.
