### ISSUE TITLE
Docking port unpassable in CLS

### ISSUE THREAD

**Issue by rtleitao** [shadowmage45/SSTULabs#581]
Docking ports are currently unpassable with CLS.
I suggest adding the CLS module to the config file

MODULE
	{
		name = ModuleConnectedLivingSpace
		passable = true
		passableWhenSurfaceAttached = true
	}

**Comment by Jimbodiah** [comment]
There is an error in the current patch for CLS as it list the same (small) port twice. I will fix it and add the large port.

**Comment by Jimbodiah** [comment]
PR sent.

**Comment by shadowmage45** [comment]
Thanks @Jimbodiah will take a look at the PR for this weekends release.

ref - https://github.com/shadowmage45/SSTULabs/pull/582

**Comment by rtleitao** [comment]
You guys are awesome
