### ISSUE TITLE
RBDC no longer aligns to center of booster

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#583]
See picture. I think the nose cone is counted as part of the main body for centering purposes?

![screen shot 10-18-17 at 06 33 pm](https://user-images.githubusercontent.com/16107012/31730728-1ac43390-b433-11e7-81c8-51c143859372.PNG)

**Comment by shadowmage45** [comment]
Where the tank attaches to the RBDC is dependent upon the tanks' surface-attach node location.  For the MFT tanks it should be located directly at the COM.  Which is correct.

Now, what had changed recently, is I added offsets for the nosecones and/or mounts to the fuel tanks -- as they are filled with fuel, they also effect the overall positioning and the COM relative to the tank body -- add a nosecone and the COM moves upwards, which is what you are seeing in your image.

Of course when you add engines to the boosters, that will shift the COM of that sub-vessel segment downwards; but that is something the user will have to accomodate themselves by adjusting the position of the tank body relative to the RBDC.

I would say it is working as intended based on the information and image provided.

**Comment by Jimbodiah** [comment]
ok!
