### ISSUE TITLE
SRB Segment slider not visible in Sandbox

### ISSUE THREAD

**Issue by pixe1reality** [shadowmage45/SSTULabs#589]
With the SRB-A part, I cannot change segment count in Sandbox.
After cheating in completed techs in Career and Science mode, it still does not apply the SRB segment upgrades.
Do note, I have checked to ensure part upgrades are enabled in the Game Settings menu.

[v1.3.1 fresh install with SSTU version .144]

**Comment by taterkerman** [comment]
Have to checked the box in sandbox settings to apply all part upgrades?

**Comment by shadowmage45** [comment]
@T10a would you mind uploadind a KSP.log file, as well as your save/persistent file?

The log will tell me if there is anything interfering or any plugin-side errors, and the save file will tell me the current purchased state of upgrades as well as if upgrades are enabled/disabled in the save.

**Comment by pixe1reality** [comment]
Weird. After testing out the game again, the SRB upgrades seem to be fine in sandbox & career modes.
Will do further testing to find which mods conflict to cause the issue.

**Comment by T10a** [comment]
After further testing, I can conclude the error is not on SSTU's end, but on the SSTU-Nova mod's end. Close this issue, and I will notify JoseEduardo about it.

**Comment by pixe1reality** [comment]
After further tests, I've found it is SSTU Nova addon doing this (it adds SRB diameter upgrades, which conflict with the new SRB changes). Issue closed, and will notify JoseEduardo.

**Comment by shadowmage45** [comment]
Thanks for investigating the problem a bit yourself :)

Good thing is I just saw Jose around the forums recently, so he should be back from his ARK induced KSP break.  If you can't get ahold of him otherwise, please let me know -- I've got some other contact info, and/or I might be able to figure out the fixes myself.

**Comment by pixe1reality** [comment]
I left a comment on the Nova forum page, which should let him know as well as anyone else who may be having this issue.

**Comment by Jimbodiah** [comment]
The expansion pack breaks more things as it's not been updated since 1.2.2 I think.
