### ISSUE TITLE
RL-10A4 has a torque according to KER

### ISSUE THREAD

**Issue by MikeOnTea** [shadowmage45/SSTULabs#591]
RL-10A4 has a torque according to kerbal engineer, possibly caused by a slightly off-center thrust vector?
Test rocket was just an mk-1 pod, small tank and the RL-10A4. The torque went away when replaced with other engines.

**Comment by shadowmage45** [comment]
Thanks for the report.

Not quite sure what is going on with this one, as the transform is perfectly centered when I look at the model in Blender.  Going to have to pull open the Unity project and see what is up with the model there.

Hmm... going to try and import the .mu directly into blender and see if it is lined up there (which should tell me if it got misplaced somewhere in Unity).

**Comment by shadowmage45** [comment]
Indeed, the transform as it looks in the imported-from-mu model is slightly misplaced.
-0.009, 0.0022, -0.2846
The X and Y are the errors.  The Z is just the vertical position as it should be.

Looks like I'll have to re-export the model through PartTools.  Gotta love Unity and how it mangles everything it touches....
