### ISSUE TITLE
Remove MFT MM patch

### ISSUE THREAD

**Issue by NicholasZonenberg** [shadowmage45/SSTULabs#593]
The Module Fuel Tank patch gives the parts a stupid amount of tankage and the issue is on MFT side so remove the patch until fixxed.

**Comment by shadowmage45** [comment]
Have adjusted the MFT patch to exclude ModularFuelTanks(the mod).  Will now only activate when RealFuels is detected.

This means that SSTU parts can no longer use the ModularFuelTank(the mod) GUI for fuel selection, and must use the SSTUVolumeContainer system even with MFT installed.

RealFuels will still use the RF GUI and fuels handling.
