### ISSUE TITLE
Custom MUS RCS propellants?

### ISSUE THREAD

**Issue by pixe1reality** [shadowmage45/SSTULabs#595]
I have a tendency to use hypergolic upper stages (engines like the AJ10-190, LR-81-80xx series, or even the SuperDraco if the payload is small enough), and with the upcoming modular RCS patch which can use multiple kinds of propellants, why can't the MUS also use different propellants?

On an unrelated note, shouldn't the LR-81s be labelled as XLR-81? I think that may be a typo.

----
Developers' Notes:
- [ ] SSTUModularRCS - adapted for fuel-switch only mode and/or centralized rcs-fuel switching code created. (used on MSM)
  * Might be easier to keep the code for this use in the MUS module, as it will be much easier to sync rcs fuel type to support tank fuel content
- [ ] Centralized RCS-module fuel-manipulation code; input a 'fuel type', and 'part'  (use this for MUS integration)
- [ ] MUS modules support tank fuel type synchronized to the fuel type for the RCS.  Maintain constant volume of battery relative to rcs propellant
  * Possibly move battery to its own CONTAINER, and give it a separate % slider in the GUI.  Would allow for cleaner (and easier) code-side integration of the feature.
  * How will these changes impact existing craft?  **might be a craft breaking change**

**Comment by Jimbodiah** [comment]
I think all sstu parts with rcs will get the toggle. In the meantime you could patch current parts to use hypergolics instead of MP if you want.

**Comment by shadowmage45** [comment]
I'm about 50% of the way to making this functional.
* SSTUModularRCS (PartModule) has been made able to function in 'no-model' mode, where all it does is update the RCS modules' fuel type.  
* Scale and structure GUI controls can be disabled, and the back-end code will skip those functions as appropriate.
* Still need to work on the MUS integration end of things; syncing support-container fuel type to that of the RCS ports.

**Comment by shadowmage45** [comment]
This will be fully available in KSP1.4+ releases.
