### ISSUE TITLE
SC-GEN-MDC + SC-GEN-MPC - New Parts (Modular Decoupler / Modular ProbeCore)

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#600]
Analogues to the ProceduralDecoupler and ProceduralProbeCore that use the ModularPart setup.  These would use pre-built models and include texture switching.  Adapter/nose/mount selection is also a possibility.

Could likely use the existing SSTUModularFuelTank module code with minor adaptions to handle manipulation of the decoupler force.

SSTUModularFuelTank module could have some simple 'on-geometry-changed' callback/delegates added, or create a derived/child class.

**Comment by Jimbodiah** [comment]
Can you elaborate on this? Not sure what the parts will do.

**Comment by shadowmage45** [comment]
These would be simple decoupler/probe cores, but with actual models and textures.  They would still feature re-scaling (whole model scaling), but would not have independently adjustable height controls.

For decouplers think stuff like a lattice decoupler for Soyuz hot-staging.  Or a special form-fitting decoupler for the reworked LC tanks (octagonal form factor); or other special form-factor decouplers where the simple procedural cylinder doesn't work.

For probe cores, something like the Saturn-V IMU (along with the other non-standard form-factors mentioned for the decouplers; octagonal, square, etc):
https://en.wikipedia.org/wiki/Saturn_V_Instrument_Unit#/media/File:Instrument_Unit_514_(IMGP3463mod).jpg


95% of the code to make it work already exists; just needs models+textures created.

**Comment by Jimbodiah** [comment]
Ah, gotcha!!!

**Comment by vossiewulf** [comment]
A nice feature for decouplers would be optional ullage rockets. I was actually surprised considering the general them of every part being able to do anything that part could possibly do that I didn't see that in the decoupler options the first time I tried one.

**Comment by Jimbodiah** [comment]
Hate to break it to you... but there is a seperate decoupler with motors built in that you can set as ullage or retro rockets. My favorite decoupler in the game ;)))

**Comment by vossiewulf** [comment]
SSTU has that? Ok only thing I can guess is I haven't gotten to it in tech tree, but since I was doing the 1500 science stuff in the CTT I figured I was past any basic equipment like that. The only ones I know of that have built-in ullage are a couple from I think KWR, but only 1.25 and 2.5.

**Comment by shadowmage45** [comment]
This part here:  https://github.com/shadowmage45/SSTULabs/blob/master/GameData/SSTU/Parts/ShipCore/General/InterstageDecoupler/SC-GEN-ISDC.cfg

The 'Interstage Decoupler'.  Combination interstage fairing + ullage (or retro) motors.  Fairing portion is recolorable, engines not (yet).

**Comment by Jimbodiah** [comment]
Yep, you can even make it longer and taper it to make a real interstage fairing with integrated ullage or retro.
