### ISSUE TITLE
Radial Booster Decoupler engine sound excessively loud

### ISSUE THREAD

**Issue by vossiewulf** [shadowmage45/SSTULabs#602]
SC-GEN-RBDC - Customizable Radial Booster Decoupler

Good way to check that your crew is on their toes is to fire off this decoupler, any that were napping will bounce off the CM ceiling. And if you're playing KSP the cat in your lap will go shooting off at a TWR of CAT and claw your groin in the process. Pretty much a guaranteed adrenaline shot for everyone involved. 

It's considerably louder than the boosters it decouples and any other engine I've used recently.

**Comment by shadowmage45** [comment]
Have adjusted the volume defs in the effects block downwards quite a bit, both on the engage sound and on the engine thrust sounds.

Old peak = 1.25
New peak = 0.8

Should result in a noticeable decrease in volume.  Will do some testing to see how they sit compared to the rocket engines/etc.
