### ISSUE TITLE
HUB-COS issue

### ISSUE THREAD

**Issue by taterkerman** [shadowmage45/SSTULabs#603]
Recoloring widow is empty for now, but cannot be closed, so you have to quit the app.

**Comment by shadowmage45** [comment]
Ahh... good thing you spotted this now.  Should be able to sneak this fix into the next release (and also reminded me that I need to fix up the textures for these parts).

**Comment by taterkerman** [comment]
Silly question, but while I know the docking ports went away on all the station stuff, on the hub parts, is it possible to toggle the SIZE of the docking ports? 

For retro stuff (Eyes Turned Skywards, etc) it might be nice to save the parts on making a hub. Big ports certainly are function, but less aesthetic in that case.

**Comment by taterkerman** [comment]
DOS hub does the same thing (has recoloring GUI that is blank and disallows any further action.
