### ISSUE TITLE
Engine numbers don't increment in the right click

### ISSUE THREAD

**Issue by taterkerman** [shadowmage45/SSTULabs#605]
Place an engine. Set layout to some value above 1. The layout slider doesn't increment, so you see 4 engines, and it says "single."

**Comment by shadowmage45** [comment]
is this in the testing version?

Yes, the testing version was messed up

Already fixed.

![screenshot61](https://user-images.githubusercontent.com/1503399/32760599-392e530a-c8ac-11e7-8da8-dd081c22f435.png)

![screenshot60](https://user-images.githubusercontent.com/1503399/32760600-3c0679a4-c8ac-11e7-930d-20a1db06c8b6.png)

**Comment by taterkerman** [comment]
Yeah, I only have that linked mac version you had me test.

**Comment by shadowmage45** [comment]
The full release is now available; check the forum :)
(the test release was chock full of holes/errors/unfinished stuff; was really only intended to see if the shaders loaded)

**Comment by shadowmage45** [comment]
If the engines work for you in the full release, please let me know and/or close this ticket.
