### ISSUE TITLE
No metallic effect on certain parts

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#607]
The Apollo SM does not have the metallic effect, the slider does nothing. Specular seems to work fine.

**Comment by shadowmage45** [comment]
Aargghh.. I likely forgot a patch in there somewhere.  Should be simple enough to get it working.  All that the 'PBR-Recoloring' patches to do is change the shader... (assuming that I got all the textures exported properly).

**Comment by Jimbodiah** [comment]
Same with the panelled version of the Lander tank, for the outside panels the specular works but not the metallic. The tanks themselves are fine, it's just the outside panneling.

Awesome work, Mage. This is so amazing!!!!

**Comment by shadowmage45** [comment]
Heh... even if I missed 2-3 parts/models, out of 500 models.... that's still >99.9% on the first pass.

Shouldn't be too hard to get them cleaned up/finished up for the next release.

**Comment by Jimbodiah** [comment]
Haha, I'm not counting, just letting you know what I find. I'm amazed you got all this out to begin with, this is gyuhge (seriously)!!! You raised the bar for KSP by 10ft, not just 1.

**Comment by shadowmage45** [comment]
Both the SC-B-SM and MFT-LV paneling/caps should all now be using the PBR shaders when the PBR expansion is installed.

Please let me know if you run into any other parts that look like they were mis-converted / places where things are not recoloring properly.

**Comment by Jimbodiah** [comment]
Will do!

PS: Do you mean on the next release or on the current one (ninja re-upload?).

**Comment by shadowmage45** [comment]
Ahh, sorry, I refer to them being fixed in the dev branch :)

One of these days I'll have to walk you through setting up git so you can get easy access to the dev branch.  Its publicly available through the GitHub web portal, but kind of a pain to download what is needed.

**Comment by Jimbodiah** [comment]
No worries... no rush...

I made some PRs to update all the ModIntegrations to point to the new LV tank. So more food for a release next week maybe.

**Comment by Jimbodiah** [comment]
PPC and PDC as well.

**Comment by shadowmage45** [comment]
PDC/PPC fixed; had a typo in the naming of 'Decoupler-A' texture set (Decouler-A... just doesn't work)

**Comment by shadowmage45** [comment]
Need to add - SC-ENG-MOUNT-FLAT and the fuel tank inset-domed end-cap (tank-none?)

**Comment by Jimbodiah** [comment]
I checked most parts now I think, haven't seen this issue with anything else.
