### ISSUE TITLE
Request: Round nose/mount on LV tank

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#614]
There is an octagonal mount/nose option right now. Would it be possible at some point to add a round version as well? There is an extended round frame now, but that is quite wide, the octagonal one is one  size narrower and would fit a CM or round tank very well.

**Comment by shadowmage45** [comment]
Not easily; the texture sheets are very packed as it is, I don't think there is room to add more new geometry anywhere.

Which means... not really doable.  Would require a new texture sheets that would end up with duplicate sections for the tank domes/etc; very inefficient use of textures, and time (would have to UV unwrap the new geometry, and re-unwrap the re-used geometry for the new texture sheet).

Had the request been made while I was working on the geometry originally, I likely could have found a way to make it work out.  At this point in time it would be very time consuming to make the addition.

**Comment by Jimbodiah** [comment]
No problem...   ;)

**Comment by shadowmage45** [comment]
One thing I might be able to do would be to make a stand-alone adapter part, and/or an adapter part that can be used on the -other- fuel tanks to adapt them to an octagonal form factor.

-Might- be able to integrate that stand-alone model into the MFT-LV by using a COMPOUND-MODEL_DATA model definition for it (creating a new adapter definition, re-using one of the existing models with the new adapter added in).

Going to re-open this while I give it a bit more thought.  No guarantee that anything will come out of it...

**Comment by shadowmage45** [comment]
Unfortunately it does not look like this will be doable as proposed without major changes to the existing models and textures, adding in the new geometry.  Essentially would require a complete rework of all of the part models/textures... so many tens of hours of work.

The existing 'octagonal' mount isn't actually a form factor.  It is just an octagonal piece to cover up the tanks, intended to give -something- to mount engines/etc onto.  If it happens to be close to a standard stack-mount size... it is entirely coincidental.

The possibility will exist in the 1.4+ rework versions to add further 'nose/mount' adapters to the part, but these would be added on above/below the existing 'ring' style mount.  

The possibility also still exists to add in an 'octagonal' form-factor (more mounts/adapters, for use on all tanks) -- but would be a much larger project, and nothing that I could commit too for the foreseeable future.

**Comment by Jimbodiah** [comment]
No problem! Thanks for looking.
