### ISSUE TITLE
Gloss

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#615]
Even with specular and metallic set to 0, there is always a gloss over the parts, making matte surfaces impossible.

**Comment by shadowmage45** [comment]
Which parts?  And do you have images/examples?

I am able to make very matte colored fuel tanks/etc without problem.  There could be some parts that still have improperly setup spec/metal textures though, which would give an undesired offset to the value specified in the UI.

**Comment by taterkerman** [comment]
Regular tanks looked matte to me when I was messing around last night.

I loaded my old Atlas V model I was playing with, and the SRBs had shiny nose parts, and I had not set them to that---take a look at those, perhaps.

**Comment by Jimbodiah** [comment]
MFT-A and basically every part with the new recoloring. If you move up/down you see the hint of a reflection moving up/down like there is a clearcoat over the part. Lemme make some screengrabs... brb

**Comment by Jimbodiah** [comment]
![pbr_13](https://user-images.githubusercontent.com/16107012/32863405-ac41c1e6-ca5b-11e7-8708-76adf16f6eaa.jpg)

**Comment by shadowmage45** [comment]
Ahh.. you must be using DX9?  (don't feel bad... it took me ~3 days to figure out what was causing this)

(it is a known issue with Unity and DX9 -- they don't blur the cube-maps properly across their seams -- **not** something that I can solve; this is why Unity has dropped support for DX9 entirely in their recent releases, or one of the reasons)

Edit:  DX11 and OpenGL both work fine for cubemap blurs.

**Comment by Jimbodiah** [comment]
euhm, how do I know what dx version I am running?  My gpu is not the issue, so I don't know why I'm not on dx11 as my nvidia drivers are up to date as well.

[edit] nvm, found it... running DX11 according to dxdiag.exe

Do I need to force DX11 somehow then in ksp?  omg, not this shit again like in x86 with the OpenGL force to save memory :)

**Comment by blowfishpro** [comment]
KSP defaults to DX9 even if your system supports better.  Run with `-force-d3d11` or `-force-opengl` to ensure it's not

**Comment by Jimbodiah** [comment]
That is so 2015....

Wow... yeah, now it's matte again, and some colors are really whacked vs earlier today.

**Comment by shadowmage45** [comment]
So is most of KSPs codebase :)

**Comment by Jimbodiah** [comment]
Assumption is the mother of all fuck-ups... but I assumed the game just used the latest install and didn't force a legacy version.

**Comment by shadowmage45** [comment]
:)

Now you can enjoy even further improved visuals and lighting.  Not that DX11 seems to do much beyond fix the cubemap blurring.

**Comment by Jimbodiah** [comment]
Now I know how tater got those reflections in his tanks and my confusion with the PRB labeled tanks... I only got a vague reflection from the hab, nothing like the mirror-effect. I have that now though, wow, what a difference...
