### ISSUE TITLE
VAB lighting

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#617]
"You know... it might be not too difficult to add in a pre-rendered environment map that represented a basic 'in LEO orbit' scene.  Possibly two; one for sun-lit, one for shadowed.  Finally a small in-editor GUI would let you swap between the 'live' cubemap or the pre-rendered ones.  (adding/using the pre-rendered cubemap would be dead simple.  Getting a good pre-convolved one....much more difficult, but doable with the techniques that I currently know)

(if someone wants to open an issue ticket under TexturesUnlimited repo on the subject, it will ensure it doesn't get forgotten about)"

**Comment by shadowmage45** [comment]
Moved to -- https://github.com/shadowmage45/TexturesUnlimited/issues/20
