### ISSUE TITLE
Request: Longer recoloring GUI

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#618]
1st world problems :(

![pbr_14](https://user-images.githubusercontent.com/16107012/32866986-af99f6d8-ca6a-11e7-8658-298435fad7ca.jpg)

**Comment by shadowmage45** [comment]
Hehe indeed :)

I can likely make the height of each section configurable through a config file.  Simple, effective, configurable.

**Comment by Jimbodiah** [comment]
That would be awesome!!! :100:

**Comment by Jimbodiah** [comment]
BTW: Want me to PR some of my colors into the standard ColorPresets? No rainbow puke colors ;)

**Comment by shadowmage45** [comment]
Will be available with the next TU release.  Check the config files in the TexturesUnlimited directory, should be some width/height controls.  Its probably just the 'total height' one that you want to adjust.

**Comment by Jimbodiah** [comment]
Dude, stop it!!!!!  You're spoiling me!!!!

**Comment by shadowmage45** [comment]
Well, you actually take the time to file proper issue tickets for the stuff.  Nice and separate, singular issue tickets.

The least I can do is take care of the easier ones when I have the time.  Lets me 'cross things off the list' and pad the length of the patch notes :)

Re: the preset colors -- I wouldn't worry about it for the time being.  I think I'm going to be splitting the colors up into 'PBR' and 'Legacy' definitions in the near future, so the format will likely be changing at that point (many of the default colors need adjusted for the PBR setup to maintain the desired visuals;  blacks need to be darker, whites brighter, and metals lighter base colored).

**Comment by Jimbodiah** [comment]
Thanks, Mage!!!!
