### ISSUE TITLE
Only one part loading?!?!?

### ISSUE THREAD

**Issue by mythmm** [shadowmage45/SSTULabs#619]
for some reason, when I play with the mod installed, only one of the modular heat shields loads and nothing else. I have the mod correctly installed on a Mac Notebook, don't know what model.

**Comment by shadowmage45** [comment]
Please upload a KSP.log file.  It can be found in the same directory as the KSP executable.  It will contain the information needed to help diagnose this problem.

**Comment by Jimbodiah** [comment]
Maybe also a screenshot of your GameData folder?

**Comment by Jimbodiah** [comment]
*crickets*
