### ISSUE TITLE
sAll the SSTU titled parts are missing icons and have no models

### ISSUE THREAD

**Issue by Squishydoo** [shadowmage45/SSTULabs#620]
hi, I am writing here to report on a bug with this mod, I have checked the logs but apparently nothing is wrong, but for some reason all the SSTU parts are missing icons and have no models, i have no idea what to do please help

**Comment by shadowmage45** [comment]
Please upload a KSP.log file.  It can be found in the same directory as the KSP executable.  It will contain the information needed to help diagnose this problem.

**Comment by Jimbodiah** [comment]
Sounds like you do not have the 000_TexturesUnlimited directory **OR** have altered the ColorPresets.cfg file to remove a color that is used. I get the same thing then, where parts do not show up on saved craft files and their icon is empty. Replacing the folder/file with the original should fix it.
