### ISSUE TITLE
SSTU-LCS-POD UI issue

### ISSUE THREAD

**Issue by vossiewulf** [shadowmage45/SSTULabs#621]
It's missing the Seat 0 Inventory. Yeah it doesn't get more minor than that, but you said you want these.

Design issues, texture doesn't look good in general but it has what looks like solar panels but they're not. Those should go, confusing and they're pretty low-res anyway. Would be helpful if we could toggle off the docking coupler, or better yet could choose between none and a couple sizes of docking couplers.

Lower section is very short leaving only a couple options for landing legs if you don't want them sticking through the pod when retracted. Built-in legs would be useful, or modify the model to allow more landing leg options. Also please make the default something besides Heer gray ;)

**Comment by taterkerman** [comment]
Are you saying that if you cover the panels, they don't work? Because I just launched one to the pad at night, and EC drained, and at dawn, it came back, clearly it has solar, though they might not be the panels drawn on.

**Comment by shadowmage45** [comment]
Seat inventory = KIS problem ~~(actually it is the KIS - MFT bug already listed on the tracker)~~.  Actually, this would seem to be a slightly different problem, and is likely related to the KIS/MFT integration problems.

Solar panels -- it does have them, and they are functional.  They are even 'curved' as they appear on the pods (multiple sun-catchers at different angles).

Textures -- yep, they were one of the first parts I ever modeled/textured, and it shows a bit.

Docking options -- see the recent discussions on this.  Swappable docking ports does not work in KSP; there is a good reason I removed them from the StationCore parts.  In the future versions of the LC-POD's, there probably will be no docking port (good thing is, you can remove the docking port with a simple config edit or patch).

Landing legs -- nothing I can do about that in the short term.  The geometry is what it is.  (If there were twenty of me, and we all had infinite time, I probably still wouldn't be able to make all the new models that are wanted/requested)

(generally, I should just delete/remove the old LC pod parts, they are long past their time; sadly will be at least a few months before I have time to make replacements)

**Comment by Jimbodiah** [comment]
Nah, they can still be used, so what if they look retro? They are not broken, I say leave them in for now. 

@vossiewulf   If you want to remove the docking port, check out JoseEduardo's SSTU Expansion Pack where he has done just that (don't install the pack as it is for 1.2 and causes a lot of problems with textures etc, but you can check his config for removing the ports).

The entire Lander Core will be overhauled in the near future, just be patient ;)

**Comment by vossiewulf** [comment]
Ok, I saw no listing in the right-click part info popup that said anything about generating EC/sec, so either I just missed it or that is missing from the description.

I have no pressing need to remove the docking port, I was just walking through design suggestions while I was thinking about it. And yes that part looks like probably some of the earliest done.

**Comment by shadowmage45** [comment]
Have fixed the only part of this issue that is fixable -- the KIS integration problems.  The rest are problems that cannot be 'solved', but are feature-requests for new models and texture changes.
