### ISSUE TITLE
Request: Blue option for solar panels

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#622]
Could there be a swtich on the DOS panels for the reflective part to toggle between the current yellow and a blue version?

Will the framing of the DOS solar panels support recoloring like on the SC-C-SM ? Or the central truss on the ISS ones for that matter, as I notice the end caps already support recoloring?

**Comment by shadowmage45** [comment]
You can have -either- recoloring -or- back-lighting.

(no, I will not be making multiple solar panel texture options)

**Comment by Jimbodiah** [comment]
;)
