### ISSUE TITLE
Request: Close Petal Adapters

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#623]
Option to close the petal adapters again after deploying?

Like in the VAB basically.

**Comment by shadowmage45** [comment]
Possible yes, but perhaps unwise?

The part is intended to represent a spring-loaded petal adapter.  They don't use motors for deployment, so there is no possibility for it to be retracted.

**Comment by Jimbodiah** [comment]
Is it config file based or handled by the plugin? if it cfg based I oculd patch it for personal use perhaps.

**Comment by taterkerman** [comment]
As a petal, yeah. For some applications, like trying to make something like BFS cargo, or some of the old 1960s concept HLVs that are reusable, closing a cargo bay is a cool thing to be able to do.

**Comment by shadowmage45** [comment]
Plugin based -- I would have to adjust the code to allow for it to close.  But also, as there is an option to 'jettison panels on deploy', I have to make sure that the option to close is only available when the panels have not been jettisoned.

**Comment by Jimbodiah** [comment]
It's not a big deal for me, just a nifty thing to have for end-game or alternate use. I'd not mind if you hide the option to set this in the cfg file and keep it working as-is on a stock sstu install for example...

**Comment by taterkerman** [comment]
Yeah, it's an edge case to be sure, but people might want to make these:
![you-only-live-twice-3](https://user-images.githubusercontent.com/17967275/32964813-a51f6c1a-cb91-11e7-946b-82eb70c2842c.jpg)

**Comment by Jimbodiah** [comment]
LOL, James Bond :)

**Comment by taterkerman** [comment]
Anything is possible, with zombo.com, 'erm, SSTU. The only limit... is your imagination.

**Comment by Jimbodiah** [comment]
..and KSP.

**Comment by pixe1reality** [comment]
A thing I noted with the panel jettison is that when jettisoned, all it does is make the panels fly away but is still highlightable in the distance. Does that part of the model vanish eventually?

**Comment by shadowmage45** [comment]
Yes, they are non-persistent debris, and will vanish after they get ~2km from the craft or timewarp is activated.

**Comment by shadowmage45** [comment]
* Also fixed up some collider related issues.
* Added deploy-limit slider; available both in editor and in flight.
* Added toggle for if should auto-decouple top node on deploy
