### ISSUE TITLE
Vertical Scaling Issues

### ISSUE THREAD

**Issue by Temeter** [shadowmage45/SSTULabs#629]
Vertical scaling for the MFT-A seems to be broken; at 3x, it only allows values from 0.9167 to 1.0833, getting lower values the bigger the tank becomes.

Also, was it intentional to remove the vertical scaling from the MFT-D (Soyuz Booster tank)? IMO the scaling was quite useful for that part.

---

Neither of those part *has* to have that additional scaling, but it is quite useful for unusual scalings, taking another larger/smaller tanks model and fine adjustment.

**Comment by shadowmage45** [comment]
>Vertical scaling for the MFT-A seems to be broken; at 3x, it only allows values from 0.9167 to 1.0833, getting lower values the bigger the tank becomes

Yep, fully intentional.  It maintains that each tank length can scale halfway to the next tank length.
So if the A tank was 10m long, and the B tank 15m long --
the A tank would scale from X to 12.5m, the B tank would scale from 12.5m to X

**Comment by Temeter** [comment]
I see, the increments obviously become larger at bigger scales. Clever.

Not sure if there is much of a point in limiting the options in general, though, but it doesn't matter too much either~

**Comment by shadowmage45** [comment]
The entire reason for limiting of the vertical scaling is to limit the model _skewing_, which can distort geometry and surface normals incorrectly.  For example the piping on the MFT-A tanks becomes less-than-round, and the braces get squashed/stretched.  The normals for the ribbing also get out of whack a bit.

This is the reason why I have such a small range of scaling -- within that range the deformation is hardly noticeable.  At larger scale values it is quite noticeable.  Even more so on parts with odd geometry (MFT-D).

**Comment by Temeter** [comment]
Haha, I just love to get options and don't mind breaking things, that's where I'm coming from.^^

No objections from me tho, the part size/scaling options work fine either way.

**Comment by shadowmage45** [comment]
I should also note that it is all config based -- you can take a look at the existing configs and patch the other parts to support that feature.

I believe the min/max scale is defined within the MODEL nodes within the SSTUModularFuelTank part module; if you look at the MFT-A config, it will probably tell you all you need to know.
