### ISSUE TITLE
MFT-Tanks - KIS spam

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#630]
Caused by the method used to blindly search for a module by name.

Should look into completely dropping KIS support, as the methods that I'm using aren't really 'supported' by KIS.  Nor does KIS actually support being able to move SSTU parts last I checked, as it relies entirely on mesh information from the prefab.

**Comment by vossiewulf** [comment]
I'm not sure what comes from what - do you have to use KIS to offer rocketparts/equipment/researchkits kind of things? If so then that would hurt. If not, not sure what it IS offering.

If you can't do the EL/Pathfinder things without KIS, I'd consider making a KIS-specific cargo part that's only as mutable as it can be without annoying KIS, and remove KIS from all of the parts where customizability is paramount.

**Comment by shadowmage45** [comment]
KIS is completely un-neccessary for any SSTU features.

It -is- mandatory for EPL survey-stake builds.

Should be no real SSTU related problems if I drop support for it from the MFT tanks.

**Comment by taterkerman** [comment]
I'd say that it's not worth the trouble. You've stated you were planning on your own EPL functionality at some point, and that might be an opportunity for something KIS like. Any sort of building part could be scaled to final craft mass, and maybe a small such part on a lander might allow a small rover to be built or something (or stored inside). Gives the functionality of KIS minus the busy work of trying to build something with kerbals.

**Comment by shadowmage45** [comment]
I very much believe that KIS has a place -- but it is more for replacing lights and solar panels that you knocked off while jet-pack-racing around the base, then it is for wholesale base or craft construction.  Or for add-on upgrades like adding more science experiments or swapping out small components to older craft.

The exception might be KIS-assembled rovers... but honestly those could be handled through EPL as well (carry enough raw materials to build the rover on-site, have a 'workshop' in the landers' crew pod, survey-stake a build-site, and away you go).  Actually would be less construction fuss that way as well as you can design your rover in the VAB, though it is a bit more abstract than KIS assembly.

As a bonus, doing it the EPL way doesn't require any additional support on the SSTU end of things.  Just add the raw resources to your fuel tank/storage, include a survey stake and mallet in your lander pods' KIS inventory, and done.

**Comment by taterkerman** [comment]
Yeah, exactly.

Alternately a storage unit that puts an entire craft file (subassembly?) inside the "EPL" part, and there is no extemporaneous building once landed. You just "launch" the part.

The pipes are useful, but I think that there is already the ability to treat landed distance as "attached" for bases anyway (if 2 craft are within XXX meters they are considered a base).

When fancier bases are produced, the ability to stretch a flexible crew tube is also a nice base-building feature, but again, more extemporaneous EPL use could do that, possibly (where it loads all craft within XX meters of the workshop, the perhaps stuff can be added to it).
