### ISSUE TITLE
New Part - Modular Parachute

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#631]
* Model-switched base -- round(nosecone), or square(radial)
* Stack or surface mount, though only has a single-node (inline not supported)
* Resizable
  * Determines max total packed chute 'volume'; can only pack so much chute in a given space
* Finely-tunable parachute parameters
  * Is drogue, main, or multi
  * Diameter of each chute for drogue/main
  * Number of chutes for each drogue/main
  * Density/thickness/type of material
* Stats based on parachute params
  * WIP
* Spread for multi-chute calculated automatically

**Comment by Jimbodiah** [comment]
I take it diameter will affect the descent speed? (hoping for yes)

Could you set the max altitude at something really high as well instead of the ussual 5km? 


PS: I tend to use Inline Ballutes (the mod) for high altitude aerobraking. Maybe that has some potential for a future SSTU part?  https://forum.kerbalspaceprogram.com/index.php?/topic/121162-130-inline-ballutes-ib-v128-30052017/&

**Comment by shadowmage45** [comment]
> I take it diameter will affect the descent speed? (hoping for yes)

Yes, it will use the standard drag equations to determine effectiveness.  This is already done in the module, but with an arbitrarily specified parachute diameter (doesn't necessarily match the visual diameter).

Terminal velocity (m/s) = sqrt((2\*kg\*G)/(rho\*area\*cD)).
kg = mass in kg
G = current gravity
rho = density of air (~1.225 kg/m3 at sea level on kerbin)
area = area of the parachute (diameter influences this)
cD = coefficient of drag (depends on the geometry of the chute)

(its mostly these same variables that influence chute safety as well...)

> Could you set the max altitude at something really high as well instead of the ussual 5km?
Its going to have a full GUI on a right click menu (e.g. recoloring/resource guis).  Will include:
* Ability to specify arbitrary altitude/pressure triggers (one or the other, toggle between the two),
* text-boxes to type in the diameter(s),
* a small area to select the # of simultaneous chutes from a few pre-set values (sorry, no infinite chutes; probably 3 or 4 max),
* # of chute reloads (can only repack this many times)
* probably a few other stats/options I'll come up with
* At the bottom there will be a small area to enter a 'test mass' and 'rho', and it will display the terminal velocity for the current chute configuration.

(yeah, sounds a bit like realchutes... but it'll be using the SSTU setup of procedurally animated models that you can add to any part/etc; no having to dink around with the crappy KSP animation handling/limited options)

> Maybe that has some potential for a future SSTU part?

I really don't have any interest in ballutes.  They've always looked dumb to me (no offense), and the performance was quite cheaty when I looked at them.  (something that large, and that heat resistant, is going to have substantial mass)  
Of course, nothing stopping you from (finding/creating) adding a ballute model that the module can use (like most SSTU modules, it will use the MODEL_DATA setup); but I'm not likely to make the models (and the models from other mods likely won't work as they use the Unity animation).

**Comment by Jimbodiah** [comment]
Thanks. Sounds interesting!

**Comment by vossiewulf** [comment]
This would be extremely handy. Thumbs up.
