### ISSUE TITLE
Add units display to inflatable parts resource requirements

### ISSUE THREAD

**Issue by vossiewulf** [shadowmage45/SSTULabs#635]
The CFG part says it will take 72t of rocketparts to inflate. It actually takes exactly 29,000 rocketparts, which works out to about 10t.

I looked at the others, they seem to be incorrect also. Secondarily, counting rocketparts by the number of parts would be much less ambiguous.

**Comment by shadowmage45** [comment]
72.05t should be required by the CFG-C for inflation.  If it is letting you inflate with less, then that is the error.

The description is correct.  Yes, the thing is heavy after inflated, and yes, the large CFG parts require a ton of resources to inflate (the -D variant is >140t of resources required).

**Comment by vossiewulf** [comment]
Geez I had tested this before filing it but I'm getting ready to send up the rocketparts for inflation and the mass I'm seeing now is more in line with your numbers. 

That said, I still think it would be much clearer to change that text to read in rocketparts numbers instead of mass.

**Comment by taterkerman** [comment]
A container about the size of a COS Hab-5 holds around 11 tons of rocket parts.

A CFG-35 requires 7 of these to be delivered to fit it out. The biggest CFG needs 13.

The one thing is odd is using tanks for this, as they really are crew containers, fully pressurized. I'd almost like to see a "supply" COS variant that can carry what containers carry, but also has at least a nominal crew of 1. Then you leave them attached and they sort of count. I'd leave them attached anyway at this point, regardless. If you assume a ton of LS related stuff for the COS-5 sized version, then each is a nice 10 ton supply unit.

Almost makes me want to try spaceplanes... Course I can also make a HLV supply capsule... Yip! a new project for SSTU that is actually playing with it!

**Comment by shadowmage45** [comment]
> That said, I still think it would be much clearer to change that text to read in rocketparts numbers instead of mass.

Sure, sounds reasonable.  Will still keep a tonnage display of some sort, but can make the main display be resource units.

**Comment by taterkerman** [comment]
This is closed, but shouldn't the part description then say the number of rocket parts, so that you know how many to add? The means you can just select the "fuel" as rocket parts, and adjust the tank without having to config containers to see the mass.
