### ISSUE TITLE
SSTU TexturesUnlimited issues

### ISSUE THREAD

**Issue by jamesb6626** [shadowmage45/SSTULabs#636]
This happened:

![image](https://user-images.githubusercontent.com/7932999/33387988-95d8aafc-d526-11e7-92d9-a286295a919e.png)
(highest altitude was 244m this time, 225m another time, and 2179m when it was flung upwards)

When decoupling the "ascent stage" of this poorly designed lander it was thrown up into the air, before suddenly being flung in a random direction. This seems to be repeatable, one time it flew into the ground, the next time it was flung sort of upwards and exploded due to overheating, this time it exploded in midair (due to a "collision").
Apparently it collided with an SSTUReflectionProbe, multiple times too!

Here's some images of the craft:
![20171129171411_1](https://user-images.githubusercontent.com/7932999/33388779-c501e346-d528-11e7-97d1-245c89fe407f.jpg)
![20171129171414_1](https://user-images.githubusercontent.com/7932999/33388783-c7dfbd04-d528-11e7-8d1a-b1eaf7e1ee0e.jpg)

It might be decoupling strangely due to the engines clipping into the hole in the middle of the fuel tank, but when I tried to test it without SSTU-PBR and TexturesUnlimited, this happened:
![20171129170339_1](https://user-images.githubusercontent.com/7932999/33389145-d40a7348-d529-11e7-8c75-68a631ba74a2.jpg)
![20171129170428_1](https://user-images.githubusercontent.com/7932999/33389195-f6720ce8-d529-11e7-978b-1402f17d65bb.jpg)
It still seems to have engines, they can be activated even though they are invisible and have no colliders. I don't think they had any thrust when I used the hack gravity cheat either.

Sorry about the image spam, and the craft file should be attatched
Happened with SSTU v0.7.39.146, SSTU-PBR 0.1.0.4, TexturesUnlimited 1.0.0.4 (& 0.9.0.3 too I think).
[Test Lander.zip](https://github.com/shadowmage45/SSTULabs/files/1514817/Test.Lander.zip)

**Comment by shadowmage45** [comment]
Testing it without TexturesUnlimited is going to result in things not working -- it is hard-dependency for SSTU (cannot use SSTU without TU).

However, I did recently find and fix a problem that could result in collisions/explosions in the dev branch.  You can try giving this .dll a go (replace the existing TexturesUnlimited.dll in the GameData/000_TexturesUnlimited/Plugins folder) --  https://github.com/shadowmage45/TexturesUnlimited/raw/dev/GameData/000_TexturesUnlimited/Plugins/TexturesUnlimited.dll

Please let me know if that fixes the problem for you.



Apparently Unity has some issues with deleting colliders when I tell it to.  As in... it sometimes flat out ignores the command.

I'm guessing this was happening on a 'revert-to-launch'?  (is the only place that I've been able to see it occur)

**Comment by jamesb6626** [comment]
The updated .dll works great! (the lander's engine was clipping though)

I'm pretty sure it was behaving as I described on every launch (not many) I tried with this craft.
Hopefully now nobody's ships will be exposed to the deadly reflection probes.

**Comment by shadowmage45** [comment]
LoL... I think that is going to be the catch-phrase for the next release:

**Now with 100% fewer deadly Reflection Probes**
