### ISSUE TITLE
MFT-LV blinking

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#639]
See video. The reflection on the tank keeps flickering every second despite there being no change in scenery.

https://www.youtube.com/watch?v=ZNxE61wtQCQ

Let me know if you want my logs.

**Comment by shadowmage45** [comment]
How to duplicate/trigger the issue?  I was not seeing anything like that during playing last night / over the weekend.

Any specific parts, orbital parameters, etc, that are needed to trigger it, or is it doing it 'all the time' on your installation?

Is it only on that specific part, or is it happening on any PBR-shader enabled parts?

(there are some debug fields that you can enable that will let you 'see' what is being rendered for the reflection -- likely that we'll have to enable those in your installation, and get some screenshots of the reflection-debug-sphere to see what is going on)

Edit:
This patch will enable the debug-GUI:

````
@REFLECTION_CONFIG[default]
{
    %debug = true
}
````

Please add that somewhere in your installation (right inside GameData works).  It should enable a new app-launcher button in flight scene (looks like a truck).  When the debug-GUI is open in the flight scene, there should be a button 'toggle debug sphere' -- press it, and observe what is rendered on the sphere.

If you can capture a few screen-shots of what is being rendered in that sphere during the flickering, it will go a long ways towards figuring out what is causing the problems.

**Comment by Jimbodiah** [comment]
Problem found... that DAVD thing with texture replacer doesnt work well with SSTU... so not related to SSTU. my bad
