### ISSUE TITLE
Spherical tank idea

### ISSUE THREAD

**Issue by taterkerman** [shadowmage45/SSTULabs#640]
I Experimented with adding a fairing module to the spherical tank, though I clearly didn't get it right, I could only adjust the top one.
![sphere with fairing](https://user-images.githubusercontent.com/17967275/33647720-b535bec0-da13-11e7-9f70-70ae8c2dc784.png)

You can see the 2-sphere 1.25m tank under there, and the top fairing is set to the diameter of the Orion. (the fairings seems to stem from the bottom (unadjustable given my paste, though I thought I made that "true", so the huge spherical tank I was playing with didn't show the concept)

I was messing with a deep space craft, and decided to use the awesomely cool, spherical tank. Launching is always odd, however, as it needs to be under a fairing. It occurred to me that if I added a fairing (2 sections), I could launch it looking like a regular rocket of large diameter, then separate the side panels. Seems to work, other than my hamfisted screw up of an alternate cfg file.

Is this possible for me to do, or is the gap I see at the top and bottom something that would be a PITA to deal with? It seemed like a cool idea if implementation is as simple as pasting into the cfg file.

If it's not, then ignore, I'll go back to thinking about an SSTU Nova type monster LV (now with retractable petal adapter, and propulsive landing back on Kerbin, a la Phil Bono designs).

**Comment by taterkerman** [comment]
Here's what happens with a larger tank:
![issue](https://user-images.githubusercontent.com/17967275/33648125-a38f3d7a-da15-11e7-9b1a-afebedd281be.png)
That's just the "top" fairing. I pasted the fairing stuff from the MUS tank, then changed a could adjustment things to "true". Seems like adding a fairing might be possible for me, I like the idea (even if the mass isn't even tracked) of imagining the upper stage side panels blowing off to reduce the stage mass of the transfer stages. I made something similar once with a reversed petal adapter.

Note that the actual use case here is HUGE spherical tanks, built in orbit with welding docking ports, with a centrifuge on top, etc as a interplanetary transfer craft. Hence the fairings, as they diameter might be really large.

**Comment by shadowmage45** [comment]
Fairing interaction like you are looking for needs to be built in at the plugin level, as the fairing needs to be told where to start/end, and what diameter to use to line up with the current model selection.  Which it is not in the case of the regular MFT tanks (MUS, MSM, and MSRB all have fairing interaction code, MFT does not).

However, even if the MFT did support fairing interaction, it would not support it like you are proposing.  It would only support it on an 'adapter' basis -- meaning the fairings only cover up from the start of the adapter, to the end of that adapter (e.g. the fairings on the top and bottom of the MUS).

What you are needing is 'full body' + 'adapter' fairing support.  Technically doable (esp. the adapter stuff), but would be a lot of code-side work for a feature that would only be used by a small number of parts, and would in fact require to be setup with 'per-model-selection' type parameterization (each model-definition would have to track if it needed body fairings, along with some data on how they should be positioned).

**Comment by taterkerman** [comment]
Gotcha. I figured if it was just a cfg thing it would be cool. If not, no big deal.
