### ISSUE TITLE
DP0 chutes say unsafe and will not deploy

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#644]
While re-entering the chutes go from unsafe to safe only to go back to unsafe for some reason; so far it seems to happen when velocity drops below 250m/s. I've had it every single time, so should not be hard to reproduce.

This is on an early career save. Don't know if it matters.

Logs here:   http://jimbodiah.com/ksp/sstu/chutes.rar

**Comment by shadowmage45** [comment]
More than likely what is happening is that as the dynamic pressure increase (from air density and velocity), it goes beyond the 'safe' range when lower in the altitude.

Those chutes still have stats as if they were equipped with drogues, so the mains deploy dynamic pressure is set with that in mind -- much lower than it probably should be on a stand-alone part.

The solution to this (in the short term) would be to adjust the dynamic pressure values in the config.  Couple other parts can also use adjustments to their chute stats (SC-A-DM).

(or you can add drogue chutes to your craft, to slow it to ~100m/s for the mains)

**Comment by Jimbodiah** [comment]
I'll test that today and let you know the new values. Thanks!


And as someone I know once said "This is SSTU after all, we don't just add more parts".  mwuhahahahaha

**Comment by Jimbodiah** [comment]
Setting dP to 30k solves the issue, should I send a PR?

**Comment by shadowmage45** [comment]
I'll have to do some testing on it to see what a valid range is -- you need it set high enough to allow for high'ish speed deployment, but not so high that it allows for deploying chutes in upper atmo/suborbital speeds.

30k sounds about right if I'm remembering the initial testing/setup properly, but I'll still need to do some validation on it.

As it is such a simple thing, and I'll need to test it anyway, I wouldn't worry about a PR (would take me longer to merge the PR than make the edit manually).  Thanks for doing some testing and coming up with some values to look at though :)

**Comment by Jimbodiah** [comment]
I can log Q with mechjeb, might be helpfull.

**Comment by Jimbodiah** [comment]
I've gotten up to the 22-25kPa limits upon descent. 

Another option might be to activate a drogue chute instead of only a main chute. That should slow it down enough to not need to increase the max P value?

**Comment by shadowmage45** [comment]
Yes, adding the a drogue chute would probably solve all of the problems.  

I had originally intended that players would add their -own- drogue chutes the craft when using the docking port w/parachute part -- but thinking more on it, there really is no good reason for that requirement.

May require some minor changes to the model -- it only has a single 'parachute cap' mesh at the moment (the bit that jettisons when the chutes are deployed), and it will either need a second one for the drogues, or to move the jettison action to the drogue-chute deployment (so mains would use the same attach points and 'cubby holes' in the model as the drogues).

**Comment by Jimbodiah** [comment]
Aaahhhh... So I am not crazy that I sometime see something fly by my ship :))))   I doubt anyone would mind that extra hatch not being there ;)  Might be an easier fix for the time being without any 3D work?

**Comment by shadowmage45** [comment]
Have updated both DP0 and DP1 to add drogue chutes.  They **will** need further balancing (I don't have time right now to start/restart KSP a bunch just for parachute balance), but they should at least be 'more usable' than they were before.
