### ISSUE TITLE
Request: Recoloring on Radial Science Bay

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#645]
If at all possible, recoloring on the science bay unit?

**Comment by shadowmage45** [comment]
Possible yes (as long as I still have the original art files for it).  Requires texturing work, so certainly won't be done anytime soon.

**Comment by Jimbodiah** [comment]
No rush. Just to complete the recoloring. If you come up with a completely different part while working on the science return thingy then that would be even better (a non-animated inline version perhaps).

**Comment by taterkerman** [comment]
Jimbo, there is the TU patch that upgrades stock parts to TU... Make that work for the service bay used for this purpose.

**Comment by Jimbodiah** [comment]
I'll have a look.

**Comment by shadowmage45** [comment]
>Jimbo, there is the TU patch that upgrades stock parts to TU... Make that work for the service bay used for this purpose.

That isn't going to add recoloring support.  Won't even add proper PBR support (sure, it'll set it to use the shaders, but the textures will be wrong).  

The part will need the textures redone in order to add support for either recoloring or PBR.

**Comment by taterkerman** [comment]
Ah, I hadn't installed that patch (since I have few stock parts that I even see, lol), but it certainly made the other stock parts look nicer.
