### ISSUE TITLE
RCS fuel switch in stock

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#646]
Could the new fuel switch for RCS fuel also be implemented for stock parts, or is it solely SSTU?

**Comment by shadowmage45** [comment]
Its a fairly generic PartModule.  Should be usable on stock parts (the fuel-switching bit at least).  You could even potentially add an 'LFO' or 'XenonElectric' fuel selection to the module with a bit of additional work.

However, I'm doubtful if I will be including any such patches in SSTU.  I've deleted the stock RCS parts in the SSTU-OptionalPatches, and as the regular SSTU install doesn't touch stock parts, any such 'stock-RCS' patch wouldn't have a home anywhere in SSTU.

**Comment by Jimbodiah** [comment]
Just for personal use. I've patched stock parts to use hypergolics, and was just wondering if the fuel switch could be used on the stock parts as well.

**Comment by shadowmage45** [comment]
Yep, should be able to add it to the stock parts without problem.  Look at the ModularServiceModule config for examples of how to set it up without the 'structure/standoff' switching stuff (just for fuel switching).

(this is another module that will be seeing changes in the near future -- splitting the fuel switching off from the structure/standoff functionality)

**Comment by Jimbodiah** [comment]
With the scaling ability and now the awesome recoloring, I no longer have a need to use stock RCS :)))

I didn't notice the rescaling option until yesterday :)

**Comment by shadowmage45** [comment]
Closing question -- fuel switching will be present on all (non-integrated) SSTU RCS parts.
