### ISSUE TITLE
KSP 1.4 - Major SSTU Changes (craft/save breaking)

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#649]
Scheduled for roughly the same time as KSP 1.4 is released (or shortly before/after depending on circumstances and timing).  Nothing guaranteed.

* Modular PartModule rework.  
  * MFT, MSC, MSRB, MUS, MSM -- all use a single centralized 'modular part' setup.
  * ModelDefinitions will list which models are valid nose/mount adapters.  Should not need to add all adapters to part configs, they will be populated automatically (e.g. how MEC populates the mount selection list)
* ShipCore part renaming -- SC-A/B/C/etc renamed
* ShipCore-Engines - renaming -- SSTU-ENG-XXXX
* MFT-A/B model and texture rework
  * Fuel tank models split into 'upper', 'intertank', 'lower' selections.  
  * Redo texture/UV mapping for all parts that use the MFT texture
* VolumeContainer in-flight container editing.
* SC-ENG - re-export with cylinder/cone colliders.  Every. Single. Engine. (gawd I hate Unity)
* ST-HAB - Rotate the windows... or something...

----

This will be the big push towards 'finished' status on any adjusted parts/modules.  The goal is to push the 'finished' parts and code into a state where they will not have any potential need for future adjustment.

Future development after this time should consist solely of adding more parts, models, textures, and should not require any further (substantial) plugin or coding work, except where already planned and accounted for (e.g. ModularParachute code + part setups + integration into existing parts).

---

Timeline:
### 02-26 <-> 03-04
- [x] Create 'mergedModel' capability - merge mulitple .mu's into a single output model.  Inputs must share materials/uv map domains.
- [ ] Finish setup of model-layout module support (rcs/solar).
- [ ] Finish implementation of module-slot parenting support (rcs/solar)
- [ ] Verify that existing model-manipulation stuff all works (tank diameters, sizing, attach-nodes, mass/cost/volume calculation).
- [x] Creation of new MFT tank models.
  * 6 tank segment models
  * 4 piping models (3m, 2m, 3m intertank, 2m intertank)
  * 2 intertank options
  * 2 AO sheets for standard cylinder tanks
- [ ] Creation of new MFT tank textures.
- [ ] Fixing of ModelDefinitions for new tank models
- [ ] Fuel tank part renaming (SC-TANK -> SSTU-TANK)
- [ ] Fixing of texture-set definitions for tank models
- [ ] Other misc model-def and texture set cleanup  
- [ ] Ensure MEC/ISDC/etc module still work with model changes.
- [ ] Adjust/fix any model defs needed for those parts.
- [ ] Initial pass on part renaming -- engines (SC-ENG -> SSTU-ENG)
- [ ] Second pass on part renaming -- command pods (SC-XXXX -> SSTU-SC-XXXX)
  * Will also include new naming scheme for the actual parts.  Rather than arbitrary A/B/C designations, they will either receive codenames or other less generic (e.g. Orion would be SC-O; soyuz SC-S, Apollo SC-A, etc).
- [ ] Model Definition Animation support testing + fixing/implementation of any missing bits.
- [ ] SSTU-ENG PBR texture pass.  Start converting engines to have PBR textures available.
### 03-05 <-> 03-11
- [ ] Initial testing releases, under KSP 1.3.1?
### 03-12 <-> 03-18
- [ ] KSP 1.4 porting work for all mods.
### 03-19 <-> 03-25
- [ ] Initial KSP 1.4 testing versions
### 03-26+
- [ ] First full KSP 1.4 release

---

## Pushed To KSP 1.4 Update
* Redo Fuel Tank Models + Textures (A/B/C)
  * 6/12? lengths per tank type
  * MFT-P-XXX - Tank sections with piping models.
  * MFT-C-XXX - Tank sections without piping models
  * MFT-IP-XXX - Intertank sections, with piping models
  * MFT-IC-XXX - Intertank sections, without piping models
  * MFT-CF-XXX - Cryo-framed tank models (mostly unchanged models, possibly re-UV'd)
  * Updated UV mapping for increased texture density and more 'modular' texture layouts.
* KSP1.4 -- MODELING+TEXTURES+UNITY+CONFIGS - Create new models for:
  * Modular RCS structural standoffs - multiple lengths of basic truss (or stack cubic octagonal struts?).
  * Stand-alone lattice decoupler
  * Octagonal Decoupler
* KSP1.4 -- Model-switch setup changes for LC-POD parts -- greatly simplified PartModule and config setup.
* KSP1.4 -- CONFIGS+MODELING+UNITY - MHS - Stand-alone model
  * Adjust the existing SC-X-CM parts to use stand-alone HS model and textures

**Comment by Jimbodiah** [comment]
If you need anyone to test anything, let me know.

Do you have an idea of what changes are coming in KSP 1.4 that will affect SSTU?

**Comment by shadowmage45** [comment]
Nope, I haven't heard squat from Squad regarding code changes.  Ever since the Take-Two takeover, they've pretty much stopped helping the modding community.

So I won't know until the public pre-releases... at which point it will be far too late to get anything changed in stock code.
