### ISSUE TITLE
Recoloring GUI size not working

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#651]
Mage, I tried setting the GUI length to something higher (640-800) a few times, but it will not rescale. Am I using the wrong parameter perhaps?

    // specifies the total height of the recoloring GUI
    recolorGUITotalHeight = 800

**Comment by shadowmage45** [comment]
Hmm... that -should- work, but perhaps I missed something code-side.  (didn't test it... don't have time to test even half the stuff I work on anymore... too much stuff...)

**Comment by Jimbodiah** [comment]
Moar Stuff!!!  :)

**Comment by shadowmage45** [comment]
Fixed.

Please not that just making the GUI wider will **not** add extra columns to the preset color area.  Really... there is no use in making it wider. (might be possible in the future, with the addition of a ton more code)

But the length adjustment stuff does work now.  (in TU 1.0.0.7)

**Comment by Jimbodiah** [comment]
NP on the width, this is why I lilke having the lsit longer so to fit some more lines of often used colors.

I grew up with the large sized crayola box ;)
