### ISSUE TITLE
New Parts - LV landing legs

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#652]
Single and quad leg sets for MFT-LV fuel tanks (and potentially general use for some variants).

* 'Light' version for use on bare 0+ length tanks.  Works best on 0-length.
  * Apollo LEM-like, bottom hinged locking brace, single piston driving deployment, single piston on main strut for suspension.
  * Suspension line is along the line of the main-strut; might suffer from jitter in some setups - testing needed.
  * 3-piece telescoping main strut.
    * Main upper
    * User configurable extension strut.
    * Suspension driven strut (may be 'locked')
![](https://i.imgur.com/eTQ28ZJ.gif)

* 'Medium' version for use on bare 0+ length tanks.  Works best on 1+length.
  * Like the light version, this one will attach to the bracing on the bottom of the tank, as well as the interior struts on the tank.
  * Exact geometry undecided, will likely be similar to light version with more robust looking attachment system and/or longer struts.

* 'Heavy' version for use on paneled tanks.
  * Current concepts will fold downards for deployment, possibly with the leg folded in half.
  * Main leg consists of two outer struts.  Single central strut drives deployment and handles suspension actuation.
  * User configurable final deployment angle
  * Suspension actuation will be vertical
![](https://i.imgur.com/p5gRMtK.png)
![](https://i.imgur.com/Ww8dgUY.png)

**Comment by taterkerman** [comment]
![bxl0x1o](https://user-images.githubusercontent.com/17967275/34135154-16eed05e-e41c-11e7-8168-f13925d35869.png)
![diagram_main_by_william_black-daiix0t](https://user-images.githubusercontent.com/17967275/34135157-1acb4d24-e41c-11e7-85ee-c6f4d808f486.jpg)
![mkjuigw-2](https://user-images.githubusercontent.com/17967275/34135158-1c849364-e41c-11e7-8650-bdd62c1d8779.png)
![tlspkqo](https://user-images.githubusercontent.com/17967275/34135161-1e629014-e41c-11e7-9e24-a025ab8e150b.png)
![163697main_lander_hi](https://user-images.githubusercontent.com/17967275/34135169-2a77fdd0-e41c-11e7-9d17-2095256152b6.jpg)

**Comment by taterkerman** [comment]
![4 moon](https://user-images.githubusercontent.com/17967275/34135224-7cd2f33c-e41c-11e7-9f48-87257fcb3827.jpg)
![bonestell_von_braun_colliers_1950s_moonlander_by_paul_lloyd-d7p60y9](https://user-images.githubusercontent.com/17967275/34135231-8d6afc80-e41c-11e7-8612-56e7d0a99da2.jpg)

**Comment by Jimbodiah** [comment]
![kerbodyne_legs](https://user-images.githubusercontent.com/16107012/34135363-857bc9e8-e460-11e7-86b9-47a2f87f872a.jpg)

**Comment by Jimbodiah** [comment]
More for stand-alone legs for main cores:

![spacex-rocket-landing-531752474](https://user-images.githubusercontent.com/16107012/34135386-a313b0ce-e460-11e7-97b4-18736ac4437e.jpg)

**Comment by taterkerman** [comment]
![20141119_mars-lander_f840-e1416665797428](https://user-images.githubusercontent.com/17967275/34135394-aa7db6ea-e41d-11e7-94dc-c2a3446f8359.png)
^^this guy is an inflatable on top of the tank and service components.

![mars_lander](https://user-images.githubusercontent.com/17967275/34135396-ac3025ae-e41d-11e7-9afd-4daa0df0b2f3.jpg)

**Comment by taterkerman** [comment]
![lunac](https://user-images.githubusercontent.com/17967275/34135905-96a53b0e-e420-11e7-8658-8f1cbefcfd9c.jpg)
The above is an interesting idea for a quad leg variant for MFT-A tanks. It could be a cylinder with the cutout as shown. as well as containers for propellants. Perhaps the landing gear tank version has a recess for engine mounting...

![lunarlander_4view](https://user-images.githubusercontent.com/17967275/34135907-981dec56-e420-11e7-8a5f-6564b179d7b9.jpg)

**Comment by taterkerman** [comment]
https://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/19750016730.pdf

**Comment by taterkerman** [comment]
![alina-and-the-alq-close](https://user-images.githubusercontent.com/17967275/34138016-c747ca88-e42a-11e7-9be9-2a8bd1071169.jpeg)

**Comment by taterkerman** [comment]
Look at the Mars lander concept that looks a lot like Altair. The bottom "LC tank" is in fact a service bay with the science gear, folder rover, etc.

That Mars lander is using the RCS engines for landing, hence the double bells facing downwards...

**Comment by taterkerman** [comment]
I'm liking these, partially because of the retro look, partially because the other bits already exist...
![space_tug_at_the_moon](https://user-images.githubusercontent.com/17967275/34142832-9a5a1dd4-e446-11e7-86a2-e8fc474ae554.jpg)


![stufftoblowyourmind-23-2013-08-landed](https://user-images.githubusercontent.com/17967275/34142977-74ef43c0-e447-11e7-9b5b-d7599a001179.jpg)

![space_tug_parts](https://user-images.githubusercontent.com/17967275/34143251-0405738a-e449-11e7-9b07-fb997bd7f007.jpg)

**Comment by taterkerman** [comment]
The Space Tug (which I have always loved, lol) propulsion unit is a pretty cool part idea for landing legs on a booster form factor (MFT-A).  I'm having difficulty figuring out how it folds, however. The middle, landed picture has part with a cover that folds like landing gear against the side, and the rest looks like it hangs below inside the engine shroud. 

Still, it's pretty cool. The other methods look like SpaceX, or maybe BO (the latter is already sort of in the KF mod).

**Comment by taterkerman** [comment]
![1970s_boeing_lunar_ferry_by_paul_lloyd-d7p601h](https://user-images.githubusercontent.com/17967275/34170351-c892c2f8-e4a7-11e7-8572-a775a1e41948.jpg)

https://paul-lloyd.deviantart.com/gallery/

The wide stance is particularly nice for some applications.

**Comment by taterkerman** [comment]
![lem-gemini-direct](https://user-images.githubusercontent.com/17967275/34193884-43fd2fbc-e513-11e7-9b44-d1a4f21bf42b.jpg)
Intriguing slot interface for a flush leg. Note that this is a Gemini concept lander.

**Comment by taterkerman** [comment]
![mavlander_persp](https://user-images.githubusercontent.com/17967275/34269119-6c9bf0b0-e640-11e7-97cd-fd4c28e27d9d.png)

Makes me wonder about a LC tank mount that is the model you already have for the tank, minus the tanks, with reset nodes for engines, or gear. In the case of engines, the node could in fact be normal, and the engine layout designed to fit (so a cluster of 4 small engines (as above) might put 2 next to each other in 2 opposite quadrants, and adjust via the spacing control).

**Comment by taterkerman** [comment]
I
Might have to make the nuclear ferry that goes with the space tug in sstu tonight, just because space tug is so frikin awesome, but I can easily make the ferry with stuff we have :) 

In my ksp world, nukes will probably get garish paint to warn astronauts to avoid the “hot” bits.

**Comment by Jimbodiah** [comment]
Garish paint: "We can do that!"

Recoloring is the best thing in KSP since KSP.

**Comment by taterkerman** [comment]
The hardest part is attaching the cargo, tug, etc as shown in images.

**Comment by Pappystein** [comment]
A simple thought on Landing legs.   What they are for determines geometry more than anything else.   Planets with higher gravity will need a leg that is taller than it is wide.   Planets with a low gravity will need a lighter structure that is WIDER than it is tall (both as measured from the Center-line of the craft in question.

Currently in Game we have Mun level lander legs.....   But no Eve level lander legs (not that you would want to spend a bunch of time on Eve but still....
For comparison look at the complex and tall landing legs on the Lunar landing Trainer vs the actual wide  simple and short legs on the Lunar lander...
