### ISSUE TITLE
RMB: Recolor not present on clone of part

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#654]
I clone the RMB to create my own science bay with other experiments, but for some reason the recoloring functionality is no longer present in the cloned part. The part is present in the game and functions properly otherwise. I don't have these issues with other cloned parts. Is there something different with this part?

**Comment by Jimbodiah** [comment]
+PART[SSTU-SC-GEN-RMB]
{
	@name = RadialScienceBay_mk1
	@title = Radial Science Bay mkI
	@description = Like a tricorder, but better!
    @manufacturer = JPL

    @entryCost = 10000
    @cost = 1000
    @mass = 0.1
    @TechRequired = start

    %explosionPotential = 0
	@crashTolerance = 12
	@maxTemp = 2400

    !MODULE[ModuleScienceExperiment] {}


// MYSTERY GOO

	MODULE
	{
		name = ModuleScienceExperiment
		experimentID = mysteryGoo
		experimentActionName = Observe Mystery Goo
		resetActionName = Reset Goo Canister
		useStaging = False
		useActionGroups = True
		hideUIwhenUnavailable = True
		xmitDataScalar = 0.3
		FxModules = 0
		dataIsCollectable = True
		collectActionName = Collect Data
		interactionRange = 1.5
		usageReqMaskInternal = 1
		usageReqMaskExternal = 8
	}
}

**Comment by Jimbodiah** [comment]
Jesus Christ, for Guthub being code oriented, it's a disaster to include any in the messages. What a cludge.

**Comment by shadowmage45** [comment]
You just need to wrap you code in blocks of   \````
e.g.
\````
code here
\````

will display like:
````
code here
````

----

Now, the actual problem is -- you've changed the part name in your clone.  The original patch that adds recoloring to that part only specifies a single target.  You'll need to fix both the regular recolor patch + the PBR conversion patch to include the new part name.


https://github.com/shadowmage45/SSTULabs/blob/master/GameData/SSTU-PBR/RecoloringConversion/TextureSets-SC-GEN-RMB.cfg#L1

https://github.com/shadowmage45/SSTULabs/blob/master/GameData/SSTU/Data/TextureSets/TextureSets-SC-GEN-RMB.cfg#L1

**Comment by Jimbodiah** [comment]
Thanks. 

The werid thing is that I've done this for other parts (orion, lots of cos modules etc) but their recoloring still works for some reason.

**Comment by shadowmage45** [comment]
It really shouldn't work for other stand-alone parts either.  Those patches are all applied to only a single part.  (it could also be a -when- thing.... WHEN is your cloning patch being ran -- before or after the texture set module is added to the part?)

Now, patching the SSTU_MODEL stuff is a different affair -- those track the texture sets internally, so if you re-use the defined model name (or clone the entire model and give it a new name), it'll carry over the texture sets just fine.

**Comment by Jimbodiah** [comment]
Pffrrttt.....  I forget the   :AFTER[SSTU]  like the noob that I am.
