### ISSUE TITLE
RD-180 Gimbal

### ISSUE THREAD

**Issue by Nightside101010** [shadowmage45/SSTULabs#655]
I noticed while playing with Real Scale Boosters that a single RD-180 from that mod has roll control while a single **SSTU-RD-180 does not have roll control**.
Is this intentional/limitation/oversight or did I miss some setting adjustment?

I don't know offhand if the real engine has this capability, but I would assume so.

**Comment by shadowmage45** [comment]
I'm not limiting it in the config, so this would appear to be an issue with the stock gimbal module.

````
MODULE
{
	name = ModuleGimbal
	gimbalTransformName = RD-180-Gimbal
	gimbalRange = 5
	useGimbalResponseSpeed = false
}
````

If this in fact a problem, there is nothing that I can do to fix it.

----

Have you verified that the 'roll' control is enabled in the gimbals 'advanced tweakables' options?

**Comment by shadowmage45** [comment]
This must be an issue with RO, as it works fine in stock...
![screenshot8](https://user-images.githubusercontent.com/1503399/46025546-6cf68700-c0a6-11e8-943f-94afe7b1e750.png)
