### ISSUE TITLE
Fuelchange code, still works?

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#657]
I found this bit in one of my old MM patches. The part has some issues and is not showing up, but after looking at why I stumbled upon this bit of patch code. Would this still work?

    @MODULE[SSTUVolumeContainer]
    {
	    @enableContainerEdit = true
	    @enableFuelTypeChange = true
    }

**Comment by shadowmage45** [comment]
Should still be functional, yes.  All that should really do is make sure the GUI can be opened, and that the 'fuel type' slider is present.

What part is having problems?

**Comment by Jimbodiah** [comment]
My own patched/cloned part, so no concern.

**Comment by Jimbodiah** [comment]
Ah, this is actually a stock setting for sstu tanks... I thought it allowed in-game reconfiguration of MFT resources.
