### ISSUE TITLE
SC-B-CM - Pod blackens as ablator is used

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#66]
Should not happen, at least not on the upper pod mesh...

Re-implementation of heat-shield module is needed for my purposes anyway.
### Requirements:
- Configurable heat-shield vector; heat shield capability proportional to angle compared to this vector
- Configurable heat-shield 'surround' angle; determine how far off-heat-shield vector movement must be before it starts losing effectiveness
- Configurable 'heat-shield mass' value, to simulate thermal soak-and-eject from the heat shield
- Configurable heat-shield type; soak or ablate
- Use 'realistic' values if possible.  Heat rejection for ablator will be based off of its HSP; heat conductivity between heat-shield and part internal will be based on (heat above ablation temp / remaining soak capacity), heat-capacity of shield will be based on its mass (density?).

**Comment by Jimbodiah** [comment]
I just noticed this, but it is kind of cool to see it scorched after a violent re-entry.

**Comment by shadowmage45** [comment]
I wouldn't mind if it was just violent re-entries; but it is anytime the ablator is depleted, even if you just remove some in the VAB (which I consider a stock bug...); unfortunately, it doesn't look like stock is interested in fixing it.

**Comment by shadowmage45** [comment]
Will rework this when I am working on redoing the SC-B-CM.  Technically it is not the CM itself, but the ablator/heat shield module that I am using that I need to update.

**Comment by FiiZzioN** [comment]
If you are still having issues with this, you can add these lines to disable the darkening. 

```
    charMin = 1.0 // Disable ablative darkening
    charMax = 1.0 // Ditto
    charAlpha = 0.0 
```

If this doesn't help you since you have a lot of custom modules, well, at least I had good intentions, lmao!

**Comment by shadowmage45** [comment]
Thanks for the info -- will keep it in mind if I go back to using the stock modules.

With my most recent releases I've swapped over to a custom heat-shield module that includes directional functionality (e.g. only shield stuff/ablate if oriented properly) and eaiser tuning of stats (using a floatCurve rather than an exponential function).

So, no longer an issue with my new heat-shield module.  There is currently no darkening effect enabled, but as my heat-shields are generally black anyway, it wouldn't be very visible even if it were implemented.

One thing I would like to do, but will likely wait until 1.1, is implementing a 'damage' or 'scorch' texture that can be overlaid on the command pod exterior (not just full-mesh blackening);  waiting for 1.1 due to their support for many additional textures/etc in the default shader (including multiple detail textures for any given mesh, which is what I would be needing).

**Comment by FiiZzioN** [comment]
What's interesting to me is that that your heatshield module is working exactly as the old version of DeadlyReentry worked before stock reentry heating was added. I mean, literally the same, float curves, pod direction, etc... I, for one, like his old method and your new method wayyy more than stock. Keep it up man! 

If you care, here's how his settings worked:

```
    MODULE
    {
        name = ModuleHeatShield
        direction = 0, -1, 0 // bottom of pod
        reflective = 0.05 // 5% of heat is ignored at correct angle
        ablative = AblativeShielding
        loss
        { // loss is based on the shockwave temperature (also based on density)
            key = 650 0 // start ablating at 650 degrees C
            key = 1000 320 // peak ablation at 1000 degrees C
            key = 3000 400 // max ablation at 3000 degrees C
        }
        dissipation
        { // dissipation is based on the part's current temperature
                key = 300 0 // begin dissipating at 300 degrees C
                key = 500 90 // maximum dissipation at 500 degrees C
        }
    }
```
