### ISSUE TITLE
Docking port configs still in station parts

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#661]
The integrated ports were removed from all the COS/DOS parts, but their code still remains. I came across these while cleaning up the configs for my own patches.

`	DOCK
	{
		name = Mount-None
	}
	DOCK
	{
		name = Dock-Small
	}
	DOCK
	{
		name = Dock-Medium
	}
	DOCK
	{
		name = Dock-Large
	}
`

Dito with the upgrade functionality between small-medium-large ports for these same parts.

Do you want me to do a pass and remove those pieces from the cfg files?

**Comment by shadowmage45** [comment]
Hmm... sure I suppose.  Mostly it would depend on how long until KSP 1.4.  If more than a month out, then it is likely that I'll publish at least one more SSTU update for KSP 1.3.1.  And it seems likely that KSP 1.4 is at least a few months away.

I already have / will be removing those configs in the KSP 1.4 branch (as every single part is having a config pass done on it, cleaning up old stuff).

**Comment by Jimbodiah** [comment]
Free labor, abuse it! ;)

**Comment by Jimbodiah** [comment]
I'll do one PR, if you can check that I did not remove anything you didn't want removed? Then I will do all the other parts as well.
