### ISSUE TITLE
Loading an in-flight savegame misaligns the ISDC's SRBs

### ISSUE THREAD

**Issue by MikeOnTea** [shadowmage45/SSTULabs#666]
Position looks correct, but their direction is wrong.
Sadly github won't let me upload a screenshot right now... will do that once github works again.

**Comment by shadowmage45** [comment]
Yes pictures please.  And a list of the steps to reliably reproduce the problem.

**Comment by MikeOnTea** [comment]
Steps to reproduce:
1) make a simple craft with ISDC
2) "Launch" it
3) Press quicksave and then quickload on the pad, don't even have to liftoff

Craft before quickload:
![Craft before quickload](https://s10.postimg.org/88l540ubd/ISDC1.jpg)
Craft after quickload (different camera angle, might just be the orientation of the SRBs that got messed with, their position looks roughly correct):
![Craft after quickload](https://s10.postimg.org/a0e3yxt3t/ISDC2.jpg)

This is not just a visual bug, their thrust vector changed along with their visuals.

**Comment by shadowmage45** [comment]
Interesting... I must have misused some of the transform operations in calculating of the orientation (and/or somehow the operation is being ran twice on vesssel re-load... which wouldn't surprise me given KSP's crappy loading sequence(s))

**Comment by Jimbodiah** [comment]
Issue #666, no good can come of this.
