### ISSUE TITLE
PR testing in my fork

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#671]
Mage. Besides the LS modintegrations, I've tested the 3rd party resource adds and the removed port parts; they work fine as far as I can tell.  I can try to test the USI/TAC LS mod integrations, but I don't think anything should be wrong seeing all the others work fine so far.

**Comment by shadowmage45** [comment]
Sounds good -- shouldn't be any difference between the others and TAC/USI.
