### ISSUE TITLE
Licensing and redistribution

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#673]
Mage,

I haven't really thought of this before as I mainly used them all for myself, but I have my patch pack up on SpaceDock now and never gave a thought to licensing (the pirate that I am). Is it okay what I am doing?

**Comment by shadowmage45** [comment]
As long as you are just distributing config files, you can use whatever license you want.

If you are distributing any of SSTU's assets (plugin, textures, models), those particular files would need to be licensed using the same setup as in SSTU -- GPL for code, CC-BY-NC-SA for textures/models.

**Comment by Jimbodiah** [comment]
Just MM patches to clone or alter your parts, no models or plugins of any kind are included/copied etc.

**Comment by shadowmage45** [comment]
You should be able to pick a license for your own works then.  

The default (no license listed) is all-rights reserved.  If you wanted something more permissive than that, I would recommend one of the CC variants, MIT, or even releasing to the public domain.

**Comment by Jimbodiah** [comment]
My own licensing is not an issue, just wanted to check you were okay with me bringing out patches using sstu as a resource ;)
