### ISSUE TITLE
RF mod integration error

### ISSUE THREAD

**Issue by Starwaster** [shadowmage45/SSTULabs#677]
The patch file for Real Fuels tries to patch part SSTU-SC-TANK-MUS-* which matches on no part currently existing in SSTU. Probably was looking for SSTU-SC-TANK-MUS.

https://github.com/shadowmage45/SSTULabs/blob/master/GameData/SSTU/ModIntegration/RealFuels/RF.cfg

**Comment by Jimbodiah** [comment]
I just made a PR to change it.
