### ISSUE TITLE
Radial booster decoupler changes?

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#679]
Has anything been changed with the radial decouplers in regards to how the jetisson engines work? My boosters keep pointing inwards upon seperation, destroying the main core.

It seems to be more prone in SRBs than in liquid fuel boosters.

**Comment by shadowmage45** [comment]
Nope, nothing has changed on them in quite a long time.

**Comment by Jimbodiah** [comment]
Ok, thanks. Just checking.
