### ISSUE TITLE
New Parts - SC-A-CM, SC-A-SM, SC-A-BPC(LAS/LES)

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#68]
Re-work/redo the 2.5M Apollo-inspired SC-A Command Module, Service Module, and add a new BPC/LAS/LES (as the stock one doesn't look/work properly).
### Goal:
- 2.5m Low-Part Count Command Pod and Service Module
- Three total parts for the system, four with a decoupler below the SM
  - CM - RCS, Heat Shield, Light, Transmitter, Probe Core, Docking Port, Parachutes, Reaction Wheels, MonoPropellant, ElectricCharge, Fuel Cell, Decoupler, Fairing(2nd bottom node)
  - SM - RCS, Light, Transmitter, Probe Core, Reaction Wheels, MonoPropellant, Main Engine, Fairing (bottom node)
  - BPC - Jettison Motor(jet fuel), Abort Motor(solid fuel), Auto-Depletion Decoupler
### Parts:
- SC-A-CM - Orbital/re-entry capable 'standard' pod
- SC-A-CMX - (no-heatshield command pod variant)
- SC-A-SM - Standard Service Module
- SC-A-BPC -  Purpose-built LAS/LES
### Models:
- SC-A-CM
  - Pod
    - Cap
  - HeatShield
- SC-PAR-GENERIC (parachute model, from existing + existing texture)
- SC-GEN-DP-0P
- SC-GEN-RCS-4F-V
- SC-GEN-HGA (High-Gain-Antenna array)
- SC-ENG-AJ-10-137 (SM Main engine)
### Requirements:
- New parachute module that can handle both drogue + main chutes, without the implementation problems of the stock module (animations, drag cubes, etc)
- New lighting module, should be based similar to the emissive module, but with control for both emissive texture (by mesh name(s)), and light-transform control by transform name(s).
- New Decoupler module - auto-decouple on depletion of the specified fuel in the part, perhaps with configurable delay, and ability to auto-trigger an engines-module through engine-mode-switch
- New Resource - Jettison Fuel - Duplicate of SolidFuel, to be used by jettison motors (esp. in places where the part may already contain SolidFuel but still need jettison capability).
- New HeatShield module - stock one ... is no good
### TODO:
- SM - finish texture; needs details on bottom, top/interior, and heat-shield.
- ENG - finish engine texture; bell looks fine for use on SM, but the rest of the engine is unfinished.
- RCS - finish texture; has only base flat color - should include normal map? (probably not needed) -- so diff/spec only
- Cleanup modules code, have a bit of new info regarding thermals
### DONE:
- Finish SC-A-CM model (add docking light, updated docking port)
- Re-export parachute model from unity with material/texture assigned.
- Lighting module -  basic implementation done
- Parachute Module - basic implementation done
- SM - rework the HGA geometry - slightly higher tri count, much greater detail and cleaner mesh flow.
- CM - HeatShield Module
- CM - Rework 0.625m geometry, Unwrap and Texture new Docking Port model(s)
- BPC - Auto-decoupler module -- should be simple enough
- BPC - JettisonFuel resource definition -- need to investigate possible conflicts with other mods
  - Perhaps name it SSTUJettisonFuel?
- BPC - Create BPC/LAS/LES model
- SM - Rework SM Model (needs RCS + AJ-10 models)
- SM - AJ-10-137 Model - not even really started
- SM - re-export to unity for the geometry changes to the heat-shield
- SM - Finish RCS models - geo, unwrap, texture
  - geometry
  - unwrap
  - textures

**Comment by lynwoodm** [comment]
Cannot wait to see these parts in the public release. The old photos of these systems looked very functional and would be fun to implement in game. Low part count always is a big plus in my book. If you need someone to test these, feel free to give me a shout.
