### ISSUE TITLE
Request: Center RBDC on main body

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#681]
Right now it looks really weird.

I've added a nose and mount to the MFT-A and the RBDC centers really funky.

**Comment by Jimbodiah** [comment]
![screen shot 02-18-18 at 06 02 pm](https://user-images.githubusercontent.com/16107012/36354907-4f0d529a-14db-11e8-9138-7418b184719f.JPG)

**Comment by shadowmage45** [comment]
As has been stated before -- use the stock offset widgets.

The tanks attach at their COM.  When you add a nose (or mount) to the booster it changes the COM up/down, which is why they get centered like shown in your image.
