### ISSUE TITLE
not loading last ver as of 3/19/18

### ISSUE THREAD

**Issue by pukendog** [shadowmage45/SSTULabs#689]
not loading recent ver as of 3/19/18. Gets stuck at SSTU. Too long waiting for KSP to start up, or not at all. Had to remove Mod.

**Comment by shadowmage45** [comment]
Logs?

Most likely problem is a version mismatch.   Mod is not updated for KSP 1.4.1 yet.

**Comment by wicaksono** [comment]
I can't play with this awesome mods... Can you update it shadow?

**Comment by Jimbodiah** [comment]
If you can't play without it, then why did you upgrade to 1.4?
