### ISSUE TITLE
Loading screen Issue

### ISSUE THREAD

**Issue by buster1234567** [shadowmage45/SSTULabs#691]
Upon loading the assets for the mod it dosnt load past ST-CFG-A.

Tried reinstalling, i will have to uninstall for now :(

**Comment by shadowmage45** [comment]
Sounds like you are trying to use SSTU with KSP 1.4.1.  It is not yet available for that version of KSP.

**Comment by buster1234567** [comment]
damm, i will have to downgrade then :)
