### ISSUE TITLE
Container GUI question

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#698]
Is there a limit to the number of fuel types (or lines/rows) that can are presented in the GUI?

**Comment by shadowmage45** [comment]
Fuel types (e.g. LFO), or resources?

Either way, it should be unlimited.  Adding more will push the rest of the GUI elements downward.

**Comment by Jimbodiah** [comment]
Like LFO / Hydrolox that will add multiple fuels at once.

OK, thanks!  I have exactly all lines filled and a new type was not showing up, so I was not sure if there is a max number of lines (at 4 now I think). I'll check what I am doing wrong on the new fueltype then (MKS with 27 resources inside).
