### ISSUE TITLE
SSTUVolumeContainer for SM and CM?

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#699]
Would it be an option to use the VolumeContainer for the service modules and pods instead of fixed resources? This would allow user based addition of LS or other resources and do away with any LS mod integrations for these parts?

**Comment by Jimbodiah** [comment]
;)

![screen shot 04-14-18 at 03 49 pm](https://user-images.githubusercontent.com/16107012/38768961-8b5857d6-3ffb-11e8-9628-0c49f4195bc4.JPG)

**Comment by shadowmage45** [comment]
Possible, yes.  Something I'm interested in adding -- not so much.  It breaks the carefully calculated balance on those parts (i.e. mass ratios and total craft dV), while not actually adding anything to their functionality.

Really the only time I could see it being useful is when life-support mods are installed... but even then... I would only use it to reduce the amount of supplies.... which can be accomplished just fine with the stock resource-control sliders.

---

IF I were to add it to the parts, I would add 'locked' containers for the propellants (both engine and RCS) (meaning they couldn't edit it with the GUI).  So basically, it might as well not even be present.

**Comment by Jimbodiah** [comment]
I have mine set up so that when it has only hypergolics it has the same dV as your stock part, but adding LS resources means less fuel and less dV. I've also not added anything other than LS to the SM (like ore/NF fuels etc) as there is no need for those.

My main reason was so that I could add more resources for an RSS scaled system (4x the LS supplies needed of stock LS) moon mission, or have more fuel and less supplies to do rescue missions in LEO.

I could revisit the LS supplies patches to add RSS multipliers instead though, but the LS patch creates volume where there was none imo.

**Comment by shadowmage45** [comment]
I balance my stock life support patches around the following theory:
_The stock parts already include mass for life support_.   
Thus, when I apply life-support patches, I will reduce the dry mass of the part, and add volume if necessary.  For most parts that would include life-support (in SSTU) only a small portion of the parts actual volume is dedicated to resources, so increasing this usage a bit to include LS supplies is well within the bounds of realism.
E.G. The Apollo SM makes terrible use of its real volume for propellants alone, and could easily accommodate oxygen and/or water tanks.  The volume used in the config is far less than what is available in the model.

**Comment by Jimbodiah** [comment]
Want me to add multipliers for RSS to the LS patches. I can see what the mass difference is and subtract that; bacisally 4x the stock LS resources.

**Comment by shadowmage45** [comment]
So.... for other reasons it looks like this change will actually be coming to many of the CM parts (using VolumeContainer system).

I've recently changed the ModularHeatShield code to interact with the VolumeContainer setup for its ablator use.  Which will mean that ablator, and all other resources on the heat-shield equipped pods, will be done through the VolumeContainer system.

I will likely also be adding the RCS-FuelSwitch module to the CM parts now that VolumeContainer will be on them, as now it will be possible to allow for adjusting of the fuels in the pod parts.

Combined with the changes to VolumeContainer using straight up 'volume' in the CONTAINER blocks, it should also make it quite a bit easier to do life-support patches.  Find out the ratios of resources needed, and the volume of those resources for a single kerbal-day, and then you can simply specify (volume * crew * days) in a the volume entry of a new CONTAINER block.

**Comment by Jimbodiah** [comment]
Awesome!!!!!!
