### ISSUE TITLE
RCS unit ISP determined in plugin?

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#704]
I have cloned the RCS units to replace the ones in NearFuture Propulsion (recoloring for the win!)... I have it changing fuel type to Xe/Li/Ar instead of MP/HG, and even ISP reflects the higher value, yet the fuel rate still shows the original rate as per the stock ISP for MP.  Is this overwritten in the plugin perhaps due to the fuel switch?

**Comment by shadowmage45** [comment]
Rather the problem is backwards of what you describe.  The plugin ignores ISP entirely.  It doesn't touch it at all.
https://github.com/shadowmage45/SSTULabs/blob/master/Plugin/SSTUTools/SSTUTools/Module/SSTUModularRCS.cs#L261

ISP should be solely determined by the stock module config setting for the ModuleRCS:
````
[KSPField]
public FloatCurve atmosphereCurve;
````

**Comment by shadowmage45** [comment]
Could you post the config for the part from the module-manager cache?  This should show me what the config looks like after module-manager is done with all patches.  
(the  module-manager cache is simply a text file containing all post-patch configs in a single combined file; you can search through the file by part-name to find the config for the specific part)

**Comment by Jimbodiah** [comment]
I think it's a KSP override, as I just checked Nertea's parts and they show the same results.

ISP=200     0.098 units/s
ISP=2000   0.095 units/s


I'll ask Nertea if he knows about this.

**Comment by shadowmage45** [comment]
Also, IIRC, the ISP (and mass flow) will always report strange values when EC is one of the propellants.

**Comment by shadowmage45** [comment]
Semi-dupe of #659 - relegating conversation to there.
