### ISSUE TITLE
DP0/1: Check if anything is docked

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#706]
I'm using MKS where you can delete parts and noticed when I deleted a part that was docked to a DP1 port, that I could no longer dock to this port. Most likely the port was not undocked and thinks there is still something there, related to the docking node issues we had in the past?

Is there any way to check if anything it acutally docked, and reset the status when there is no longer anything there?

**Comment by shadowmage45** [comment]
That is actually a bug report you should file with MKS.  Nothing that I can do about it, as I don't control the code that is doing the part-removal.
(I would first check to see if the problem exists with stock docking ports; likely it does)

**Comment by Jimbodiah** [comment]
Will do.
