### ISSUE TITLE
Parts will not show up

### ISSUE THREAD

**Issue by SL2002** [shadowmage45/SSTULabs#708]
I go through the normal procedure for mod installation but the parts won't show up. I have tried the tricks I normally use but they won't work. Any advice? Could you also update for 1.4.2?

**Comment by shadowmage45** [comment]
Logs?  I can't even guess at what could be going on without a log file (the KSP.log file from the main KSP directory).  You can drag+drop directly into the reply box and it should attach the file to the reply.

Further requests for updates will result in being blocked from the repository.  This is not the place for such requests;  this is the place for submitting bugs or contributing to the mod.

**Comment by SL2002** [comment]
It helps, but now it will not load and is stuck on the file ST-CFG-A under SSTU, Game Data, SSTU, Assets

**Comment by shadowmage45** [comment]
My first guess is that you are on KSP 1.4+?    If so, that would be your problem.  SSTU is only compatible with KSP 1.3.x.
My second guess is that you did not install the requisite dependencies -- ModuleManager, CommunityResourcePack, TexturesUnlimited, KSPWheel (all included in the releases).
....But those are just complete guesses.

If you could provide the log file as requested, I might be able to help you get the problem sorted out much more efficiently.

**Comment by SL2002** [comment]
Thanks, it works now.
