### ISSUE TITLE
1.4 dev branch?

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#710]
Hi John,

Is the dev branch the actual 1.4 branch you are using? ie can I start going ove rthe mod integrations there?

**Comment by shadowmage45** [comment]
Yes, that is the correct branch ( https://github.com/shadowmage45/SSTULabs/tree/dev ).

SSTU-TANKS-MFT-X should be more or less ready for patching, though the MUS may still have some changes to its container layout to facilitate the 'support tank' setup for rcs propellants.

SSTU-ST-XXX StationCore parts are still WIP, 
SSTU-SC-XXX pods likely will have their part names changed soon, so I would hold off on those.

----

Yes you can add duplicate resources to the tanks.  I would still consider it an error (and it is logged as such), but it shouldn't crash the game/break the parts.  Duplicate definitions will simply be ignored.

**Comment by Jimbodiah** [comment]
Would you still prefer I keep the exceptions in place like they are now? Not sure if it is tempting the beast to define them multiple times? KSP isn't exactly the most stable platform performance wise.

BTW: I can delete the current PRs and just make new ones for the dev build instead.

**Comment by shadowmage45** [comment]
>Would you still prefer I keep the exceptions in place like they are now? Not sure if it is tempting the beast to define them multiple times? KSP isn't exactly the most stable platform performance wise.

Duplicates should have zero impact on performance at run-time, and minimal impact during startup.  Might add a few extra ms to the loading time, but nothing of consequence.

Probably worth the convenience and speed in writing configs/patches to just not worry about duplicates and let the code take care of it.

>BTW: I can delete the current PRs and just make new ones for the dev build instead.

Either way, whatever is easiest and fastest for you.  You should be able to 'edit' the existing PRs to re-target them at the 'dev' branch and update the names, all through the GitHub web-interface.

**Comment by Jimbodiah** [comment]
Will do, I will slap you with PRs until you are sick of me ;)    Nah, I'll try the branch thing again like last time.

**Comment by Jimbodiah** [comment]
PR incoming, wasn't much work really

**Comment by shadowmage45** [comment]
Good to hear -- I'll take a quick look over it and see about merging the existing stuff into the dev branch now (Rather than later), so that it should be available for testing asap.

Speaking of testing -- you are free to grab the contents of the 'dev' branch for actual testing anytime you want, as long as you keep in mind that it is very much still a WIP.  (okay, so its probably still a bit early for real testing and bug-reporting, but probably far enough along that you could give some of the new features a try)

**Comment by Jimbodiah** [comment]
Sounds cool!  I'll give it a spin this weekend perhaps.
