### ISSUE TITLE
Apollo CM Sinks in Water & Overheats during re-entry. 

### ISSUE THREAD

**Issue by KamikazeKricket** [shadowmage45/SSTULabs#720]
When I landed in the ocean coming back from a Mun mission, the Apollo command module sunk! During the same mission the Apollo CM was over heating during re-entry, not to a failure level, but it was close. The ablator wasn’t decreasing either. This was the re-entry version of the CM too.

**Comment by shadowmage45** [comment]
Should be fixed in yesterdays release.  Please let me know if you experience further issues.

Was being caused by the heat-shield module throwing errors constantly, which bugs out other parts of KSP (like the buoyancy code).
