### ISSUE TITLE
"SSTU - TANK - MUS" exhibits negative mass upon adding solar array

### ISSUE THREAD

**Issue by Teslamax** [shadowmage45/SSTULabs#724]
Adding a solar array to the modular upper stage subtracts about 2,499 kg from it's mass.

I created a second KSP install with almost no mods other than SSTU 0.8.42.152 .

I tried different combinations/permutations until discovering the solar array as the culprit.

(If you don't mind watching a [terrible 5-minute video](www.youtube.com/watch?v=EycTK7hrFGs) of me exhibiting this problem,

**Comment by shadowmage45** [comment]
Looks like there was an error in both the code and configs that were both causing parts of this problem.

Have fixed the plugin code and config, and doing verification testing now.  Should be fixed and available with the next release.
