### ISSUE TITLE
SSTU-TANK-MUS RCS is in the wrong position with respect to the mount

### ISSUE THREAD

**Issue by blowfishpro** [shadowmage45/SSTULabs#725]
It definitely used to be on the equipment shelf below for the skeletal mounts.  It seems to be positioned at the top of the mount for all mounts now (true for both the split tank and common bulkhead variants).

![screenshot1](https://user-images.githubusercontent.com/10545461/43242090-b194f6cc-9053-11e8-822b-7d2eeec609ff.png)

**Comment by blowfishpro** [comment]
Hmm, the RCS also appears to not work, i.e. no module gets added to the part

**Comment by shadowmage45** [comment]
RCS Function -- Interesting; the module should -already- be on the part, as part of the part config.  Could be that I missed that, or that I'm not updating the modules' transform and/or effects properly.

RCS Positioning -- yep, bit of a known issue.  I have to go into each of the model definitions for the mounts/noses and add the model-relative RCS position, movement range, and movement angle.  Currently if the model def doesn't have a position spec, the code just places it at the 'origin' of the model, which is mostly incorrect, but a good enough 'default' for when values aren't specified.   Probably good to have this as an official issue though, as it is one of the more noticeable problems with the parts.

**Comment by shadowmage45** [comment]
List of models that need verified / fixed:

- [x] model = Model-TankCap-Inset
- [x] model = Model-TankCap-Flat
- [x] model = Mount-Nova
- [x] model = Mount-S-II
- [x] model = Mount-S-IVB
- [x] model = Mount-Generic
- [x] model = Mount-Skeletal-L
- [x] model = Mount-Skeletal-M
- [x] model = Mount-Skeletal-S
- [x] model = Mount-Shroud3
- [x] model = Mount-Shroud4
- [x] model = Mount-Shroud5
- [x] model = Mount-Shroud6
- [x] model = MFT-S-ADPT-N
- [x] model = MFT-S-ADPT-S
- [x] model = MFT-S-ADPT-M
- [x] model = MFT-SF-ADPT-N
- [x] model = MFT-SF-ADPT-S
- [x] model = MFT-SF-ADPT-M

**Comment by shadowmage45** [comment]
Have added RCS position specifications to the above listed engine mounts (where needed), to at least restore the positioning from previous versions.

Have also change the default parent slot for lower RCS to be the MOUNT slot; though the part still defaults to 'RCS-None' for port model selection.
