### ISSUE TITLE
SRB-U should have lower fairing

### ISSUE THREAD

**Issue by blowfishpro** [shadowmage45/SSTULabs#728]
For when things are attached to the very bottom node

**Comment by shadowmage45** [comment]
And upper fairing as well, for when using a domed nose model.

Support is already in the plugin, so likely is just a configuration level error.  I got 'busy' at work while I was in the middle of finishing up/converting many of the parts, so several have been left in an unfinished state for the last few releases.

**Comment by blowfishpro** [comment]
I think it already has an upper fairing

**Comment by shadowmage45** [comment]
Fixed in dev branch; will be available with the next update.
