### ISSUE TITLE
New Parts: SC-C 1.875m CM / SM / BPC

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#73]
Set of 1.875m CM/SM/BPC parts.

Soyuz style pod; 3-part CSM stack + BPC  

Geometry done on OM/SM/DM, BPC nearly complete  
Textures started on OM/SM/DM, BPC needs geo/unwrap first.  
Configs - WIP

**Comment by Jimbodiah** [comment]
Any sneak-peeks on the models?

**Comment by shadowmage45** [comment]
I haven't even decided on what type of pod/set of parts it will be, and am likely a few weeks out from even starting on it.  Need to finish SC-A CM/SM and SC-B CM/SM reworks first.

**Comment by Jimbodiah** [comment]
yeah, I think I am confusing it with the A series you are working on.
