### ISSUE TITLE
ModularPart - Losing settings on reload/revert, or loading of existing craft

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#730]
Report from forums (@Qwarkk):
>I'm having a problem with the SSTU parts not keeping their height / color / texture settings. After creating a craft and saving it, when i reload or launch the craft im left with something like this:
>It is most common with the tank parts, but has happened with the SRBs too - in both cases they weirdly keep their volume settings.

2nd user confirmation (@Kablob):
> Yeah, I get the same thing in the 1.4.x versions. Have to manually change the tank settings every time I reload a craft file.

**Comment by blowfishpro** [comment]
I think I ran into this at least a couple of times.  IIRC when I launched from the VAB all the SRBs settings were reset, but after reverting to launch it was fixed.

**Comment by shadowmage45** [comment]
Strange... and interesting.  Normally it works the other way (launch is fine, revert has problems).

Hopefully I'll get some time to investigate tomorrow and track down where the error is.

**Comment by blowfishpro** [comment]
At the very least though, it rules out the possibility that the data isn't getting saved - seems like it's just not getting applied in certain circumstances

**Comment by shadowmage45** [comment]
Strangely, I'm unable to reproduce this during testing.  
* Create a craft, launch it, no problems.  
* Revert to launch works
* Revert to VAB, no problem
* Reload existing craft in VAB works
* Reload of existing in-flight craft works
----

Does anyone have a .craft file and/or exact steps to reproduce this issue?

**Comment by Kablob** [comment]
[SSTU Modular Settings Test.zip](https://github.com/shadowmage45/SSTULabs/files/2321887/SSTU.Modular.Settings.Test.zip)

Here's a craft file, made with vanilla KSP 1.4.5+the latest version of SSTU.

**Comment by shadowmage45** [comment]
Has anyone come up with steps to reproduce this issue?

Even using the test-craft posted above, doing some test flights, revert-to-pad, revert-to-vab, re-launch, revert, I was unable to trigger any issues.

At this point I'm suspecting that there may be a mod conflict of some sort involved; it doesn't really make sense, as most mods shouldn't impact those subystems of SSTU, but it would explain why others are encountering the problem while I am not (e.g. they have some mod installed that I don't).

----

Would anyone be able to post up a log file from a run of KSP where this problem was encountered?  That _might_ give me a bit more information on what is going on, and would at least let me see any configuration level differences.

**Comment by pixe1reality** [comment]
I don't have a log file on me, but as I've stated on the forums (putting here so it's more easy to find) it seems to only happen when its on a tank that had its diameter adjusted via the slider bar instead of the arrows (e.g. selecting 0.938m/0.9375m from 0.625m), but never from when it was adjusted in increments via the arrow buttons. Strangely enough, this also happens in a different form with the MUS, where if the tank diameter is adjusted with the slider it seems to reset to being a split tank instead of maintaining the desired upper stage variant, with no changes at all to the custom diameter or tank length.

**Comment by shadowmage45** [comment]
Interesting -- will see if I can duplicate it with the above details.  Still was unable to reproduce yesterday during testing, though I am admittedly trying fairly simple craft and part setups.

**Comment by Joker58th** [comment]
This issue has happened several time in the past for me.  To fix it, I usually have to detach everything from the fuel tank, remove the tank, reattach it to the desire node, then adjust the size as desired.  I'm trying to pay close attention now that I'm in a career.  In the VAB image below, this occurred right after I added a sub-assembly that included everything from the procedure fairing base and below.  The launchpad issue occurred after I had reverted from a KRASH simulation to the VAB then to the launch pad to go for real.  Exiting the game does not fix it, I have to do the above procedure in the VAB to fix the tanks.  Sorry I don't have any logs at this point either but maybe this will help.  Let me know if you want me to try something specific.

KSP 1.4.5 (-force-glcore)
SSTU 0.8.43.153 (I did update to the latest version as of last night but the screenshots are from this version)

https://imgur.com/a/z7dkJSy

**Comment by Joker58th** [comment]
Ok, I can reproduce it every time now.

Situation:
Clean KSP 1.4.5 (-force-glcore)

Mods Installed via SSTU zip:
Textures Unlimited
Community Resource Pack
KSP Wheel
SSTU

Steps:
1. In VAB add probe core and SSTU - TANK - MFT-A Standard and save
2. Change variant to Hydrolox
3. Change core to MFT-B-1-0 and save
4. Exit VAB, Enter VAB

Now so far it looks ok but if you go to the properties of the tank you can see that the settings are reset.  Going to launch from here will show the tank has been reset.  Also on revert to VAB.  Here are the pics from the steps above.

https://imgur.com/a/gqVOezO

**Comment by shadowmage45** [comment]
I'll give you an internet cookie for posting this.... and a free beer (or drink of choice) if it allows me to repro the problem.

Will try and test tonight if I can get a free moment....

**Comment by Joker58th** [comment]
lol..I hope it helps.  It still doesn't explain why the problem only shows up "sometimes" on my main save.  I like to use the Cryo variant a lot so that is what led me to this point.  Leaving it with the default Kerolox doesn't seem to cause the issue ever.  I will also try it tonight on a different machine/hardware as another test.

**Comment by Joker58th** [comment]
I also just added a screenshot of my gamedata folder to the album above for your verification.

**Comment by shadowmage45** [comment]
Alright -- can finally reproduce this issue, using the steps listed above.  Many thanks for finding the necessary steps.  There certainly is a loss of persistent information at one point or another during (re)loading -- now I just need to figure out the 'why' :)

Log file only shows one 'error' of note.  May be related... though it is supposed to be a 'fail gracefully' bit of code wrapping that loading error.
````
[LOG 16:15:05.103] SSTU-ERROR: Model definition was null for name: Adapter-2-2-Long. Skipping definition during loading of part
[LOG 16:15:05.103] SSTU-ERROR: Model definition was null for name: Adapter-2-2-Long. Skipping definition during loading of part
[LOG 16:15:05.103] SSTU-ERROR: Model definition was null for name: Adapter-2-2-Long. Skipping definition during loading of part
````
