### ISSUE TITLE
SRB-U - flag mesh is visible but contains no flag and is not toggleable

### ISSUE THREAD

**Issue by blowfishpro** [shadowmage45/SSTULabs#734]
![screenshot3](https://user-images.githubusercontent.com/10545461/44634016-52ff4280-a948-11e8-867e-4e2e0d055c53.png)

**Comment by shadowmage45** [comment]
Nice :)
(this is likely just a missing SSTUFlagDecal PartModule...)
Should be simple enough to fix up.
