### ISSUE TITLE
Dome A/B texture weirdness

### ISSUE THREAD

**Issue by blowfishpro** [shadowmage45/SSTULabs#736]
Not sure where the lip color is coming from, and there are two odd bands at opposite sides of the lip.  Seems to be the case on every part that uses it
![screenshot4](https://user-images.githubusercontent.com/10545461/44634080-58a95800-a949-11e8-9b50-fff415a81746.png)

**Comment by shadowmage45** [comment]
Ring texture color comes from the dome adapter itself.  The model consists of the dome, and the two 'lips' to make it line up with standard stack diameters.  Could potentially make the lip re-colorable if it isn't currently -- will have to take a look at the mask setup.

The mis-colored sections are likely either a mask-texture error, or error with the diffuse texture (though could also be spec/met...).

Either way, shouldn't be too much of a problem to get this fixed up.

**Comment by shadowmage45** [comment]
There was a small error in the SPEC and MET maps for the texture for that model.  Have fixed up those maps, and the miscolored section is no longer present.

Sadly trying to change the lip to be recolorable is not nearly as simple -- the same mask looks to be used by other models (that also have the lip on them), and all three channels are already in use.  Will investigate more in depth to see precisely where they are used and what the change would impact.

**Comment by blowfishpro** [comment]
I don't think the lip needs to be recolorable, I was just confused about why it's that specific color.

**Comment by shadowmage45** [comment]
Ahh, yeah, the lip was supposed to be 'inside-of-fairing brown' color, to line up with the coloring I had on the inside of the fairings long ago.

Honestly I could probably change it to be a painted gray, steel/silver metallic, or ??  Its currently not masked/recolorable, so I can use 'standard' texturing techniques for it.  Perhaps turn it into some bolt-head ring, or other sorts of detail-level greeble (attach points/latches for the fairing?).

Entirely open to suggestions if you have any; I'm also open to leaving it as-is :)

**Comment by blowfishpro** [comment]
I guess some sort of bolt ring might make sense.  It's not a big deal though.
