### ISSUE TITLE
SRB Thrust Curves not working

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#745]
Reported on forums; no other information given.

**Comment by shadowmage45** [comment]
Can confirm.
Strangely, from the code perspective it should be working.  The curves are valid in the editor.  They are saved and restored correctly across revert/reload/launch.  Code obviously is applying them to an engine module.

Potential for part-engine-module config needs to be enabled for thrust-curves? 'useThrustCuves=true' or somesuch?

**Comment by blowfishpro** [comment]
I believe the modules do need a flag set.  I think it’s some artifact of how FloatCurve is implemented and it being null by default (I can definitely see better ways to do this but usually best, for one’s own sanity, not to ask why Squad did things the way they are)

**Comment by shadowmage45** [comment]
Indeed -- it did turn out to be the module itself needing the flag set to use thrust curves.  

Have toggled it on in the part configs, and verified that it works with a custom thrust curve.  Need to double check that the 'default' configuration still works though...
