### ISSUE TITLE
Radial Booster Decoupler - SolidFuel amount isn't scaling with diameter

### ISSUE THREAD

**Issue by blowfishpro** [shadowmage45/SSTULabs#747]
Seems to be staying at a constant 140.

**Comment by blowfishpro** [comment]
Maybe something to do with this being unimplemented/commented out?

https://github.com/shadowmage45/SSTULabs/blob/31df048229ff0cfa4fb0db7eb73dd8e3288f35f3/Plugin/SSTUTools/SSTUTools/Module/SSTUCustomRadialDecoupler.cs#L277

**Comment by shadowmage45** [comment]
Hahaha... yep, that _might just_ do it.  Good catch, should be simple enough to fix up.  I reworked the container interaction a bit during the 1.4 updates, and apparently missed a few places where it needed to be reworked.

**Comment by shadowmage45** [comment]
Fixed in dev; still uses simple internal resource handling / does not use volumecontainer or RF/MFT.
