### ISSUE TITLE
Lander tank - secondary nodes are not positioned correctly/not hidden when they should be

### ISSUE THREAD

**Issue by blowfishpro** [shadowmage45/SSTULabs#749]
As discussed on the forums

**Comment by shadowmage45** [comment]
Fixed in dev;  
* Tank body model definitions for inset variant needed the node definitions added.
* Tank config needed the top2/bottom2 nodes linked to the Core model for manipulation

**Comment by shadowmage45** [comment]
Fixed in dev;
    * Tank body model definitions for inset variant needed the node definitions added.
    * Tank config needed the top2/bottom2 nodes linked to the Core model for manipulation
