### ISSUE TITLE
New Part - SC-B-SM (rework)

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#75]
Rework SC-B-SM (Service Module) 
- Fix RCS positions and orientations to allow for better / more balanced control.
- Add dedicated transmitter module and module
- Rework secondary engines to be a set of overpowered RCS thrusters.
- Remove umbilical to allow for more generic use of the part?
- Rebalance the thrust/mass/etc for stock part balancing.
- Investigate ability to add decoupler to top/bottom
- Clean up default settings on the fairings

**Comment by Jimbodiah** [comment]
Can you keep the umbilical as a selectable option, to keep it real-life looking? I think the Orion is your flagship component.

PS: what is the use for the planned orbital version? Only the heatshield and chutes are removed.

**Comment by shadowmage45** [comment]
I strongly dislike the umbillicals.  It makes all of the parts harder to re-use in a visually clean manner.  And I have stated -many- times that I'm not in this to make real-life replicas of stuff.  Also, I really don't feel like writing yet-another-mesh-switch module just for SM umbilicals.  Nor do I want to make a separate texture set for the CM without the umbilical ports.  Would rather just have a single model + texture for each.

Orbital version - no clue, but people had asked for CMs without heatshields, so as I'm already redoing them and the added time to remove the heatshield is close to nil, I'll be including them.

**Comment by Jimbodiah** [comment]
ok

**Comment by shadowmage45** [comment]
I'll consider doing the umbilicals, as I'm not yet past the 'can't do them' stage -- however, it would require delaying finishing up the SC-A-CM texture until I had the SM done (as I would need to know where to position the umbilical ports on the texture).  And at least initially they would be a fixed mesh/no switch support - I'll split the mesh off though so that it could be easily enabled with a config addition.

**Comment by Jimbodiah** [comment]
Skip the umbilical ;) I want a clean conscience, haha.

**Comment by shadowmage45** [comment]
Rolled into #72
