### ISSUE TITLE
RL10-4 Engine has no shutdown or activate option

### ISSUE THREAD

**Issue by Joker58th** [shadowmage45/SSTULabs#750]
Clean KSP 1.4.5 install
SSTU-0.8.43.155 installed with included required mods.
GameData folder shown in imgur album.

In comparing an RL10A-3, there is no option to shutdown or activate the RL10A-4 engine.  Also while the action group options do show the option to Shutdown and Activate, these actions deploy/retract the engine bell extension instead.

[KSP.log](https://github.com/shadowmage45/SSTULabs/files/2502482/KSP.log)

https://imgur.com/a/3EjYlPl

**Comment by shadowmage45** [comment]
I believe that is intended -- the 'animated engine' module takes over the stock controls and performs the 'activate' and 'shutdown' depending on if the engine bell is extended or retracted.

Basically it is to force that you cannot activate the engine until it is deployed.

The real question is -- does the engine **work** once it has been deployed?  If so, then it is all working as intended.  If not... then there is likely a bug somewhere.

(the RL10-B2 engine has the same deployment setup)

**Comment by Joker58th** [comment]
You are correct, it does not activate until it is deployed and I understand that is by design.  My problem is if I want to deactivate the engine, the bell extension does retract but the engine continues to run.

Edit: I realize I did not state this clearly in the first post so thanks for your question.

**Comment by shadowmage45** [comment]
> My problem is if I want to deactivate the engine, the bell extension does retract but the engine continues to run.

What method are you using to de-activate (do you press the PAW button for 'retract', or using action groups)?

Sounds like there may be a bug with at least part of the implementation -- it should not let you retract without first deactivating (rather it should automatically de-activate when retracted; and automatically retract if deactivated).

**Comment by Joker58th** [comment]
I tried both methods and they behave the same.  I added another image that shows the engine running after clicking on retract in the PAW and I also tried the activate/deactivate in the action groups.

**Comment by shadowmage45** [comment]
Thanks for the testing and confirmation.  Would definitely label this one as a bug.

Will look into this for the next update/release.  Just as soon as I finish up the 1.5 update for TU :)

**Comment by shadowmage45** [comment]
Fixed in dev.  Initiating the retract action now shuts down the engine.

May investigate allowing just a 'shutdown' command without engine retract in the future.
