### ISSUE TITLE
KSP 1.5 Updates

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#751]
* All parts will use PBR shading by default.  Legacy shader use deprecated.
  * All textures need swapped from spec.RGB met.A to Met.R, AO.G Spec.A
  * texture sets need updated for changes to texture set names and shader names
  * recolorable texture sets need keyword props and normalization values added
* Fix stock part-resource manipulation code -- something about simulation resources that needs to be kept in-sync with actual part resources.

### WIP Parts with issues:
* SC-E - Landing Legs
* DP - emissive map / mesh assignment is wrong for glow

**Comment by blowfishpro** [comment]
Regarding resource stuff, here's the update I had to make if it helps: https://github.com/blowfishpro/B9PartSwitch/pull/110/files

Actually now that I think about it, I'm wondering if the code that modifies resource amounts needs to be updated too.

**Comment by shadowmage45** [comment]
I just updated SSTU's resource-manipulation code with similar to what you are using in B9, with the addition of also updating simulation resources whenever I alter (as opposed to add) a resource.

Thanks for pointing that out to me, would have taken a few hours of head-bashing to figure out that stock included an entire new resource-list...
