### ISSUE TITLE
Bugs & missed textures (ver. SSTU-0.9.44.156)

### ISSUE THREAD

**Issue by korych** [shadowmage45/SSTULabs#753]
![1111](https://user-images.githubusercontent.com/45110013/48679039-49c6f000-eb9c-11e8-90af-336714bcb6c7.jpg)
![2222](https://user-images.githubusercontent.com/45110013/48679040-4a5f8680-eb9c-11e8-9ce7-dd585d2e66bb.jpg)

**Comment by pixe1reality** [comment]
Another missing texture type issue from the release is the F-1 and J-2 PBR textures. They seem to still be requesting textures from the SSTU-PBR/Assets folder, rather than from SSTU/Assets.

Until the next release, I recommend putting duplicated DIFF/GLOW/NRM textures in a SSTU-PBR/Assets folder.

**Comment by shadowmage45** [comment]
Hmmm... those textures were supposed to go away entirely (the F1 and J2 PBR textures).  Must have inadvertently left the patch in somewhere?

**Comment by shadowmage45** [comment]
Looks like the LC-POD RCS ports have already been patched somewhere along the lines.
F1/J2 textures already fixed in previous bugfix pass.
Have fixed the offset RCS ports on the DOS-FEM module.

**Comment by shadowmage45** [comment]
Need to revisit; LC5-POD at least needs its RCS blocks patched.

**Comment by shadowmage45** [comment]
LC3 and LC5 pod RCS blocks fixed.
