### ISSUE TITLE
Both LR81 engines show as operating in game (out of VAB)

### ISSUE THREAD

**Issue by taterkerman** [shadowmage45/SSTULabs#754]
Both the LR81 engines exhibit this behavior once out of the VAB. No propellants required.

This tank has rocket parts (works on an i-beam, whatever):
![lr81s](https://user-images.githubusercontent.com/17967275/48917714-810bfa00-ee45-11e8-84a7-5e73a1f2fb8a.png)

MacOS High Sierra, everything else in SSTU so far is peachy. I think this happened a long time ago as well, unsure if I resolved it, or forgot to post the issue.

**Comment by taterkerman** [comment]
So does the RD-0110. Make craft, go to launchpad, and the engine _looks_ as if it's runing, even when not activated.

**Comment by taterkerman** [comment]
And the RD-107

**Comment by shadowmage45** [comment]
RealPlume, or stock?

**Comment by taterkerman** [comment]
Stock. Realplume still says 1.4, haven't stuck it on yet (seems to be semi-abandoned as a mod).

**Comment by blowfishpro** [comment]
RealPlume should work ok in 1.5.  It's just a bunch of effects and configs.  The plugin it relies on (SmokeScreen) is updated.

**Comment by taterkerman** [comment]
Cool, will do (adding RP back). 

That said, considering how annoying the engines always (visually) appearing to run is, it might have to be listed as a dependency on the OP of the mod at the forum as it is bound to generate loads of questions (unless there is a trivial fix for stock, since most all the SSTU engines do not exhibit this behavior).

**Comment by shadowmage45** [comment]
I'm sure the fix (whatever it is) for stock would be simple; 99% likely it is just a misspelled transform name in the config files.

I was just asking if it was RP or stock, so that I would know -which- config files to look at :)  (stock effects are in the part.cfg; real-plume have their own patch.cfg file in a different place).

**Comment by shadowmage45** [comment]
Not seeing this issue any longer when using stock effects.

Have not investigated RealPlume, but marking as resolved for now.
