### ISSUE TITLE
Smaller length steps for tanks

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#76]
Tank lengths increase by quite a big step, is it possible to add only half of what is added per step at the moment?

**Comment by shadowmage45** [comment]
Will be implemented with the upcoming re-work of the custom fuel tanks.  I have added half-step sizes in-between all existing tank sizes  (including a half-height variant of the currently smallest tank).

Models are already done/exported, just need to finish up the rest of the plugin code to allow them to be used.

You should see this feature with the next full/scheduled update.

**Comment by SixDasher** [comment]
You da man!!!

**Comment by Jimbodiah** [comment]
Thank you.

**Comment by shadowmage45** [comment]
Rolling into #74
