### ISSUE TITLE
F1 and J-2 engines lack textures for me.

### ISSUE THREAD

**Issue by taterkerman** [shadowmage45/SSTULabs#760]
I've added in a bunch of mods, but it's odd that just those 2 show this. Can someone take a glance at those and see? If it's just me, it's likely a conflict.

**Comment by shadowmage45** [comment]
Most likely I've missed a patch when I merged the PBR into the main distro.  Those were the only two engines that had specific PBR textures (which were removed), but the patches are likely still pointing to those now removed texture files.

**Comment by taterkerman** [comment]
Cool. Just making sure I didn't manage to screw up my install.
