### ISSUE TITLE
MUS almost crashes editor

### ISSUE THREAD

**Issue by taterkerman** [shadowmage45/SSTULabs#762]
[KSP.log.zip](https://github.com/shadowmage45/SSTULabs/files/2670821/KSP.log.zip)
Stick a MUS to something. Add Solar and RCS. Try to attach an engine. The node on bottom disappears, and the engine goes transparent. Can't select it. Then select the MUS, it disconnects from the capsule, then goes transparent. 

It didn't crash, but here's the log, anyway.

**Comment by taterkerman** [comment]
I should add I was trying to make an alternate SM for Soyuz. I need to test with an alternate capsule.

**Comment by shadowmage45** [comment]
Interesting; issue appears to be with the MUS, but only -after- the engine is added...

````
[LOG 00:11:18.769] SSTU-SC-ENG-Merlin-1BV added to ship - part count: 4
[EXC 00:11:18.772] NullReferenceException
	UnityEngine.Transform.get_localRotation ()
	SSTUTools.SolarPivotData.getPersistentData ()
	SSTUTools.PanelData.getPersistentData ()
	SSTUTools.SolarModule.updateSolarPersistence ()
	SSTUTools.SSTUModularPart.OnSave (.ConfigNode node)
	PartModule.Save (.ConfigNode node)
	ShipConstruct.SaveShip ()
	ShipConstruction.CreateBackup (.ShipConstruct ship)
	EditorLogic.SetBackup ()
	EditorLogic.<SetupFSM>m__27 ()
	KerbalFSM.RunEvent (.KFSMEvent evt)
	KerbalFSM.updateFSM (KFSMUpdateMode mode)
	KerbalFSM.UpdateFSM ()
	EditorLogic.Update ()
[EXC 00:11:22.471] NullRefer
````

**Comment by shadowmage45** [comment]
What was the configuration of the MUS when you were attempting this?  Did it have solar panels selected, or using the default 'no panels' option?

**Comment by taterkerman** [comment]
I know I tried solar panels at some point, so it certainly happens with panels. I will systematically try this tonight and let you know.

And yes, it l;ooks fine, then when I add the engine, poof, the node disappears.

**Comment by taterkerman** [comment]
Anything but the default Solar Layout seems to trigger it.

**Comment by shadowmage45** [comment]
Can duplicate with a bit of back-and-forth; trying to figure out the exact cause/steps now -- seems to be specifically related to the 'solar panel layout' option, and not necessarily the 'model'  (and doesn't impact RCS AFAIK).

Hopefully should have this one cleaned up shortly, soon as I can figure out precisely where it is exploding.

**Comment by shadowmage45** [comment]
Fixed in dev; will be available with the next release.
