### ISSUE TITLE
Manufacturer tab

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#77]
Add a tab under manufacturers to filter out all SSTU parts.

**Comment by shadowmage45** [comment]
Apparently this will require investigation of the 'agents' folder/config node setup.  Should likely be fairly easy to accommodate, but will require some time (while not at work) to sit down and work through the stuff.

Scheduling for this weeks update, but may or may not actually make it in depending upon other demands for my time / how the rest of the week goes.

**Comment by Jimbodiah** [comment]
No hurry on this, just cool for future versions.
