### ISSUE TITLE
SSTU texture bug in map view

### ISSUE THREAD

**Issue by YBAX83** [shadowmage45/SSTULabs#771]
I love this mod! in my opinion is top 3 in complexity and usability and I use it in all previous versions of KSP. normally I was playing on 1.4.5 without any problems and today I decided to use the latest version of the game and start a new career. so I installed all the mods and when I started the game I had a problem: <a href="https://s1081.photobucket.com/user/flo_22_ro/media/54524084_2395992507295840_8761372691270729728_n_zpsyzxbzoun.jpg.html" target="_blank"><img src="https://i1081.photobucket.com/albums/j359/flo_22_ro/54524084_2395992507295840_8761372691270729728_n_zpsyzxbzoun.jpg" border="0" alt="ksp bug photo 54524084_2395992507295840_8761372691270729728_n_zpsyzxbzoun.jpg"/></a>

I tried everything on here... have the latest version of texture unlimited put in the shortcut of ksp the command with "-force-d3d11" even delete all folder of texture unlimited and the problem is still there... I say is this mod because I tested the game with every mod and nothing... it works perfect but when I put this mod the big white square appears in game... and when I delete the SSTU folder game is back to normal. It is a pity because KSP is not complete without this mod... So any ideas on what is causing this?

**Comment by shadowmage45** [comment]
Unfortunately that photo is not loading, so I'm unable to see the error.

Perhaps more useful would be to upload a KSP.log file so that I might see what/if any errors are occuring during startup.

The mod is known to work properly with KSP 1.6.1 as long as it is installed correctly and all dependencies are up to date.

**Comment by shadowmage45** [comment]
Edit:  I was able to see your image as posted in the forums.  That is indeed some odd graphical corruption, of a kind that I have not seen before.

Do you know if your graphics hardware and drivers are fully DX11 compatible?

Again, this is where uploading a KSP.log file would be useful -- it will list the graphics compatibility in the top of the log file.

**Comment by YBAX83** [comment]
[KSP.log](https://github.com/shadowmage45/SSTULabs/files/2982721/KSP.log)
 as you will se in the log i do have a fully DX11 compatible system... I don't know how the log works and if you can see the problem there but I had to delete SSTU mod because of this bug... oh and one more thing the parts in the parts category list on the left in the VAB and SPH are a bit gray too... I hope this helps cause I really want to use your mod man cause it is awesome! 
P.S I never seen a bug like this until now too and I played all previous versions of KSP with a lot of mods including SSTU... at first I thought it was EVE or sctaerer related and I took a stock install of the game and started to add mods one by one and test to see when the bug appears and it came down to SSTU... Ieven deleted texture unlimited folder and tried  to run the game like that and the bug was still there.

**Comment by YBAX83** [comment]
hmm... the version that I was using with the bug is 1.6.0.2395 (WindowsPlayer x64) with the DLC making history.... and now I just tested the mod with the latest version of the game 1.6.1 without DLC... and there is no bug but only had SSTU and all dependencies + mechjeb and toolbar. could it be there is a DLC conflict with SSTU in 1.6.0.2395?

**Comment by YBAX83** [comment]
Edit nr.3 please ignore this bug report... i did a fresh reinstall with latest version of the game (1.6.1) and everything works well! no major bugs... so please excuse me for the bug report and time wasting! continue the good work that you are doing! one suggestion... if you can in the future I searched everywhere on ksp mods and I can't find a cylinder  cargo bay with a ramp for rover transportation and deployment purposes.... if you are planing in the future to add more parts please consider this as well. thank you for the replay and again sorry for the bug report... the problem was on my end. have a good day shadowmage45!

**Comment by shadowmage45** [comment]
No worries, and glad you got it sorted out.

(and yes, additional cargo-bays are on the todo list :) )
