### ISSUE TITLE
Orion SM Fuel 

### ISSUE THREAD

**Issue by Alan-JH** [shadowmage45/SSTULabs#773]
Fuel tanks in Orion SM always reset to Aerozine 50 and NTO upon launch no matter the type of fuel was added in the VAB

**Comment by shadowmage45** [comment]
Edit:  Actual, not confirmed.  The fuel selection appears to work fine in my testing; select MonoPropellant in the VAB, and that is what is in the craft upon launch.  

Any specific configuration needed to trigger this issue?

**Comment by Alan-JH** [comment]
Well when I tried to use Orion SM it said the engine had flameout because of lack of pressure, then I checked and realized the AJ10-190 engine ran on MMH and MON3, so I added those tanks, along with the preexisting A50 and NTO tanks and it just went back to A50 and NTO.  When I switched RCS to MP, it removed all non MP tanks instead.
It seems only fuel tanks which the rcs is set to use stay in the vehicle.

**Comment by blowfishpro** [comment]
Sounds like you're using RealFuels (and maybe RO?) ... in either case the configuration for that is maintained elsewhere.

**Comment by Alan-JH** [comment]
Okay so it isn't an issue with SSTU?

**Comment by blowfishpro** [comment]
I don't think so.  Highly pressurized tanks are a RealFuels thing.
