### ISSUE TITLE
Drone core for un-manned rockets

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#78]
Drone core with SAS, Reaction wheel and maneuvering functions (target, retro/prograde etc) to send up unmanned rockets.

**Comment by shadowmage45** [comment]
Does stock not already offer probe-core parts with those functions?

(Really, I'm asking.. as I have no idea... I don't think I've ever touched the stock probe core parts; have always used MJ as my probe-core)

I suppose the big missing part would the the reaction wheel?  I don't remember seeing any ASAS capabilities on the stock parts (granted, I have not looked at them closely, nor at all in a very long time)

**Comment by Jimbodiah** [comment]
The stock cores have no real reaction wheel to speak of (low torques), but was wondering if something that fits with SSTU parts would be an option. The stock parts stick out like a sore thumb and would require 2 parts (core and reaction wheel).

**Comment by shadowmage45** [comment]
Ahh, that makes a bit more sense.

However, I would rather implement these as the 'Service Modules' that I have planned.  These will be a part/series of parts that include, well, service modules for various stack sizes -- including RCS, solar panels, probe core, reaction wheels.. the works (undecided if they will include engines or not... would like to keep them scalable, but inclusion of engines would prevent this).  These would be sized/setup such that they are capable of being disposable orbital tugs, automated station resupply barges, etc.

Alternatively, these might be a good fit for the other planned 'Satellite Core' series of parts -- basically small probe-core bodies with transmitters/solar panel/rcs/fuel.  In essence, smaller versions of the service modules that are not intended to carry payloads other than scientific instruments.

However, I could not see myself using a 'large-rocket' oriented stand-alone probe-core; every use case I can think of would be better suited to a proper service module or satellite core.

**Comment by Jimbodiah** [comment]
Sounds like the solution to my request. If you can scale them into a slice to match the tanks etc, then problem solved! Adding RCS/Solar as well is even one step further and a better solution.

**Comment by blowfishpro** [comment]
Just as a note to @SixDasher, the upper stage tanks already have built-in probe cores (and RCS), so if you include one of those you will have control.

**Comment by Jimbodiah** [comment]
OMG!!!  I didn't even see those three new parts... I just installed 0.2.22 this afternoon and didn't think anything new was added. Thanks for pointing this out!!! They do indeed have RCS/SAS, but no reaction wheels though. Nice work, you are way ahead of me I see ;)

**Comment by Jimbodiah** [comment]
Is there a road-map to see what you are working on? Maybe save some issue-spamming by me ;)

**Comment by shadowmage45** [comment]
Basic roadmap - dates are kind of... iffy, but the ordering of stuff on there is fairly appropriate.
https://github.com/shadowmage45/SSTULabs/milestones

The issues tab also will let you know what is currently 'in progress' by checking for the 'Next Update' tags on the issues:

https://github.com/shadowmage45/SSTULabs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22Next+Update%22

**Comment by Jimbodiah** [comment]
Thanks Mage!
