### ISSUE TITLE
Action group items have blank titles.

### ISSUE THREAD

**Issue by Teslamax** [shadowmage45/SSTULabs#782]
- Many parts have action group items with blank titles. (The one I noticed first was `DOS - TKS`.)
- The issue exists in both stock action group editing and in [AGX](https://forum.kerbalspaceprogram.com/index.php?/topic/167269-17-action-groups-reextended-250-action-groups-in-flight-editing/).

[Example image](https://i.imgur.com/DKxuY9m.png?1)

**Comment by shadowmage45** [comment]
Fixed in dev.  These were action-group links to the animation and solar panel actions for SSTUModularPart.
