### ISSUE TITLE
ModIntegrations update: collected questions

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#788]
Just wanted to make a topic for questions regarding to upgrading ModIntegration files.

**Comment by Jimbodiah** [comment]
1.)   SSTUVolumeContainer for LS resources. Are the volumes from the old patches still relevant, as I can not find references to them anymore on the original parts.


>@PART[SSTU-LC2-POD]:FOR[SSTU]:NEEDS[USILifeSupport] // 2-person pod
{
	MODULE
	{
		name = ModuleLifeSupport
	}
	@MODULE[SSTUVolumeContainer]
	{
		@volume = 330    ////////////////////////////////// THIS ONE
		@CONTAINER,0
		{
			@defaultResources = MonoPropellant,25;ElectricCharge,300;Supplies,65,1;Mulch,65,0
			resource = Supplies
			resource = Mulch
		}
	}
	@MODULE[SSTUModelSwitch]
	{
		@baseVolume = 330   /////////////////////////////////  THIS ONE
	}
}<

**Comment by shadowmage45** [comment]
1.)  That 'volume' spec should probably be removed from the configs, as that was the volume for the whole part;  the 'volume' spec has since been moved into the CONTAINER definitions, so that you can simply patch in the specific container needed, with the volume it needs.
