### ISSUE TITLE
After upgrading to 1.8

### ISSUE THREAD

**Issue by Quadonix** [shadowmage45/SSTULabs#816]
After KSP upgrade to 1.8, loading freezes. Please upgrade. I can't play

**Comment by Jimbodiah** [comment]
Play 1.7.x, downgrade your intallation.

Wait for mods to update before removing your old ksp version. No sense expecting all mods to update for you just a couple of days after  yet another new KSP version hits. You should know this by now.

**Comment by shadowmage45** [comment]
Closed due to entitled whining.

The mod will be updated if and when it is updated.  Bugging me here only serves to piss me off, and will in fact only result in delays to releases.  So.. thanks for that.  Now I know what I'm _not_ working on this week.
