### ISSUE TITLE
All crew module, as well as their service module can't change their fuel type under RO

### ISSUE THREAD

**Issue by Foxrect** [shadowmage45/SSTULabs#818]
As described in the title, All crew module can't change their fuel type under RO. Well, more specifically. I can't save them after I change them. Not even if I want lunch them. The fuel type will be changed into stock one automatically. And this made me feel sad really because there are few mod have high quality Orion space craft. Not to mention one can be recoloured.

**Comment by shadowmage45** [comment]
Realism Overhaul issues should be reported in the Realism Overhaul issue tracker.

I do not use Realism Overhaul, do not develop for Realism Overhaul, and do not support Realism Overhaul.  Nor can I fix problems with their code or patches.
