### ISSUE TITLE
Solar Panels don't show their details (EC generation, etc.)

### ISSUE THREAD

**Issue by ns88ns** [shadowmage45/SSTULabs#829]
Hi.

In KSP 1.9.1 SSTU Solar Panels don't show their details (EC production, etc.). All mods and Squad use module **ModuleDeployableSolarPanel** to define solar panels however you use your own module **SSTUSolarPanelDeployable** for that. Perhapr it is possible to inherit from **ModuleDeployableSolarPanel** and adjust it? Will it resolve the issue?

Or is there any other way to know how many EC SSTU solar panels generate?

Thank you in advance for reply.

**Comment by ns88ns** [comment]
Ah, it is clear now - it isn't implemented. There is still TODO stub. Closed.

**Comment by Jimbodiah** [comment]
Maybe add the Ec/s in the description text for now? Could be done here by anyone.
