### ISSUE TITLE
1.875m fairings skipped

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#83]
Upon selection fairing size for next/previous stage, size goes from 1.25 directly to 2.5m. Needs manual freesclaing to fit.

[edit] same goes for engine mount sizes.

**Comment by shadowmage45** [comment]
Intentional; 

People complained when I had the step size at 0.625m;  So now it is 1.25 and you need to use the fine-adjust slider (that is what it is there for, after all).

**Comment by Jimbodiah** [comment]
Haha... yeah, people are nuts ;)
