### ISSUE TITLE
Pre-Release TODO: Part Balance Pass (Career Mode) - Prices, Unlock Prices, Tech-nodes

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#88]
All data pertaining to non physical part balance will be located at:

https://docs.google.com/spreadsheets/d/1spJ-M3PJhFfzmbS6p8NZOjsCL3Sq290JSul0keFg7Iw/edit?usp=sharing

Please post comments/etc on what you think might be good values, or clone the sheet and fill things in and link back to it.

**Comment by shadowmage45** [comment]
Merging #151 in here

**Comment by Jimbodiah** [comment]
May I enter the data there?

What is the Unlock Price if I may ask?

**Comment by shadowmage45** [comment]
Would rather leave it as hand-manicured for now (as if other people edit data that I dont like, I won't know what it -was- prior to their edit).  So for now, feel free to open up an issue / etc with the suggested prices for particular parts and I will merge them into the sheet (and configs) when I have time.  Same for tech-nodes

Unlock price -- there is an option in KSP career mode to force a player to 'unlock' each individual part after they have researched it, but before they can use it.  It defaults to 'off' for easy/normal career games I believe.  This is a one-time cost that the player must pay before the part is available in the editor, and is separate from the per-part cost that the part adds to the vessel total cost.

**Comment by Jimbodiah** [comment]
NP, will do.

Hadn't seen that option before on careers. Makes sense, some sort of prototyping costs :)

**Comment by shadowmage45** [comment]
Largest outstanding career-mode issues are related to the positioning of the SC-B (Apollo) parts and other Apollo-era hardware.

Stats-wise most of it should be in the last 1 or 2 tiers of the tech-tree; history wise it should be about half-way through (where it is currently positioned).  Not sure of a way to rectify those two opposing setups.
