### ISSUE TITLE
New Parts - Ship Core: Interstage Decoupler

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#92]
Interstage decoupler will consist of the following:
- Bottom Node Decoupler
- Procedural and adjustable fairing (height, top diameter, bottom diameter, straight-height/taper start)
- Top Node Decoupler
- Ullage/Retro rockets (depending on how it is installed)(can use two if you want both retro and ullage rockets)

Plugin done
Model geometry first pass/prototype is done (no uv/etc)
Model texture not even started

**Comment by Jimbodiah** [comment]
Oh joy!!! :100:

**Comment by shadowmage45** [comment]
Part is working in dev and will be available with the next update.  Models/textures will likely still be WIP.
