### ISSUE TITLE
Multiple crashes upon using modular fuel tanks

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#93]
I keep getting crashes when I play with the modular fuel tanks, especially on a project that uses two and in combination with the pedal fairing. 3/4 times it just crashes, else it get super slow and memory usage shoots up from 1.7 to around 3GB.

See link for log file.
http://dasher.nl/kerbal/output_log_sstu.txt

The logfile is huge (34MB), and I cleaned it just prior to this run of abotu 2-3 minutes.

**Comment by shadowmage45** [comment]
Could you post the KSP log as well?  The log you have posted does not have a stack trace in it that I can work with, it merely lists something regarding a button, but does not tell me what/where it was triggered, or what the button even was.

**Comment by Jimbodiah** [comment]
http://dasher.nl/kerbal/KSP.log

**Comment by shadowmage45** [comment]
If that posted log is correct (looks like it was all in the editor?), then this issue should be fixed along with #94.  Please try out .23-pre-3 and let me know how it goes.

**Comment by Jimbodiah** [comment]
Will do

**Comment by Jimbodiah** [comment]
No crashes so far, been playing avidly with two modular tanks and the pedal fairing in a project for over 10 minutes now with over 7 launches, and still running.

**Comment by Jimbodiah** [comment]
Crashes seems solved, haven't had an abnormal crash so far (only normal ones, whah).

**Comment by shadowmage45** [comment]
Okay, please let me know if it pops up any more, with fresh logs if you can.  Closing this ticket, but if you comment I will still see it and can re-open if needed.
