### ISSUE TITLE
Nose and mount texture bug on modular tank

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#94]
I can only select one next texture for nose and mount, then it gets stuck to that color. Body cycles properly.

Nosecone shape gets stuck as well, two textures can be seen:
http://dasher.nl/kerbal/sstu_nosecone.jpg

**Comment by Jimbodiah** [comment]
If I select a next body texture it will sometimes allow me to advance one version of the nose/mount texture.

**Comment by shadowmage45** [comment]
Can confirm the issue regarding nose-cone switching; investigating now.  From looking at the log posted on #93 these seem to be related (only thing in that log was this same error).

**Comment by shadowmage45** [comment]
One other point of note, is that not all mounts/adapters have textures for all texture sets (yet); notably the engine mounts only have a single texture set, and the nosecones and adapters only have 4 sets (2 black/white, 1 white, 1 orange).  Will be updating the texture-swap function in the future to skip these emtpy sets, and/or adding textures for those sets.

**Comment by shadowmage45** [comment]
Uploading a new release now that fixes this issue.  Please report in on #93 as well, as it should likely be fixed with this update too.

https://github.com/shadowmage45/SSTULabs/releases/tag/0.3.23-pre-3

I did also discover an unrelated bug regarding the RCS on the MUS parts; will look into fixing that up in the morning.

**Comment by Jimbodiah** [comment]
Textures (color) seem to be cycling better now, haven't seen the double nose-cone so far. Will keep trying ;)

**Comment by Jimbodiah** [comment]
Mage, I just got the glitch on a mount with the modular tank where two mounts are showing at once. Need the logs?

It was on a booster that was attached via the radial decoupler. The main tanks seems to cycle fine.

**Comment by shadowmage45** [comment]
If you are using the latest release, then yes, logs please.

Any other steps to reproduce?
1 - attach radial decoupler to -something-
2 - attach tank to radial decoupler
3 - mount glitches out?

**Comment by Jimbodiah** [comment]
Will send logs tomorrow.

i had tanks in the radial decoupler and then wanted to change the mount. After cycling through 2-3 types it glitched.

**Comment by shadowmage45** [comment]
Any update on this?  I was not able to reproduce given the simple test case listed above.  Granted I do not have the texture sets installed on my dev setup at the moment, so if there was some texture switching involved that could be useful information to have.

**Comment by Jimbodiah** [comment]
Cripes... Forgot all about it. Been busy getting six ships in duna orbit and prepping base/miners for arrival of 20 kerbals next. will make some ships tomorrow and see if I can get it ti happen again.

**Comment by shadowmage45** [comment]
Have not been able to reproduce this issue during testing.  Please update with more information if you see it pop up again (logs, exact steps to reproduce, etc), and I will re-open the issue.

**Comment by Jimbodiah** [comment]
Haven't seen it lately, but have not changed many tank setups as I tend to use sub-assemblies for all my lifters now, since I have built one for probably any weight class I could want (Delta II to Jupiter 3).
