### ISSUE TITLE
Fairing request

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#95]
Is there any way to get a fairing that is shapeable like the current pedal one, but without a bottom and pedal function? It is for interstages that need to be matched to the next stage and could go on tanks with slanted sides (see picture).

http://dasher.nl/kerbal/sstu_fairing.jpg

I would like to have it run straight down and taper out near the bottom where the previous stage is, so just upside down. I know I can just turn the pedal upside down, but then I would jettison my engine upon staging ;)

It's to replicate this kind of fairing (interstage, both pieces combined):
http://www.aerospaceweb.org/question/spacecraft/constellation/ares-V-exploded.jpg

One solution might be a copy of the current pedal that works the other way around (straight part at the top) and that just seperates upon staging, not open up and require a manual release.

**Comment by shadowmage45** [comment]
Extremely difficult to do from a coding perspective, given the numerous interactions this module has with both other modules and user input.

The long-term goal for this module is to have a third diameter and height setting, for a central 'ring'.  So you can adjust top diameter, bottom diameter, and center diameter, as well as move the center-taper point up/down between the top and bottom.

However, I do not anticipate having the GUI necessary to rework the fairing module with these capabilities until after 1.1 is released (at which point the fairings will have a custom config GUI, and I will likely even allow more than 1 split/ring, so you could make semi-curved fairings).

Alternatively, the upcoming 'Interstage Decoupler' -will - have bi-conic ability like the petal adapter part -- much easier to integrate onto a part with limited features, than it is to integrate into a module that is used... everywhere.

**Comment by Jimbodiah** [comment]
wow that is quite complicated what you have in mind.

**Comment by shadowmage45** [comment]
Rolling this into #92, as I believe it will fit your needs, though it would be a separate part.  Will not be changing the fairing behavior again anytime soon; was a headache enough getting it sorted out for the engines/tanks/upper stage stuff.

Feel free to open a new request regarding this issue sometime after 1.1 is released and I can do custom GUIs for stuff.

**Comment by Jimbodiah** [comment]
:100:
