### ISSUE TITLE
Strut placement

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#97]
Whenever I place a strut from booster to main tank, it sees the last click as a double click, thereby seperating the piece from the main build.

**Comment by shadowmage45** [comment]
Likely nothing I can do about this.  I cannot alter stock strut behavior, nor the giant mess of hacks they use to enable them.

**Comment by blowfishpro** [comment]
As a workaround, get KJR.  No seriously.  The way things flop around in stock is ridiculous.

**Comment by Jimbodiah** [comment]
Already use KJR, one of the pre-requisite mods next to mechjeb and SSTU ;)

I need struts to keep the booster from flapping all over the place and only notice the behavior (strut placement) on SSTU tanks. hence my "issue".

Is there any way to get the boosters to stay in place with those radial decouplers? I ten to add two struts per booster at the top to keep them from pointing into another direction (mostly inwards).

**Comment by shadowmage45** [comment]
I will do some investigation regarding colliders, though there is likely little/nothing that I can do to fix the stock strut behavior.

I have noticed that the surface attach on the tanks is a bit funky until you pick them up and put them back down again in the editor.  Have you tried this with your tanks prior to putting struts on them? (E.g. if you change the tank model, simply move the craft in the editor; it seems to trigger a re-calculation of the surface-attach colliders).

**Comment by Jimbodiah** [comment]
The struts seem fine now... don't know what's up, let's write it off as another KSP quirk.

**Comment by shadowmage45** [comment]
I believe part of this bug might have been related to the editor lag induced by the fairing code (as it was giving me problems when placing struts; would 'pick up' the fuel tank when I attached the second strut point).

Is this still a noticeable problem in your games with the latest release?

**Comment by Jimbodiah** [comment]
Only rarely, had it with a fuel line yesterday (not latest release).
