### ISSUE TITLE
SSTU MUS-A Split Tank: Separation between tank and mount

### ISSUE THREAD

**Issue by lynwoodm** [shadowmage45/SSTULabs#98]
I'm not sure if this is a problem on my end or an actual bug, but there is a huge split between the tank and mount on this fuel tank. 
![screenshot from 2015-12-06 12 58 29](https://cloud.githubusercontent.com/assets/15900022/11614750/c05eb458-9c19-11e5-9eac-2231d1b65f63.png)

**Comment by shadowmage45** [comment]
was a problem with the pre-4 release, has been fixed in pre-5; please redownload

**Comment by Jimbodiah** [comment]
Yeah, keep up!  ;) hahah, Mage is too fast for us, puts out new builds faster than we can build rockets ;)
