### ISSUE TITLE
Intermediate engine sizes

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#99]
Would it be possible to have a single engine between the J2 and the RL10... namely one with around 200-300 thrust? I know you are working on some other engine types, just don't know if this is one of them. There is nothing between the 40 thrust and 650 thrust without resorting to clustered smaller ones.

**Comment by blowfishpro** [comment]
I think the RL60 would fill this gap nicely.  It has almost 2.5 times the thrust of the RL10B2 but is not any larger.  Can't remember if it's on the engine list already.  Reference material is somewhat hard to come by though, particularly since it's still in development.

**Comment by Jimbodiah** [comment]
I just noticed the J2 has terrible thrust in atmosphere, only 50% of vacuum. The RS25 has 1100 atm and 1300 vac, that is why I could not get the J2 to lift a small rockets, while the RS25 at 40% was just fine.

**Comment by blowfishpro** [comment]
The RS-25 has a nozzle optimized for both atmospheric and vacuum performance, whereas the J2 is optimized for vacuum performance only.   Theoretically, you could fit the J2 with a nozzle better suited for atmospheric operation, but you would of course loose vacuum performance.  But performance wouldn't be great - it's really designed as an upper stage engine.

**Comment by Jimbodiah** [comment]
Indeed. Stock parts have some engines with the needed thrust, but their base size is too big. Stock parts suck :)

**Comment by shadowmage45** [comment]
List of 'planned' parts (no set schedule on most)
https://github.com/shadowmage45/SSTULabs/wiki/Parts---Master-List

List of engines / stats for those engines on the planned parts list (and a few extras)
https://docs.google.com/spreadsheets/d/1VJtB_ma_ZW1HGOtkfO05KQm07zoGvmkGY3JZFbHs0s4/edit#gid=0

I -would- already be working on more engines (J-2X and RS-68 have mostly finished geometry), but people decided they would rather have me use my time to rework the command pods and service modules; democracy in action.

**Comment by Jimbodiah** [comment]
Can't you do both at the same time ;)  hehehe....   I wish I could help, but all I can do is sit there like a deer looking into the headlights.

**Comment by Jimbodiah** [comment]
My god, man. You have a lot of cool stuff planned. If there is any way I can help... I write software, but it's mostly a kind of Basic environment for servo/plc stuff.

**Comment by shadowmage45** [comment]
Thanks for the offer :)
Most of the work to be done unfortunately is modeling/texturing/art type stuff.
I'm sure I'll write up a few more 'modular part' plugins over time, but at this point it is almost templated work where I can just fill-in-the-blanks / link it together.  Aside from the parachute that I'm working on currently, the only other large/new plugin that I plan would be a multi-wheel capable plugin for integrated rover bodies; I likely won't be doing it though until 1.1, as I would just have to re-do it at that point anyhow. 

I should add that for the most part it does not matter to me what order I get these parts done in; I won't be really playing KSP again until after 1.1 + time for me to update.  But, the more I get done prior to that, the more will be available to play with while I un-break my code.

**Comment by Jimbodiah** [comment]
Modding is your way of playing KSP :)   Don't burn yourself out!!!   I think you have THE best parts mod going with what's in here already and what you are planning. The freaking updates will cause a headache every single time.

**Comment by shadowmage45** [comment]
No need for a generic 'more engines' issue -- will open up specific 'new part' tickets if/when they re needed and as the parts get scheduled.
